import assert from "node:assert/strict";
import { PlayerPacketEncoder } from "@server/network/encoding/PlayerPacketEncoder";
import { PlayerSyncSession } from "@server/network/PlayerSyncSession";
import { CombatBroadcaster } from "@server/network/broadcast/CombatBroadcaster";
import { PlayerState } from "@server/game/player";
import { createTestGamemode } from "./fixtures/createTestGamemode";
import { registerSkillConfiguration } from "@server/game/combat/SkillConfigurationProvider";
registerSkillConfiguration({ computeCombatLevel: () => 3, skillRestoreIntervalTicks: 100, skillBoostDecayIntervalTicks: 100, hitpointRegenIntervalTicks: 100, hitpointOverhealDecayIntervalTicks: 100, preserveDecayMultiplier: 1.5 });
const mode = createTestGamemode("sote-visibility", "Sotetseg visibility");
const players = [1, 2, 3].map(id => { const p = new PlayerState(id, 3278, 4315, 0, mode); p.name = `p${id}`; p.worldViewId = 4000; return p; });
const [runner, other, spectator] = players;
const services: any = { players: { getById: (id: number) => players.find(p => p.id === id), forEach: (f: any) => players.forEach(p => f(p, p)), forEachBot: () => { } }, appearanceService: { buildAnimPayload: () => undefined } };
const encoder = new PlayerPacketEncoder(services), sessions = players.map(() => new PlayerSyncSession());
const frame: any = { tick: 1, tickMs: 600, playerViews: new Map(players.map(p => [p.id, { id: p.id, x: p.x, y: p.y, level: p.level, rot: p.rot, name: p.name, appearance: p.appearance }])),
    playerSteps: new Map(), interactionIndices: new Map(), pendingSequences: new Map(), pendingFaceDirs: new Map(), hitsplats: [], forcedChats: [], forcedMovements: [], spotAnimations: [], chatMessages: [], colorOverrides: new Map() };
const sync = () => { players.forEach((p, i) => encoder.buildPlayerSyncPacket(sessions[i], p, frame)); frame.tick++; };
sync();
assert(sessions.every(s => s.playersIndices.length === 3));
runner.encounterVisibility = { key: "maze", group: "shadow", privateToGroup: true };
other.encounterVisibility = { key: "maze", group: "real" };
sync();
assert(!sessions[1].playersIndices.includes(runner.id));
assert(!sessions[2].playersIndices.includes(runner.id), "unscoped spectator cannot reveal runner");
assert(sessions[0].playersIndices.includes(runner.id), "runner still sees themselves");
assert(!sessions[0].playersIndices.includes(other.id));
runner.encounterVisibility = undefined;
other.encounterVisibility = undefined;
sync();
assert(sessions.every(s => s.playersIndices.length === 3), "phase cleanup re-adds hidden actors");
let sent: number[] = [];
const broadcaster = new CombatBroadcaster({ forEachPlayer: f => players.forEach(p => f(p as any, p)), withDirectSendBypass: (_c, f) => f() });
const ctx: any = { cyclesPerTick: 30, sendWithGuard: (p: PlayerState) => sent.push(p.id), broadcast: () => assert.fail("private spot cannot broadcast"), broadcastToNearby: () => assert.fail("private spot cannot broadcast nearby") };
frame.spotAnimations = [{ tick: 1, spotId: 60000, ownerPlayerId: other.id, worldViewId: 4000, durationTicks: 1, tile: { x: 3278, y: 4315, level: 0 } }];
broadcaster.flush(frame, ctx);
assert.deepEqual(sent, [other.id]);
sent = [];
other.worldViewId = 4001;
broadcaster.flush(frame, ctx);
assert.deepEqual(sent, [], "late effects cannot leak into another instance");
console.log("Real player sync hides/restores maze runner per recipient; marker broadcast is owner- and instance-scoped");
