import { EquipmentSlot } from "@august/osrs-engine/config/player/Equipment";
import { SkillId } from "@august/osrs-engine/skill/skills";
import type { PlayerState } from "@server/game/player";
import { NpcPreDeathDecision, type IScriptRegistry, type NpcInteractionEvent, type ScriptServices } from "@server/game/scripts/types";
import { completeQuest, countCarriedItem, getQuestStage, meetsQuestRequirements, setQuestStage, takeQuestItems } from "@server/content/gamemodes/vanilla/quests/QuestService";
import { choose, option, run, sayNpc, sayPlayer, startConversation } from "@server/content/gamemodes/vanilla/quests/dialogue";
import type { QuestDefinition } from "@server/content/gamemodes/vanilla/quests/types";
import { ITEM, LOC, NPC, STAGE_BLACK_ARMBAND, STAGE_BLACK_CANDLESTICK, STAGE_BLACK_GRIP, STAGE_BLACK_HQ, STAGE_BLACK_KATRINE, STAGE_BLACK_MANSION, STAGE_BLACK_PAPERS, STAGE_COMPLETE, STAGE_PHOENIX_ALFONSE, STAGE_PHOENIX_ARMBAND, STAGE_PHOENIX_CHARLIE, STAGE_PHOENIX_GRIP, STAGE_PHOENIX_STRAVEN, STAGE_STARTED } from "@server/content/gamemodes/vanilla/quests/definitions/heroes-quest/constants";

function context(event: NpcInteractionEvent, name: string) { return { player: event.player, services: event.services, npcId: event.npc.typeId, npcName: name }; }
function has(player: PlayerState, services: ScriptServices, itemId: number, quantity = 1) { return countCarriedItem(player, services, itemId) >= quantity; }
function owns(player: PlayerState, services: ScriptServices, itemId: number) { return services.inventory.findOwnedItemLocation(player, itemId) !== undefined; }
function give(player: PlayerState, services: ScriptServices, itemId: number, quantity = 1): boolean { const result = services.inventory.addItemToInventory(player, itemId, quantity); if (result.added !== quantity) { services.messaging.sendGameMessage(player, "You need more free inventory space."); return false; } services.inventory.snapshotInventory(player); return true; }
function take(player: PlayerState, services: ScriptServices, itemId: number, quantity = 1) { return takeQuestItems(player, services, [{ itemId, quantity, journalLabel: "" }]); }
function isPhoenix(player: PlayerState) { return (player.varps.getVarpValue(145) & (1 << 4)) !== 0; }

function achietties(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => {
    const stage = getQuestStage(event.player, quest); const ctx = context(event, "Achietties");
    if (stage === 0) { if (!meetsQuestRequirements(event.player, event.services, quest)) { startConversation(ctx, [sayNpc("You need 55 Quest Points, the four required quests, and the required skills.")]); return; } startConversation(ctx, [sayNpc("To enter the Heroes' Guild, bring me a firebird feather, a cooked lava eel, and a master thief's armband."), choose([option("I accept.", [run(({ player, services }) => setQuestStage(player, quest, services, STAGE_STARTED))]), option("Not now.")])]); return; }
    if (stage < STAGE_COMPLETE && has(event.player, event.services, ITEM.fireFeather) && has(event.player, event.services, ITEM.cookedLavaEel) && has(event.player, event.services, ITEM.thievesArmband)) {
        startConversation(ctx, [sayPlayer("I have all three proofs."), sayNpc("Excellent. You are worthy of the Heroes' Guild."), run(({ player, services }) => { if (!take(player, services, ITEM.fireFeather) || !take(player, services, ITEM.cookedLavaEel) || !take(player, services, ITEM.thievesArmband)) return; completeQuest(player, services, quest); })]); return;
    }
    startConversation(ctx, [sayNpc(stage >= STAGE_COMPLETE ? "Welcome, hero." : "Bring all three proofs together.")]);
}; }

function straven(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { const stage = getQuestStage(event.player, quest); if (stage === STAGE_STARTED && isPhoenix(event.player)) { startConversation(context(event, "Straven"), [sayNpc("Steal Scarface Pete's candlestick. Tell Alfonse in Brimhaven the password Gherkin."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_PHOENIX_STRAVEN))]); return; } if (stage === STAGE_PHOENIX_GRIP && has(event.player, event.services, ITEM.petesCandlestick)) { startConversation(context(event, "Straven"), [sayNpc("A fine theft. Take this master thief's armband."), run(({ player, services }) => { if (!take(player, services, ITEM.petesCandlestick)) return; if (give(player, services, ITEM.thievesArmband)) setQuestStage(player, quest, services, STAGE_PHOENIX_ARMBAND); })]); return; } startConversation(context(event, "Straven"), [sayNpc("The Phoenix Gang remembers you.")]); }; }
function alfonse(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) === STAGE_PHOENIX_STRAVEN) { startConversation(context(event, "Alfonse"), [sayPlayer("Gherkin."), sayNpc("Speak to Charlie around the back."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_PHOENIX_ALFONSE))]); return; } startConversation(context(event, "Alfonse"), [sayNpc("The kitchen is private.")]); }; }
function charlie(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) === STAGE_PHOENIX_ALFONSE) { startConversation(context(event, "Charlie the cook"), [sayNpc("Grip carries the treasure-room key. Lure him out and take the candlestick."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_PHOENIX_CHARLIE))]); return; } startConversation(context(event, "Charlie the cook"), [sayNpc("Keep your voice down.")]); }; }
function katrine(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { const stage = getQuestStage(event.player, quest); if (stage === STAGE_STARTED && !isPhoenix(event.player)) { startConversation(context(event, "Katrine"), [sayNpc("Our Brimhaven gang can get you into Scarface Pete's mansion. Password: four-leaved clover."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_BLACK_KATRINE))]); return; } if (stage === STAGE_BLACK_CANDLESTICK && has(event.player, event.services, ITEM.petesCandlestick)) { startConversation(context(event, "Katrine"), [sayNpc("You stole Pete's candlestick. You have earned this armband."), run(({ player, services }) => { if (!take(player, services, ITEM.petesCandlestick)) return; if (give(player, services, ITEM.thievesArmband)) setQuestStage(player, quest, services, STAGE_BLACK_ARMBAND); })]); return; } startConversation(context(event, "Katrine"), [sayNpc("Don't forget who helped you.")]); }; }
function grubor(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) === STAGE_BLACK_KATRINE) { startConversation(context(event, "Grubor"), [sayPlayer("Four-leaved clover."), sayNpc("Welcome to the Brimhaven Black Arm headquarters."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_BLACK_HQ))]); return; } startConversation(context(event, "Grubor"), [sayNpc("I'm busy.")]); }; }
function trobert(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { const stage = getQuestStage(event.player, quest); if (stage === STAGE_BLACK_HQ || (stage === STAGE_BLACK_PAPERS && !owns(event.player, event.services, ITEM.idPapers))) { startConversation(context(event, "Trobert"), [sayNpc("Impersonate Hartigen, Grip's new deputy. These are his identity papers."), run(({ player, services }) => { if (give(player, services, ITEM.idPapers)) setQuestStage(player, quest, services, STAGE_BLACK_PAPERS); })]); return; } startConversation(context(event, "Trobert"), [sayNpc("Get inside Pete's mansion and find Grip's key.")]); }; }
function garv(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) === STAGE_BLACK_PAPERS && has(event.player, event.services, ITEM.blackFullHelm) && has(event.player, event.services, ITEM.blackPlatebody) && has(event.player, event.services, ITEM.blackPlatelegs)) { startConversation(context(event, "Garv"), [sayNpc("Hartigen? Your armour and papers look right. Go in."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_BLACK_MANSION))]); return; } startConversation(context(event, "Garv"), [sayNpc("Only Hartigen in full black armour may enter.")]); }; }
function grip(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) === STAGE_BLACK_MANSION && has(event.player, event.services, ITEM.idPapers)) { startConversation(context(event, "Grip"), [sayNpc("Your papers are in order, deputy. Keep watch over the mansion."), run(({ player, services }) => { take(player, services, ITEM.idPapers); setQuestStage(player, quest, services, STAGE_BLACK_GRIP); })]); return; } startConversation(context(event, "Grip"), [sayNpc("Keep away from Pete's treasure room.")]); }; }

function registerThieves(quest: QuestDefinition, registry: IScriptRegistry): void {
    registry.registerNpcPreDeath(NPC.grip, (event) => { const player = event.killer; if (!player) return NpcPreDeathDecision.Allow; const stage = getQuestStage(player, quest); if (stage !== STAGE_PHOENIX_CHARLIE && stage !== STAGE_BLACK_GRIP) return NpcPreDeathDecision.Allow; if (!owns(player, event.services, ITEM.gripsKeyring)) give(player, event.services, ITEM.gripsKeyring); if (stage === STAGE_PHOENIX_CHARLIE) setQuestStage(player, quest, event.services, STAGE_PHOENIX_GRIP); return NpcPreDeathDecision.Allow; });
    for (const locId of LOC.candlestickChest) registry.registerItemOnLoc(ITEM.gripsKeyring, locId, ({ player, services }) => { const stage = getQuestStage(player, quest); if (stage !== STAGE_PHOENIX_GRIP && stage !== STAGE_BLACK_GRIP) return; if (!owns(player, services, ITEM.petesCandlestick) && give(player, services, ITEM.petesCandlestick) && stage === STAGE_BLACK_GRIP) setQuestStage(player, quest, services, STAGE_BLACK_CANDLESTICK); });
}

function registerProofItems(quest: QuestDefinition, registry: IScriptRegistry): void {
    registry.registerNpcPreDeath(NPC.iceQueen, (event) => { const player = event.killer; if (player && getQuestStage(player, quest) >= STAGE_STARTED && !owns(player, event.services, ITEM.iceGloves)) give(player, event.services, ITEM.iceGloves); return NpcPreDeathDecision.Allow; });
    registry.registerNpcPreDeath(NPC.firebird, (event) => { const player = event.killer; if (!player || getQuestStage(player, quest) < STAGE_STARTED) return NpcPreDeathDecision.Allow; if (event.services.equipment.getEquippedItem(player, EquipmentSlot.GLOVES) !== ITEM.iceGloves) { event.services.messaging.sendGameMessage(player, "The feather is too hot to pick up without ice gloves."); return NpcPreDeathDecision.Allow; } if (!owns(player, event.services, ITEM.fireFeather)) give(player, event.services, ITEM.fireFeather); return NpcPreDeathDecision.Allow; });
    const gerrant = (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) >= STAGE_STARTED && !owns(event.player, event.services, ITEM.blamishSlime) && !owns(event.player, event.services, ITEM.blamishOil) && !owns(event.player, event.services, ITEM.oilyFishingRod)) { startConversation(context(event, "Gerrant"), [sayNpc("Mix this blamish snail slime into an unfinished harralander potion, then oil a fishing rod."), run(({ player, services }) => { give(player, services, ITEM.blamishSlime); })]); return; } startConversation(context(event, "Gerrant"), [sayNpc("An oily rod can survive the heat of lava-eel waters.")]); };
    registry.registerNpcScript({ npcId: NPC.gerrant, option: "talk-to", handler: gerrant });
    registry.registerItemOnItem(ITEM.blamishSlime, ITEM.harralanderPotionUnf, ({ player, services }) => { if (!take(player, services, ITEM.blamishSlime) || !take(player, services, ITEM.harralanderPotionUnf)) return; give(player, services, ITEM.blamishOil); });
    registry.registerItemOnItem(ITEM.blamishOil, ITEM.fishingRod, ({ player, services }) => { if (!take(player, services, ITEM.blamishOil) || !take(player, services, ITEM.fishingRod)) return; give(player, services, ITEM.oilyFishingRod); });
    registry.registerLocScript({ locId: LOC.lavaFishingSpot, action: undefined, handler: ({ player, services }) => { if (getQuestStage(player, quest) < STAGE_STARTED || !has(player, services, ITEM.oilyFishingRod) || !has(player, services, ITEM.fishingBait)) { services.messaging.sendGameMessage(player, "You need an oily fishing rod and bait."); return; } if (services.skills.getSkill(player, SkillId.Fishing).baseLevel < 53) return; take(player, services, ITEM.fishingBait); give(player, services, ITEM.rawLavaEel); services.skills.addSkillXp(player, SkillId.Fishing, 60); } });
    registry.registerItemAction(ITEM.rawLavaEel, ({ player, services }) => { if (services.skills.getSkill(player, SkillId.Cooking).baseLevel < 53 || !take(player, services, ITEM.rawLavaEel)) return; give(player, services, ITEM.cookedLavaEel); services.skills.addSkillXp(player, SkillId.Cooking, 140); }, "cook");
}

export function registerHeroesQuestInteractions(quest: QuestDefinition, registry: IScriptRegistry, _services: ScriptServices): void {
    const handlers = [[NPC.achietties, achietties(quest)], [NPC.straven, straven(quest)], [NPC.alfonse, alfonse(quest)], [NPC.charlieCook, charlie(quest)], [NPC.katrine, katrine(quest)], [NPC.grubor, grubor(quest)], [NPC.trobert, trobert(quest)], [NPC.garv, garv(quest)], [NPC.grip, grip(quest)]] as const;
    for (const [npcId, handler] of handlers) { registry.registerNpcScript({ npcId, option: "talk-to", handler }); registry.registerNpcScript({ npcId, option: undefined, handler }); }
    registerThieves(quest, registry); registerProofItems(quest, registry);
}
