export {
    DEFAULT_WATER_MATERIAL,formatPlayerCombatLabel,ICE_WATER_MATERIAL,MATERIAL_TEXTURE_ROWS,MAX_CLIENT_TICK_DEBT,MAX_CLIENT_TICKS_PER_FRAME,MAX_HIT_ENTRIES,MAX_TEXTURES,optimizeAssumingFlatsHaveSameFirstAndLastData,SWAMP_WATER_MATERIAL,TEXTURE_SIZE,TextureFilterMode,VANILLA_WATER_SURFACE_COLORS,WATER_FLAG_HAS_FOAM,
    WATER_FLAG_NORMAL_MAP_2,WATER_TEXTURE_ASSETS,WATER_TEXTURE_SIZE,type BrowserQualityProfile,type BrowserQualityProfileKey,type ColorRgb,type InteractHighlightTarget,type LocHighlightTarget,type LocReloadBatchState,type NpcHighlightTarget,type StreamMapBatch,
    type WaterMaterialParams
} from "@client/engine/rendering/render/constants";
