export {
    TextureFilterMode,
    type BrowserQualityProfileKey,
    type BrowserQualityProfile,
    type ColorRgb,
    type LocReloadBatchState,
    type StreamMapBatch,
    type WaterMaterialParams,
    type LocHighlightTarget,
    type NpcHighlightTarget,
    type InteractHighlightTarget,
    optimizeAssumingFlatsHaveSameFirstAndLastData,
    formatPlayerCombatLabel,
    MAX_TEXTURES,
    TEXTURE_SIZE,
    MATERIAL_TEXTURE_ROWS,
    WATER_FLAG_HAS_FOAM,
    WATER_FLAG_NORMAL_MAP_2,
    WATER_TEXTURE_SIZE,
    WATER_TEXTURE_ASSETS,
    MAX_HIT_ENTRIES,
    MAX_CLIENT_TICKS_PER_FRAME,
    MAX_CLIENT_TICK_DEBT,
    DEFAULT_WATER_MATERIAL,
    SWAMP_WATER_MATERIAL,
    ICE_WATER_MATERIAL,
    VANILLA_WATER_SURFACE_COLORS,
} from "@client/engine/rendering/render/constants";
