// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Woodcutting/Level_up_table page. Blank requires fields are intended for hand editing.
import { SkillId } from "@august/osrs-engine/skill/skills";
import type { SkillGuideData } from "@server/content/gamemodes/vanilla/skill-guide/types";

export const woodcuttingSkillGuide: SkillGuideData = {
    skillId: SkillId.Woodcutting,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: 1511,
                    level: 1,
                    name: "Chop logs",
                    requires: "",
                },
                {
                    itemId: 1351,
                    level: 1,
                    name: "Chop with bronze axes",
                    requires: "",
                },
                {
                    itemId: 1349,
                    level: 1,
                    name: "Chop with iron axes",
                    requires: "",
                },
                {
                    itemId: 1353,
                    level: 6,
                    name: "Chop with steel axes",
                    requires: "",
                },
                {
                    itemId: 1361,
                    level: 11,
                    name: "Chop with black axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 12,
                    name: "Carve log canoes",
                    requires: "",
                },
                {
                    itemId: 1521,
                    level: 15,
                    name: "Chop oak logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 19,
                    name: "New information is available from the 22570",
                    requires: "",
                },
                {
                    itemId: 1355,
                    level: 21,
                    name: "Chop with mithril axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 27,
                    name: "Carve dugout canoes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "New information is available from the 22570",
                    requires: "",
                },
                {
                    itemId: 1519,
                    level: 30,
                    name: "Chop willow logs",
                    requires: "",
                },
                {
                    itemId: 1357,
                    level: 31,
                    name: "Chop with adamant axes",
                    requires: "",
                },
                {
                    itemId: 1359,
                    level: 41,
                    name: "Chop with rune axes",
                    requires: "",
                },
                {
                    itemId: 23279,
                    level: 41,
                    name: "Chop with gilded axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Carve stable dugout canoes",
                    requires: "",
                },
                {
                    itemId: 1517,
                    level: 45,
                    name: "Chop maple logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Carve waka canoes",
                    requires: "",
                },
                {
                    itemId: 1515,
                    level: 60,
                    name: "Chop yew logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery",
                    requires: "",
                }
            ]
        },
        {
            label: "Members",
            entries: [
                {
                    itemId: 2862,
                    level: 1,
                    name: "Chop achey tree logs",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 1,
                    name: "Receive a maximum of 1 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Chop with bronze felling axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Chop with iron felling axes",
                    requires: "",
                },
                {
                    itemId: 1823,
                    level: 1,
                    name: "Cut a Kharidian cactus to fill a waterskin",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 6,
                    name: "Chop with steel felling axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 11,
                    name: "Chop with black felling axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Chop with mithril felling axes",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 24,
                    name: "Receive a maximum of 2 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Chop with adamant felling axes",
                    requires: "",
                },
                {
                    itemId: 6333,
                    level: 35,
                    name: "Chop teak logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Make forester's rations (with Cooking 35)",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Make secateurs attachments (with Smithing 35)",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 36,
                    name: "Receive a maximum of 3 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Chop jatoba logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 41,
                    name: "Chop with rune felling axes",
                    requires: "",
                },
                {
                    itemId: 13355,
                    level: 42,
                    name: "Chop juniper logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Wear lumberjack clothing",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Wear the forestry outfit",
                    requires: "",
                },
                {
                    itemId: 3239,
                    level: 45,
                    name: "Chop bark",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 48,
                    name: "Receive a maximum of 4 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: 6332,
                    level: 50,
                    name: "Chop mahogany logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Make clothes pouches (with Crafting 50)",
                    requires: "",
                },
                {
                    itemId: 10810,
                    level: 54,
                    name: "Chop arctic pine logs",
                    requires: "",
                },
                {
                    itemId: 10812,
                    level: 56,
                    name: "Split arctic pine logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Craft Neitiznot shield",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Access the Woodcutting Guild",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 60,
                    name: "Receive a maximum of 5 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: 6739,
                    level: 61,
                    name: "Chop with dragon axes, 3rd Age axes, and infernal axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Chop with dragon felling axes",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Chop with 3rd Age felling axes",
                    requires: "",
                },
                {
                    itemId: 6004,
                    level: 65,
                    name: "Chop mushrooms, mort myre fungus, and sulliuscep caps from Sulliuscep",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Chop camphor logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Make nature offerings (with Farming 50)",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 72,
                    name: "Receive a maximum of 6 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: 1513,
                    level: 75,
                    name: "Chop magic logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Make sturdy harnesses (with Smithing 75)",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Chop Demon tears",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Chop ironwood logs",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 84,
                    name: "Receive a maximum of 7 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: 19669,
                    level: 90,
                    name: "Chop redwood logs",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Chop rosewood logs",
                    requires: "",
                },
                {
                    itemId: 9094,
                    level: 96,
                    name: "Receive a maximum of 8 Kindling from trees at Ice demon",
                    requires: "",
                },
                {
                    itemId: 9807,
                    level: 99,
                    name: "Buy the Woodcutting cape and hood from Wilfred south of the furnace in Lumbridge, and wear them",
                    requires: "",
                }
            ]
        }
    ]
};
