import type { PlayerState } from "@server/game/player";
import { NpcPreDeathDecision, type IScriptRegistry, type NpcInteractionEvent, type ScriptServices } from "@server/game/scripts/types";
import { completeQuest, countCarriedItem, getQuestStage, meetsQuestRequirements, setQuestStage, takeQuestItems } from "@server/content/gamemodes/vanilla/quests/QuestService";
import { choose, option, run, sayNpc, sayPlayer, showItem, startConversation } from "@server/content/gamemodes/vanilla/quests/dialogue";
import type { QuestDefinition } from "@server/content/gamemodes/vanilla/quests/types";
import { ITEM, LOC, NPC, STAGE_CHARLIE_CLUE, STAGE_COMPLETE, STAGE_DEMON_DEFEATED, STAGE_FOUND_JOURNAL, STAGE_FOUND_PRISONER, STAGE_GIVEN_TWIGS, STAGE_HAZELMERE, STAGE_INVASION_PLANS, STAGE_LUMBER_ORDER, STAGE_RELAYED_MESSAGE, STAGE_RELEASED, STAGE_SEARCHING_DACONIA, STAGE_SPOKEN_GLOUGH, STAGE_SPOKEN_PRISONER, STAGE_STARTED, STAGE_TRAPDOOR, TILE, VARP_GRAND_TREE_PILLARS } from "@server/content/gamemodes/vanilla/quests/definitions/grand-tree/constants";

function context(event: NpcInteractionEvent, name: string) { return { player: event.player, services: event.services, npcId: event.npc.typeId, npcName: name }; }
function has(player: PlayerState, services: ScriptServices, itemId: number, quantity = 1) { return countCarriedItem(player, services, itemId) >= quantity; }
function owns(player: PlayerState, services: ScriptServices, itemId: number) { return services.inventory.findOwnedItemLocation(player, itemId) !== undefined; }
function give(player: PlayerState, services: ScriptServices, itemId: number, quantity = 1): boolean { const result = services.inventory.addItemToInventory(player, itemId, quantity); if (result.added !== quantity) { services.messaging.sendGameMessage(player, "You need more free inventory space."); return false; } services.inventory.snapshotInventory(player); return true; }
function take(player: PlayerState, services: ScriptServices, itemId: number, quantity = 1) { return takeQuestItems(player, services, [{ itemId, quantity, journalLabel: "" }]); }
function setAux(player: PlayerState, services: ScriptServices, value: number) { player.varps.setVarpValue(VARP_GRAND_TREE_PILLARS, value); services.variables.sendVarp(player, VARP_GRAND_TREE_PILLARS, value); }

function narnode(quest: QuestDefinition) {
    return (event: NpcInteractionEvent): void => {
        const stage = getQuestStage(event.player, quest); const ctx = context(event, "King Narnode Shareen");
        if (stage === 0) {
            if (!meetsQuestRequirements(event.player, event.services, quest)) { startConversation(ctx, [sayNpc("The climb through our tree requires level 25 Agility.")]); return; }
            startConversation(ctx, [sayNpc("The Grand Tree is dying. Take this bark sample to Hazelmere and translate his answer."), choose([option("I'd be happy to help.", [run(({ player, services }) => { if (!give(player, services, ITEM.barkSample) || !give(player, services, ITEM.translationBook)) return; setQuestStage(player, quest, services, STAGE_STARTED); }), showItem(ITEM.barkSample, "The King gives you a bark sample and translation book.")]), option("I don't want to get involved.")])]); return;
        }
        if (stage === STAGE_HAZELMERE) { startConversation(ctx, [sayPlayer("Hazelmere says a human carrying your seal was given Daconia rocks."), sayNpc("Relay this immediately to my guardian Glough."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_RELAYED_MESSAGE))]); return; }
        if (stage === STAGE_SPOKEN_GLOUGH) { startConversation(ctx, [sayNpc("Glough caught a human with Daconia rocks. Speak to the prisoner Charlie at the top of the tree."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_FOUND_PRISONER))]); return; }
        if (stage === STAGE_FOUND_JOURNAL && has(event.player, event.services, ITEM.gloughJournal)) { startConversation(ctx, [sayPlayer("Glough's journal says he paid Charlie."), sayNpc("I will release you, but investigate the shipyard before accusing my guardian."), run(({ player, services }) => { take(player, services, ITEM.gloughJournal); setQuestStage(player, quest, services, STAGE_RELEASED); })]); return; }
        if (stage === STAGE_INVASION_PLANS && has(event.player, event.services, ITEM.invasionPlans)) { startConversation(ctx, [sayPlayer("These plans prove Glough is building a fleet to attack humanity."), sayNpc("The guards found four strange twigs. Perhaps they unlock his secret."), run(({ player, services }) => { if (!take(player, services, ITEM.invasionPlans)) return; for (const twig of ITEM.twigs) if (!give(player, services, twig)) return; setAux(player, services, 0); setQuestStage(player, quest, services, STAGE_GIVEN_TWIGS); })]); return; }
        if (stage === STAGE_DEMON_DEFEATED) { startConversation(ctx, [sayPlayer("Glough set a black demon on me and hid Daconia throughout the roots."), sayNpc("Then search every root. The tree still may be saved."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_SEARCHING_DACONIA))]); return; }
        if (stage === STAGE_SEARCHING_DACONIA && has(event.player, event.services, ITEM.daconiaRock)) { startConversation(ctx, [sayPlayer("I found the last Daconia rock."), sayNpc("The tree is recovering already. Humans and gnomes can live in peace."), run(({ player, services }) => { if (!take(player, services, ITEM.daconiaRock)) return; completeQuest(player, services, quest); setAux(player, services, 0); })]); return; }
        if (stage >= STAGE_COMPLETE) { startConversation(ctx, [sayNpc("The Grand Tree is healthier than ever, thanks to you.")]); return; }
        const replacements = stage === STAGE_STARTED && !owns(event.player, event.services, ITEM.barkSample) ? [run(({ player, services }) => { give(player, services, ITEM.barkSample); if (!owns(player, services, ITEM.translationBook)) give(player, services, ITEM.translationBook); })] : [];
        startConversation(ctx, [sayNpc(stage >= STAGE_GIVEN_TWIGS ? "Expose Glough's secret beneath his house." : "Please continue your investigation."), ...replacements]);
    };
}

function hazelmere(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) !== STAGE_STARTED || !has(event.player, event.services, ITEM.barkSample)) { startConversation(context(event, "Hazelmere"), [sayNpc("Hubble, gobble, geh! ... human ... Daconia ... tree.")]); return; } startConversation(context(event, "Hazelmere"), [sayNpc("A human bearing the King's seal took Daconia stones. The Grand Tree will die."), run(({ player, services }) => { take(player, services, ITEM.barkSample); if (!owns(player, services, ITEM.hazelmereScroll)) give(player, services, ITEM.hazelmereScroll); setQuestStage(player, quest, services, STAGE_HAZELMERE); })]); }; }
function glough(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { const stage = getQuestStage(event.player, quest); if (stage === STAGE_RELAYED_MESSAGE) { startConversation(context(event, "Glough"), [sayNpc("Humans cannot be trusted! I will catch this saboteur."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_SPOKEN_GLOUGH))]); return; } startConversation(context(event, "Glough"), [sayNpc(stage >= STAGE_CHARLIE_CLUE ? "Stay out of my affairs, human!" : "The stronghold is for gnomes alone.")]); }; }
function charlie(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { const stage = getQuestStage(event.player, quest); if (stage === STAGE_FOUND_PRISONER) { startConversation(context(event, "Charlie"), [sayNpc("Glough paid me to retrieve Daconia. His journal proves it."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_SPOKEN_PRISONER))]); return; } if (stage === STAGE_LUMBER_ORDER && has(event.player, event.services, ITEM.lumberOrder)) { startConversation(context(event, "Charlie"), [sayNpc("That order came from Glough. Anita may have the key to his cupboard."), run(({ player, services }) => setQuestStage(player, quest, services, STAGE_CHARLIE_CLUE))]); return; } startConversation(context(event, "Charlie"), [sayNpc("Glough framed me!")]); }; }
function foreman(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) !== STAGE_RELEASED) { startConversation(context(event, "Foreman"), [sayNpc("This shipyard is restricted.")]); return; } startConversation(context(event, "Foreman"), [sayPlayer("Ka-Lu-Min."), sayNpc("Glough's latest lumber order. Take it and leave."), run(({ player, services }) => { if (give(player, services, ITEM.lumberOrder)) setQuestStage(player, quest, services, STAGE_LUMBER_ORDER); })]); }; }
function anita(quest: QuestDefinition) { return (event: NpcInteractionEvent): void => { if (getQuestStage(event.player, quest) === STAGE_CHARLIE_CLUE && !owns(event.player, event.services, ITEM.gloughKey)) { startConversation(context(event, "Anita"), [sayNpc("Glough left this key here. Please return it."), run(({ player, services }) => { give(player, services, ITEM.gloughKey); })]); return; } startConversation(context(event, "Anita"), [sayNpc("I'm worried about Glough.")]); }; }

function registerEvidence(quest: QuestDefinition, registry: IScriptRegistry): void {
    for (const locId of LOC.gloughChests) registry.registerLocScript({ locId, action: undefined, handler: ({ player, services }) => { if (getQuestStage(player, quest) !== STAGE_SPOKEN_PRISONER || owns(player, services, ITEM.gloughJournal)) { services.messaging.sendGameMessage(player, "You find nothing useful."); return; } if (give(player, services, ITEM.gloughJournal)) setQuestStage(player, quest, services, STAGE_FOUND_JOURNAL); } });
    for (const locId of LOC.gloughCupboards) { registry.registerItemOnLoc(ITEM.gloughKey, locId, ({ player, services }) => { if (getQuestStage(player, quest) !== STAGE_CHARLIE_CLUE) return; if (!owns(player, services, ITEM.invasionPlans) && give(player, services, ITEM.invasionPlans)) setQuestStage(player, quest, services, STAGE_INVASION_PLANS); }); registry.registerLocScript({ locId, action: undefined, handler: ({ player, services }) => services.messaging.sendGameMessage(player, getQuestStage(player, quest) === STAGE_CHARLIE_CLUE ? "The cupboard is locked. Anita may have Glough's key." : "The cupboard contains ordinary records.") }); }
}

function registerFinale(quest: QuestDefinition, registry: IScriptRegistry): void {
    ITEM.twigs.forEach((twig, index) => registry.registerItemOnLoc(twig, LOC.pillars[index], ({ player, services }) => { if (getQuestStage(player, quest) !== STAGE_GIVEN_TWIGS || !take(player, services, twig)) return; const mask = player.varps.getVarpValue(VARP_GRAND_TREE_PILLARS) | (1 << index); setAux(player, services, mask); if (mask === 0xf) { setQuestStage(player, quest, services, STAGE_TRAPDOOR); services.messaging.sendGameMessage(player, "The twigs spell TUZO. Glough's trapdoor unlocks."); } }));
    for (const locId of LOC.trapdoor) registry.registerLocScript({ locId, action: undefined, handler: ({ player, services }) => { if (getQuestStage(player, quest) < STAGE_TRAPDOOR) { services.messaging.sendGameMessage(player, "The trapdoor is locked by four carved pillars."); return; } services.movement.teleportPlayer(player, TILE.gloughTunnel.x, TILE.gloughTunnel.y, TILE.gloughTunnel.level); if (getQuestStage(player, quest) === STAGE_TRAPDOOR && !services.npc.findNearbyNpc(player, NPC.blackDemon, 20)) services.npc.spawnNpc({ id: NPC.blackDemon, x: TILE.demon.x, y: TILE.demon.y, level: 0, worldViewId: player.worldViewId, ownerPlayerId: player.id, lifetimeTicks: 1_000 }); } });
    registry.registerNpcPreDeath(NPC.blackDemon, (event) => { const player = event.killer; if (!player || event.npc.ownerPlayerId !== player.id || getQuestStage(player, quest) !== STAGE_TRAPDOOR) return NpcPreDeathDecision.Allow; setQuestStage(player, quest, event.services, STAGE_DEMON_DEFEATED); return NpcPreDeathDecision.Allow; });
    for (const locId of LOC.daconiaRoots) registry.registerLocScript({ locId, action: undefined, handler: ({ player, services }) => { if (getQuestStage(player, quest) !== STAGE_SEARCHING_DACONIA || owns(player, services, ITEM.daconiaRock)) { services.messaging.sendGameMessage(player, "You search the roots but find nothing."); return; } give(player, services, ITEM.daconiaRock); } });
}

export function registerGrandTreeInteractions(quest: QuestDefinition, registry: IScriptRegistry, _services: ScriptServices): void {
    const handlers = [[NPC.narnode, narnode(quest)], [NPC.hazelmere, hazelmere(quest)], [NPC.glough, glough(quest)], [NPC.charlie, charlie(quest)], [NPC.foreman, foreman(quest)], [NPC.anita, anita(quest)]] as const;
    for (const [npcId, handler] of handlers) { registry.registerNpcScript({ npcId, option: "talk-to", handler }); registry.registerNpcScript({ npcId, option: undefined, handler }); }
    registerEvidence(quest, registry); registerFinale(quest, registry);
}
