import {
    buildFreeToPlayQuestJournal,
    buildFreeToPlayQuestOverview,
    type FreeToPlayQuestContent,
} from "@server/content/gamemodes/vanilla/quests/content/freeToPlay";

/** Miniquests use the same display-only journal presentation as quests. */
export type MiniquestContent = FreeToPlayQuestContent;

export const MINIQUEST_CONTENT: readonly MiniquestContent[] = [
    { key: "alfred grimhand's barcrawl", displayName: "Alfred Grimhand's Barcrawl", description: "Alfred Grimhand's barcrawl card challenges you to sample drinks in pubs across Gielinor.", overviewStartText: "reading <col=800000>Alfred Grimhand's Barcrawl<col=000080> card in the <col=800000>Barbarian Outpost<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Medium", storyline: "Barbarian" }, requirementLines: ["Access to the Barbarian Outpost"], requiredItems: ["Coins for drinks", "The barcrawl card"], combatNotes: [], rewards: ["Completion credit for the Barcrawl", "Progress toward the Scorpion Catcher requirement"], outline: ["Collect the barcrawl card.", "Visit every listed bar and sample its signature drink.", "Return with the completed card."], },
    { key: "barbarian training", displayName: "Barbarian Training", description: "Otto Godblessed teaches unusual Barbarian methods of Fishing, Firemaking, and Smithing.", overviewStartText: "speaking to <col=800000>Otto Godblessed<col=000080> at the <col=800000>Barbarian Outpost<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Long", storyline: "Barbarian" }, requirementLines: ["Alfred Grimhand's Barcrawl for some sections"], requiredItems: ["Fishing, Firemaking, and Smithing supplies"], combatNotes: [], rewards: ["Barbarian Fishing, Firemaking, and Smithing methods", "Access to ancient-cavern training content"], outline: ["Ask Otto about Barbarian traditions.", "Complete the Fishing, Firemaking, and Smithing lessons.", "Return to Otto as each technique is mastered."], },
    { key: "bear your soul", displayName: "Bear Your Soul", description: "A strange spirit encounter asks you to confront a bear-themed mystery in the Wilderness.", overviewStartText: "speaking to the relevant spirit in the <col=800000>Wilderness<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Short", storyline: "Wilderness" }, requirementLines: ["Wilderness access"], requiredItems: ["Combat equipment", "Food", "Teleportation"], combatNotes: ["The Wilderness is dangerous; other players may attack."], rewards: ["Miniquest completion credit", "Related Wilderness lore unlocks"], outline: ["Locate the spirit's starting point.", "Follow its clues through the Wilderness.", "Complete the encounter and claim the lore reward."], },
    { key: "curse of the empty lord", displayName: "Curse of the Empty Lord", description: "The ghostly followers of Zaros offer clues about the Empty Lord and ancient desert history.", overviewStartText: "speaking to a <col=800000>Ghost Disciple<col=000080> after beginning the <col=800000>Desert Treasure<col=000080> storyline.", journalInfo: { difficulty: "Experienced", length: "Medium", storyline: "Mahjarrat" }, requirementLines: ["Desert Treasure I progress", "Ghostspeak amulet"], requiredItems: ["Ghostspeak amulet", "Desert supplies", "Teleportation"], combatNotes: [], rewards: ["Ancient ghostly robes", "Zarosian lore completion"], outline: ["Find each Ghost Disciple.", "Listen to their account of the Empty Lord.", "Complete the set of lore encounters."], },
    { key: "daddy's home", displayName: "Daddy's Home", description: "Marlo needs help restoring a run-down house and learning the foundations of Construction.", overviewStartText: "speaking to <col=800000>Marlo<col=000080> in <col=800000>Varrock<col=000080>.", journalInfo: { difficulty: "Novice", length: "Short", storyline: "Construction" }, requirementLines: [], requiredItems: ["Hammer", "Saw", "Basic construction supplies"], combatNotes: [], rewards: ["Construction experience", "Starter player-owned house supplies", "Construction tutorial completion"], outline: ["Meet Marlo and inspect the house.", "Gather the materials and repair each room.", "Finish the renovation and learn the Construction basics."], },
    { key: "enter the abyss", displayName: "Enter the Abyss", description: "Zamorak's Mage needs help investigating a rift that leads to the Abyss.", overviewStartText: "speaking to the <col=800000>Mage of Zamorak<col=000080> in the <col=800000>Wilderness<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Short", storyline: "Runecrafting" }, requirementLines: ["Rune Mysteries", "Level 21 Runecraft"], requiredItems: ["Combat equipment", "Food", "Teleportation"], combatNotes: ["Travel through the Wilderness and the dangerous Abyss."], rewards: ["Abyss access", "Ability to use Abyssal rifts to Runecrafting altars"], outline: ["Speak to the Mage of Zamorak.", "Survive the Wilderness investigation and enter the Abyss.", "Return after opening the route to the altars."], },
    { key: "family pest", displayName: "Family Pest", description: "A family problem in Varlamore needs help dealing with a troublesome infestation.", overviewStartText: "speaking to the quest contact in <col=800000>Varlamore<col=000080>.", journalInfo: { difficulty: "Novice", length: "Short", storyline: "Varlamore" }, requirementLines: ["Access to Varlamore"], requiredItems: ["No mandatory items"], combatNotes: ["Expect light exploration and minor danger."], rewards: ["Miniquest completion credit", "Varlamore lore progression"], outline: ["Investigate the family's problem.", "Track the source of the infestation.", "Resolve it and return to the family."], },
    { key: "the enchanted key", displayName: "The Enchanted Key", description: "A strange key starts a treasure hunt across Misthalin and the Fremennik lands.", overviewStartText: "using the <col=800000>enchanted key<col=000080> received from <col=800000>Jorral<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Medium", storyline: "Fremennik" }, requirementLines: ["Making History"], requiredItems: ["Enchanted key", "Spade", "Teleportation"], combatNotes: [], rewards: ["Treasure caskets", "Fremennik and Misthalin lore"], outline: ["Use the key to locate each hidden treasure point.", "Follow its temperature clues across Gielinor.", "Unearth the final treasure."], },
    { key: "the frozen door", displayName: "The Frozen Door", description: "A frozen door beneath God Wars Dungeon hides an ancient Zarosian mystery.", overviewStartText: "examining the <col=800000>Frozen Door<col=000080> beneath <col=800000>God Wars Dungeon<col=000080>.", journalInfo: { difficulty: "Master", length: "Long", storyline: "God Wars" }, requirementLines: ["Desert Treasure I", "God Wars Dungeon access"], requiredItems: ["High-level combat equipment", "Ecumenical key or dungeon access", "Food", "Prayer restoration"], combatNotes: ["Fight strong God Wars Dungeon enemies and solve the frozen-door challenges."], rewards: ["Ancient prison access", "Nex lore and encounter access"], outline: ["Find and investigate the Frozen Door.", "Collect the keys and solve the prison's requirements.", "Open the door and uncover the Zarosian chamber."], },
    { key: "the general's shadow", displayName: "The General's Shadow", description: "A spectral general's legacy leads to a short encounter with forgotten military history.", overviewStartText: "speaking to the relevant spirit in <col=800000>Gielinor<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Short", storyline: "Ghost" }, requirementLines: ["Related quest progress"], requiredItems: ["Ghostspeak amulet", "Combat supplies if needed"], combatNotes: [], rewards: ["Miniquest completion credit", "Related lore unlocks"], outline: ["Find the general's spirit.", "Follow the clues surrounding its unfinished business.", "Resolve the encounter."], },
    { key: "his faithful servants", displayName: "His Faithful Servants", description: "A forgotten master and loyal servants leave clues that must be pieced together.", overviewStartText: "speaking to the relevant quest contact in <col=800000>Gielinor<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Short", storyline: "Lore" }, requirementLines: ["Related quest progress"], requiredItems: ["Teleportation", "Quest-specific clues"], combatNotes: [], rewards: ["Miniquest completion credit", "Related lore unlocks"], outline: ["Locate the servants' clues.", "Piece together their master's story.", "Complete the final encounter."], },
    { key: "hopespear's will", displayName: "Hopespear's Will", description: "Hopespear's legacy asks you to follow the wishes he left behind for his people.", overviewStartText: "speaking to the relevant <col=800000>cave goblin<col=000080> contact.", journalInfo: { difficulty: "Intermediate", length: "Short", storyline: "Dorgeshuun" }, requirementLines: ["Dorgeshuun storyline progress"], requiredItems: ["Light source", "Teleportation"], combatNotes: [], rewards: ["Miniquest completion credit", "Dorgeshuun lore unlocks"], outline: ["Learn about Hopespear's will.", "Follow the instructions left for the cave goblins.", "Complete the final request."], },
    { key: "in search of knowledge", displayName: "In Search of Knowledge", description: "Scholars need help finding lost information hidden throughout the world.", overviewStartText: "speaking to the relevant <col=800000>scholar<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Medium", storyline: "Lore" }, requirementLines: ["Access to the relevant research locations"], requiredItems: ["Teleportation", "Research notes"], combatNotes: [], rewards: ["Miniquest completion credit", "Lore and research unlocks"], outline: ["Accept the search for lost knowledge.", "Visit the indicated locations and recover each clue.", "Return the completed research."], },
    { key: "into the tombs", displayName: "Into the Tombs", description: "An expedition prepares you to enter the ancient Tombs of Amascut.", overviewStartText: "speaking to the expedition contact at the <col=800000>Tombs of Amascut<col=000080> entrance.", journalInfo: { difficulty: "Experienced", length: "Medium", storyline: "Desert" }, requirementLines: ["Beneath Cursed Sands"], requiredItems: ["Combat equipment", "Food", "Prayer restoration"], combatNotes: ["Prepare for raid-level desert encounters."], rewards: ["Tombs of Amascut introduction", "Raid access and lore"], outline: ["Meet the expedition at the tomb entrance.", "Learn the raid's objectives and prepare for its rooms.", "Complete the introductory route."], },
    { key: "lair of tarn razorlor", displayName: "Lair of Tarn Razorlor", description: "Tarn Razorlor's abandoned lair conceals traps, undead servants, and ancient rewards.", overviewStartText: "entering <col=800000>Tarn Razorlor's Lair<col=000080> beneath the <col=800000>Haunted Mine<col=000080>.", journalInfo: { difficulty: "Experienced", length: "Medium", storyline: "Morytania" }, requirementLines: ["Haunted Mine"], requiredItems: ["Combat equipment", "Food", "Light source", "Teleportation"], combatNotes: ["Fight Tarn Razorlor and dangerous undead dungeon enemies."], rewards: ["Salve amulet enhancement materials", "Tarn's diary and dungeon rewards"], outline: ["Find the route into Tarn's lair.", "Navigate the traps and defeat its guardians.", "Defeat Tarn Razorlor and recover the rewards."], },
    { key: "mage arena i", displayName: "Mage Arena I", description: "Kolodion invites powerful mages to prove themselves in the Wilderness Mage Arena.", overviewStartText: "speaking to <col=800000>Kolodion<col=000080> in the <col=800000>Mage Arena<col=000080>.", journalInfo: { difficulty: "Experienced", length: "Medium", storyline: "Wilderness" }, requirementLines: ["Level 60 Magic"], requiredItems: ["Combat runes", "Food", "Teleportation"], combatNotes: ["Fight Kolodion's forms in level 55 Wilderness; other players may attack."], rewards: ["God capes", "God spells", "Mage Arena completion"], outline: ["Find Kolodion in the Wilderness arena.", "Defeat his four forms and choose a god.", "Claim the matching cape and spell."], },
    { key: "mage arena ii", displayName: "Mage Arena II", description: "Kolodion challenges proven mages to hunt powerful godly creatures across the Wilderness.", overviewStartText: "speaking to <col=800000>Kolodion<col=000080> after completing <col=800000>Mage Arena I<col=000080>.", journalInfo: { difficulty: "Master", length: "Long", storyline: "Wilderness" }, requirementLines: ["Mage Arena I", "Level 75 Magic"], requiredItems: ["God cape", "Strong combat equipment", "Food", "Teleportation"], combatNotes: ["Defeat the three godly creatures in the Wilderness; other players may attack."], rewards: ["Imbued god capes", "Mage Arena II completion"], outline: ["Accept Kolodion's second challenge.", "Track and defeat each godly creature in the Wilderness.", "Use the gathered components to imbue a god cape."], },
    { key: "skippy and the mogres", displayName: "Skippy and the Mogres", description: "Skippy needs help dealing with mogres emerging from the mud near Mudskipper Point.", overviewStartText: "speaking to <col=800000>Skippy<col=000080> at <col=800000>Mudskipper Point<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Short", storyline: "Mogre" }, requirementLines: ["Level 32 Slayer"], requiredItems: ["Explosive compound", "Combat equipment", "Food"], combatNotes: ["Fight mogres (level 60) after luring them from the mud."], rewards: ["Mogre access", "Ability to obtain mudskipper and mogre drops"], outline: ["Speak to Skippy and learn why the mogres are appearing.", "Prepare the explosive compound and use it at the mud.", "Defeat a mogre and return to Skippy."], },
    { key: "vale totems", displayName: "Vale Totems", description: "Varlamore totems hold a regional mystery that can be solved by following their clues.", overviewStartText: "speaking to the relevant contact in <col=800000>Varlamore<col=000080>.", journalInfo: { difficulty: "Intermediate", length: "Medium", storyline: "Varlamore" }, requirementLines: ["Access to Varlamore"], requiredItems: ["Teleportation", "Quest-specific clues"], combatNotes: ["Expect exploration and regional hazards."], rewards: ["Miniquest completion credit", "Varlamore lore progression"], outline: ["Locate the first totem clue.", "Follow the trail between the Vale's totems.", "Resolve the mystery at the final site."], },
];

const byKey = new Map<string, MiniquestContent>();
const byName = new Map<string, MiniquestContent>();
for (const content of MINIQUEST_CONTENT) {
    if (byKey.has(content.key) || byName.has(content.displayName.toLowerCase())) {
        throw new Error(`Duplicate miniquest content: ${content.displayName}`);
    }
    byKey.set(content.key, content);
    byName.set(content.displayName.toLowerCase(), content);
}

export function getMiniquestContent(reference: string): MiniquestContent | undefined {
    const key = String(reference ?? "").trim().toLowerCase();
    return byKey.get(key) ?? byName.get(key);
}

export const buildMiniquestJournal = buildFreeToPlayQuestJournal;
export const buildMiniquestOverview = buildFreeToPlayQuestOverview;
