// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Attack/Level_up_table page. Blank requires fields are intended for hand editing.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const attackSkillGuide: SkillGuideData = {
    skillId: SkillId.Attack,
    tabs: [
        {
            label: "Overview",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level in Attack contributes to a player's combat level",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level in Attack slightly increases the accuracy of a player's melee attacks",
                    requires: "",
                },
            ]
        },
        {
            label: "Weapons",
            entries: [
                {
                    itemId: 1205,
                    level: 1,
                    name: "Bronze weapons",
                    requires: "",
                },
                {
                    itemId: 1203,
                    level: 1,
                    name: "Iron weapons",
                    requires: "",
                },
                {
                    itemId: 1207,
                    level: 5,
                    name: "Steel weapons",
                    requires: "",
                },
                {
                    itemId: 1217,
                    level: 10,
                    name: "Black weapons",
                    requires: "",
                },
                {
                    itemId: 6591,
                    level: 10,
                    name: "White weapons",
                    requires: "",
                },
                {
                    itemId: 1209,
                    level: 20,
                    name: "Mithril weapons",
                    requires: "",
                },
                {
                    itemId: 1211,
                    level: 30,
                    name: "Adamant weapons",
                    requires: "",
                },
                {
                    itemId: 1391,
                    level: 30,
                    name: "Battlestaves",
                    requires: "Level 30 Magic",
                },
                {
                    itemId: 22370,
                    level: 30,
                    name: "Bryophyta's staff",
                    requires: "Level 30 Magic",
                },
                {
                    itemId: 10149,
                    level: 30,
                    name: "Swamp lizard",
                    requires: "Level 30 Ranged, level 30 Magic",
                },
                {
                    itemId: 1213,
                    level: 40,
                    name: "Rune weapons",
                    requires: "",
                },
                {
                    itemId: 25641,
                    level: 40,
                    name: "Barronite mace",
                    requires: "Below Ice Mountain",
                },
                {
                    itemId: 11037,
                    level: 40,
                    name: "Brine sabre",
                    requires: "",
                },
                {
                    itemId: 22398,
                    level: 40,
                    name: "Ivandis Flail",
                    requires: "A Taste of Hope",
                },
                {
                    itemId: 1405,
                    level: 40,
                    name: "Mystic Staves",
                    requires: "Level 40 Magic",
                },
                {
                    itemId: 8841,
                    level: 42,
                    name: "Void Knight mace",
                    requires: "Level 22 Prayer, level 42 Ranged, level 42 Defence, level 42 Strength, level 42 Hitpoints, level 42 Magic",
                },
                {
                    itemId: 24699,
                    level: 50,
                    name: "Blisterwood",
                    requires: "Sins of the Father",
                },
                {
                    itemId: 10581,
                    level: 50,
                    name: "Keris dagger",
                    requires: "Contact!",
                },
                {
                    itemId: 28792,
                    level: 50,
                    name: "Bone mace",
                    requires: "",
                },
            ]
        },
        {
            label: "Armour",
            entries: [
                {
                    itemId: 8839,
                    level: 42,
                    name: "Void Knight equipment",
                    requires: "Level 22 Prayer, level 42 Ranged, level 42 Defence, level 42 Strength, level 42 Hitpoints, level 42 Magic",
                },
                {
                    itemId: 22981,
                    level: 80,
                    name: "Ferocious Gloves",
                    requires: "Level 80 Defence",
                },
                {
                    itemId: 9747,
                    level: 99,
                    name: "Skillcape",
                    requires: "See Ajjat at the Warriors' Guild",
                },
            ]
        }
    ]
};
