// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Cooking/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const cookingSkillGuide: SkillGuideData = {
    skillId: SkillId.Cooking,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level reduces the chance of burning food when cooking. For burn rates, see the Burn Level a",
                    description: "rticle."
                },
                {
                    itemId: 2309,
                    level: 1,
                    name: "Bake bread"
                },
                {
                    itemId: 319,
                    level: 1,
                    name: "Cook anchovies"
                },
                {
                    itemId: 2140,
                    level: 1,
                    name: "Cook chickens"
                },
                {
                    itemId: 2142,
                    level: 1,
                    name: "Cook meat"
                },
                {
                    itemId: 325,
                    level: 1,
                    name: "Cook sardines"
                },
                {
                    itemId: 315,
                    level: 1,
                    name: "Cook shrimps"
                },
                {
                    itemId: 347,
                    level: 5,
                    name: "Cook herring"
                },
                {
                    itemId: 2325,
                    level: 10,
                    name: "Bake redberry pies"
                },
                {
                    itemId: -1,
                    level: 13,
                    name: "Cook Cooked t-bone steak"
                },
                {
                    itemId: 333,
                    level: 15,
                    name: "Cook trout"
                },
                {
                    itemId: 2327,
                    level: 20,
                    name: "Bake meat pies"
                },
                {
                    itemId: 351,
                    level: 20,
                    name: "Cook pike"
                },
                {
                    itemId: 329,
                    level: 25,
                    name: "Cook salmon"
                },
                {
                    itemId: 2003,
                    level: 25,
                    name: "Cook stews"
                },
                {
                    itemId: 2323,
                    level: 30,
                    name: "Bake apple pies"
                },
                {
                    itemId: 361,
                    level: 30,
                    name: "Cook tuna"
                },
                {
                    itemId: -1,
                    level: 32,
                    name: "Access the Cooks' Guild"
                },
                {
                    itemId: 2289,
                    level: 35,
                    name: "Bake plain pizza"
                },
                {
                    itemId: 1993,
                    level: 35,
                    name: "Brew jug of wine"
                },
                {
                    itemId: 1891,
                    level: 40,
                    name: "Bake cakes"
                },
                {
                    itemId: 379,
                    level: 40,
                    name: "Cook lobsters"
                },
                {
                    itemId: 2293,
                    level: 45,
                    name: "Bake meat pizzas"
                },
                {
                    itemId: 373,
                    level: 45,
                    name: "Cook swordfish"
                },
                {
                    itemId: 1897,
                    level: 50,
                    name: "Bake chocolate cakes"
                },
                {
                    itemId: 2297,
                    level: 55,
                    name: "Bake anchovy pizzas"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        },
        {
            label: "Members 1",
            entries: [
                {
                    itemId: 20871,
                    level: 1,
                    name: "Cook guanic bats"
                },
                {
                    itemId: 3146,
                    level: 1,
                    name: "Cook poison karambwans"
                },
                {
                    itemId: 20856,
                    level: 1,
                    name: "Cook psyk fish"
                },
                {
                    itemId: 3228,
                    level: 1,
                    name: "Cook rabbits"
                },
                {
                    itemId: 9436,
                    level: 1,
                    name: "Cook sinew"
                },
                {
                    itemId: 1883,
                    level: 1,
                    name: "Cook ugthanki kebabs"
                },
                {
                    itemId: 25565,
                    level: 1,
                    name: "Cook harpoonfish"
                },
                {
                    itemId: -1,
                    level: 5,
                    name: "Build a (with Construction 7)"
                },
                {
                    itemId: 2084,
                    level: 6,
                    name: "Mix fruit blasts"
                },
                {
                    itemId: 6701,
                    level: 7,
                    name: "Bake baked potatoes"
                },
                {
                    itemId: 2048,
                    level: 8,
                    name: "Mix pineapple punches"
                },
                {
                    itemId: 7072,
                    level: 9,
                    name: "Cook spicy sauces (topping ingredient)"
                },
                {
                    itemId: 2217,
                    level: 10,
                    name: "Bake toad crunchies"
                },
                {
                    itemId: 355,
                    level: 10,
                    name: "Cook mackerel"
                },
                {
                    itemId: 7062,
                    level: 11,
                    name: "Cook chilli con carne (topping ingredient)"
                },
                {
                    itemId: 9980,
                    level: 11,
                    name: "Cook roasted bird meat"
                },
                {
                    itemId: 2213,
                    level: 12,
                    name: "Bake spicy crunchies"
                },
                {
                    itemId: 3363,
                    level: 12,
                    name: "Cook thin snail"
                },
                {
                    itemId: 7078,
                    level: 13,
                    name: "Cook scrambled eggs (topping ingredient)"
                },
                {
                    itemId: 2205,
                    level: 14,
                    name: "Bake worm crunchies"
                },
                {
                    itemId: 5763,
                    level: 14,
                    name: "Brew cider"
                },
                {
                    itemId: -1,
                    level: 14,
                    name: "Build a (with Construction 12)"
                },
                {
                    itemId: 20873,
                    level: 15,
                    name: "Cook prael bats"
                },
                {
                    itemId: 20858,
                    level: 15,
                    name: "Cook suphi fish"
                },
                {
                    itemId: 2209,
                    level: 16,
                    name: "Bake chocchip crunchies"
                },
                {
                    itemId: 7223,
                    level: 16,
                    name: "Cook roasted rabbit"
                },
                {
                    itemId: 6293,
                    level: 16,
                    name: "Cook spiders on stick"
                },
                {
                    itemId: 3365,
                    level: 17,
                    name: "Cook lean snails"
                },
                {
                    itemId: 339,
                    level: 18,
                    name: "Cook cod"
                },
                {
                    itemId: 2054,
                    level: 18,
                    name: "Mix wizard blizzards"
                },
                {
                    itemId: 1913,
                    level: 19,
                    name: "Brew dwarven stouts"
                },
                {
                    itemId: 2080,
                    level: 20,
                    name: "Mix short green guy (SGG)"
                },
                {
                    itemId: 4239,
                    level: 20,
                    name: "Brew nettle tea"
                },
                {
                    itemId: 2130,
                    level: 21,
                    name: "Churn pots of cream"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Cook giant crab meat"
                },
                {
                    itemId: 9988,
                    level: 21,
                    name: "Cook roasted beast meat"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Cook red crab meat"
                },
                {
                    itemId: 3367,
                    level: 22,
                    name: "Cook fat snails"
                },
                {
                    itemId: 7064,
                    level: 23,
                    name: "Cook egg and tomatoes (topping ingredient)"
                },
                {
                    itemId: -1,
                    level: 23,
                    name: "Cook wild kebbits"
                },
                {
                    itemId: 1905,
                    level: 24,
                    name: "Brew asgarnian ales"
                },
                {
                    itemId: -1,
                    level: 24,
                    name: "Build an (with Construction 18)"
                },
                {
                    itemId: 2277,
                    level: 25,
                    name: "Bake fruit batta"
                },
                {
                    itemId: 2255,
                    level: 26,
                    name: "Cook toad batta"
                },
                {
                    itemId: 2253,
                    level: 27,
                    name: "Bake worm batta"
                },
                {
                    itemId: 2281,
                    level: 28,
                    name: "Bake vegetable batta"
                },
                {
                    itemId: 5988,
                    level: 28,
                    name: "Cook sweetcorn"
                },
                {
                    itemId: -1,
                    level: 28,
                    name: "Cook slimy eels"
                },
                {
                    itemId: 2259,
                    level: 29,
                    name: "Bake cheese and tomato batta"
                },
                {
                    itemId: 7170,
                    level: 29,
                    name: "Bake mud pies"
                },
                {
                    itemId: 1909,
                    level: 29,
                    name: "Brew greenman's ale"
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "Build a (with Construction 26)"
                },
                {
                    itemId: 2191,
                    level: 30,
                    name: "Bake worm holes"
                },
                {
                    itemId: 20875,
                    level: 30,
                    name: "Cook giral bats"
                },
                {
                    itemId: 20860,
                    level: 30,
                    name: "Cook leckish fish"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Cook larupias (with 15 Hunters' Rumours completed)"
                },
                {
                    itemId: 7530,
                    level: 31,
                    name: "Cook fishcakes"
                },
                {
                    itemId: 2092,
                    level: 32,
                    name: "Mix drunk dragons"
                },
                {
                    itemId: -1,
                    level: 32,
                    name: "Cook barb-tailed kebbits (with 15 Hunters' Rumours completed)"
                },
                {
                    itemId: 2074,
                    level: 33,
                    name: "Mix choc saturdays"
                },
                {
                    itemId: 7178,
                    level: 34,
                    name: "Bake garden pie"
                },
                {
                    itemId: 1907,
                    level: 34,
                    name: "Brew wizard's mind bomb"
                },
                {
                    itemId: 2195,
                    level: 35,
                    name: "Bake veg ball"
                },
                {
                    itemId: 10136,
                    level: 35,
                    name: "Cook rainbow fish"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Make forester's rations (with Woodcutting 35)"
                },
                {
                    itemId: -1,
                    level: 36,
                    name: "Brew damiana tea"
                },
                {
                    itemId: 2064,
                    level: 37,
                    name: "Mix blurberry specials"
                },
                {
                    itemId: 6697,
                    level: 38,
                    name: "Churn pats of butter"
                },
                {
                    itemId: 5003,
                    level: 38,
                    name: "Cook cave eels"
                },
                {
                    itemId: 6703,
                    level: 39,
                    name: "Bake potatoes with butter"
                },
                {
                    itemId: 1911,
                    level: 39,
                    name: "Brew dragon bitters"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Build a (with Construction 36)"
                },
                {
                    itemId: 2187,
                    level: 40,
                    name: "Bake tangled toad's legs"
                },
                {
                    itemId: 7054,
                    level: 41,
                    name: "Bake chilli potatoes"
                },
                {
                    itemId: 7568,
                    level: 41,
                    name: "Cook jubblies"
                },
                {
                    itemId: -1,
                    level: 41,
                    name: "Cook graahks (with 25 Hunters' Rumours completed)"
                },
                {
                    itemId: 7084,
                    level: 42,
                    name: "Cook fried onions (topping ingredient)"
                },
                {
                    itemId: 2185,
                    level: 42,
                    name: "Bake chocolate bombs"
                },
                {
                    itemId: 365,
                    level: 43,
                    name: "Cook bass"
                },
                {
                    itemId: 2955,
                    level: 44,
                    name: "Brew moonlight mead"
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Build a (with Construction 48)"
                },
                {
                    itemId: 20862,
                    level: 45,
                    name: "Cook brawk fish"
                },
                {
                    itemId: 20877,
                    level: 45,
                    name: "Cook phluxia bats"
                },
                {
                    itemId: 7082,
                    level: 46,
                    name: "Cook fried mushrooms (topping ingredient)"
                },
                {
                    itemId: 6705,
                    level: 47,
                    name: "Bake potatoes with cheese"
                },
                {
                    itemId: 7188,
                    level: 47,
                    name: "Bake fish pies"
                },
                {
                    itemId: 1985,
                    level: 48,
                    name: "Churn cheese"
                },
                {
                    itemId: -1,
                    level: 48,
                    name: "Cook blue crab meat"
                },
                {
                    itemId: 5751,
                    level: 49,
                    name: "Brew axeman's folly"
                },
                {
                    itemId: 7056,
                    level: 51,
                    name: "Bake egg potatoes"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: -1,
                    level: 51,
                    name: "Cook kyatts (with 25 Hunters' Rumours completed)"
                },
                {
                    itemId: 19662,
                    level: 52,
                    name: "Bake botanical pie"
                },
                {
                    itemId: 5755,
                    level: 54,
                    name: "Brew chef's delight"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Cook swordtip squids"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Cook mushroom & onions (topping ingredient)"
                },
                {
                    itemId: 1865,
                    level: 58,
                    name: "Bake pitta bread"
                },
                {
                    itemId: 5759,
                    level: 59,
                    name: "Brew slayer's respite"
                },
                {
                    itemId: -1,
                    level: 59,
                    name: "Cook pyre foxes (with 25 Hunters' Rumours completed)"
                },
                {
                    itemId: 21690,
                    level: 60,
                    name: "Bake mushroom pies"
                },
                {
                    itemId: 2011,
                    level: 60,
                    name: "Cook curry"
                },
                {
                    itemId: 20879,
                    level: 60,
                    name: "Cook kryket bats"
                },
                {
                    itemId: 20864,
                    level: 60,
                    name: "Cook mycil fish"
                },
                {
                    itemId: 7058,
                    level: 64,
                    name: "Bake mushroom potatoes"
                },
                {
                    itemId: 2301,
                    level: 65,
                    name: "Bake pineapple pizzas"
                },
                {
                    itemId: 245,
                    level: 65,
                    name: "Brew wine of Zamoraks"
                },
                {
                    itemId: 7068,
                    level: 67,
                    name: "Cook tuna and corn (topping ingredient)"
                },
                {
                    itemId: 7060,
                    level: 68,
                    name: "Bake tuna potatoes"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Cook sunlight antelopes (with 50 Hunters' Rumours completed)"
                },
                {
                    itemId: -1,
                    level: 69,
                    name: "Cook giant krill"
                },
                {
                    itemId: 7198,
                    level: 70,
                    name: "Bake admiral pies"
                },
                {
                    itemId: -1,
                    level: 71,
                    name: "Cook jumbo squids"
                },
                {
                    itemId: 12934,
                    level: 72,
                    name: "Dissect 3-5 Zulrah's scales per sacred eel"
                },
                {
                    itemId: 22795,
                    level: 73,
                    name: "Bake dragonfruit pies"
                },
                {
                    itemId: -1,
                    level: 73,
                    name: "Cook haddock"
                },
                {
                    itemId: 20881,
                    level: 75,
                    name: "Cook murng bats"
                },
                {
                    itemId: 20866,
                    level: 75,
                    name: "Cook roqed fish"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Cook rainbow crab meat"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Cook yellowfin"
                },
                {
                    itemId: 385,
                    level: 80,
                    name: "Cook sharks"
                },
                {
                    itemId: 12934,
                    level: 80,
                    name: "Dissect 4-6 Zulrah's scales per sacred eel"
                },
                {
                    itemId: 397,
                    level: 82,
                    name: "Cook sea turtles"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Cook dashing kebbits (with 50 Hunters' Rumours completed)"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Cook halibut"
                },
                {
                    itemId: 13441,
                    level: 84,
                    name: "Cook anglerfish"
                },
                {
                    itemId: 7208,
                    level: 85,
                    name: "Bake wild pies"
                },
                {
                    itemId: 21031,
                    level: 85,
                    name: "Make an Infernal harpoon"
                },
                {
                    itemId: -1,
                    level: 87,
                    name: "Cook bluefin"
                },
                {
                    itemId: 12934,
                    level: 88,
                    name: "Dissect 5-7 Zulrah's scales per sacred eel"
                },
                {
                    itemId: 11936,
                    level: 90,
                    name: "Cook dark crabs"
                },
                {
                    itemId: 20868,
                    level: 90,
                    name: "Cook kyren fish"
                },
                {
                    itemId: 20883,
                    level: 90,
                    name: "Cook psykk bats"
                },
                {
                    itemId: 391,
                    level: 91,
                    name: "Cook manta rays"
                },
                {
                    itemId: -1,
                    level: 91,
                    name: "Cook marlin"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Cook moonlight antelopes (with 50 Hunters' Rumours completed)"
                },
                {
                    itemId: 7218,
                    level: 95,
                    name: "Bake summer pies"
                },
                {
                    itemId: 12934,
                    level: 96,
                    name: "Dissect 6-8 Zulrah's scales per sacred eel"
                },
                {
                    itemId: 9801,
                    level: 99,
                    name: "Buy the Cooking cape and hood from the head chef in the Cooks' Guild, and wear them"
                }
            ]
        }
    ]
};
