// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Crafting/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const craftingSkillGuide: SkillGuideData = {
    skillId: SkillId.Crafting,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: 1759,
                    level: 1,
                    name: "Craft balls of wool"
                },
                {
                    itemId: 1059,
                    level: 1,
                    name: "Craft leather gloves"
                },
                {
                    itemId: 1931,
                    level: 1,
                    name: "Craft pots"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Dye capes"
                },
                {
                    itemId: 579,
                    level: 1,
                    name: "Dye blue wizard hats"
                },
                {
                    itemId: 577,
                    level: 1,
                    name: "Dye blue wizard robes"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "String amulets"
                },
                {
                    itemId: 1635,
                    level: 5,
                    name: "Craft gold rings"
                },
                {
                    itemId: 1654,
                    level: 6,
                    name: "Craft gold necklaces"
                },
                {
                    itemId: 1061,
                    level: 7,
                    name: "Craft leather boots"
                },
                {
                    itemId: 2313,
                    level: 7,
                    name: "Craft pie dishes"
                },
                {
                    itemId: 1923,
                    level: 8,
                    name: "Craft bowls"
                },
                {
                    itemId: 1673,
                    level: 8,
                    name: "Craft gold amulet (u)"
                },
                {
                    itemId: 1167,
                    level: 9,
                    name: "Craft leather cowls"
                },
                {
                    itemId: 1063,
                    level: 11,
                    name: "Craft leather vambraces"
                },
                {
                    itemId: 1129,
                    level: 14,
                    name: "Craft leather bodies"
                },
                {
                    itemId: 1714,
                    level: 16,
                    name: "Craft unstrung symbols"
                },
                {
                    itemId: 1095,
                    level: 18,
                    name: "Craft leather chaps"
                },
                {
                    itemId: 1637,
                    level: 20,
                    name: "Craft sapphire rings"
                },
                {
                    itemId: 1607,
                    level: 20,
                    name: "Cut sapphires"
                },
                {
                    itemId: 1656,
                    level: 22,
                    name: "Craft sapphire necklaces"
                },
                {
                    itemId: 5525,
                    level: 23,
                    name: "Craft tiaras"
                },
                {
                    itemId: 1675,
                    level: 24,
                    name: "Craft sapphire amulet (u)"
                },
                {
                    itemId: 1639,
                    level: 27,
                    name: "Craft emerald rings"
                },
                {
                    itemId: 1605,
                    level: 27,
                    name: "Cut emeralds"
                },
                {
                    itemId: 1131,
                    level: 28,
                    name: "Craft hardleather bodies"
                },
                {
                    itemId: 1658,
                    level: 29,
                    name: "Craft emerald necklaces"
                },
                {
                    itemId: 1677,
                    level: 31,
                    name: "Craft emerald amulet (u)"
                },
                {
                    itemId: 1641,
                    level: 34,
                    name: "Craft ruby rings"
                },
                {
                    itemId: 1603,
                    level: 34,
                    name: "Cut rubies"
                },
                {
                    itemId: 1757,
                    level: 40,
                    name: "Access to the Crafting Guild while wearing a brown apron or crafting cape"
                },
                {
                    itemId: 1660,
                    level: 40,
                    name: "Craft ruby necklaces"
                },
                {
                    itemId: 1643,
                    level: 43,
                    name: "Craft diamond rings"
                },
                {
                    itemId: 1601,
                    level: 43,
                    name: "Cut diamonds"
                },
                {
                    itemId: 1679,
                    level: 50,
                    name: "Craft ruby amulet (u)"
                },
                {
                    itemId: 1662,
                    level: 56,
                    name: "Craft diamond necklaces"
                },
                {
                    itemId: 1681,
                    level: 70,
                    name: "Craft diamond amulet (u)"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        },
        {
            label: "Members 1",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Increases the chance of successfully cutting opal, jade, and red topaz"
                },
                {
                    itemId: 1775,
                    level: 1,
                    name: "Craft molten glass"
                },
                {
                    itemId: 1919,
                    level: 1,
                    name: "Craft beer glasses"
                },
                {
                    itemId: 21081,
                    level: 1,
                    name: "Craft opal rings"
                },
                {
                    itemId: 1609,
                    level: 1,
                    name: "Cut opals"
                },
                {
                    itemId: 1019,
                    level: 1,
                    name: "Dye black capes"
                },
                {
                    itemId: 6752,
                    level: 1,
                    name: "Dye black desert robes"
                },
                {
                    itemId: 6750,
                    level: 1,
                    name: "Dye black desert shirts"
                },
                {
                    itemId: 581,
                    level: 1,
                    name: "Dye black robes"
                },
                {
                    itemId: 1017,
                    level: 1,
                    name: "Dye black wizard hats"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "String amulets"
                },
                {
                    itemId: 10496,
                    level: 3,
                    name: "Craft polished buttons"
                },
                {
                    itemId: 1980,
                    level: 3,
                    name: "Craft empty cups"
                },
                {
                    itemId: 4529,
                    level: 4,
                    name: "Craft Candle lantern (white)s"
                },
                {
                    itemId: 21512,
                    level: 5,
                    name: "Craft bird houses"
                },
                {
                    itemId: 11068,
                    level: 7,
                    name: "Craft gold bracelets"
                },
                {
                    itemId: 1777,
                    level: 10,
                    name: "Craft bow strings"
                },
                {
                    itemId: 9438,
                    level: 10,
                    name: "Craft crossbow strings"
                },
                {
                    itemId: 3224,
                    level: 10,
                    name: "Craft strips of cloth"
                },
                {
                    itemId: 9436,
                    level: 10,
                    name: "Extract sinew from damaged monkey tails"
                },
                {
                    itemId: 2862,
                    level: 11,
                    name: "Craft achey pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 1511,
                    level: 11,
                    name: "Craft regular pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 4522,
                    level: 12,
                    name: "Craft oil lamps"
                },
                {
                    itemId: 3420,
                    level: 12,
                    name: "Craft limestone brick"
                },
                {
                    itemId: 1779,
                    level: 12,
                    name: "Spin flax into linen yarn"
                },
                {
                    itemId: -1,
                    level: 12,
                    name: "Craft bolts of linen"
                },
                {
                    itemId: -1,
                    level: 12,
                    name: "Craft gem pouches"
                },
                {
                    itemId: 1611,
                    level: 13,
                    name: "Cut jade"
                },
                {
                    itemId: 21084,
                    level: 13,
                    name: "Craft jade rings"
                },
                {
                    itemId: 13385,
                    level: 14,
                    name: "Craft xerician hats"
                },
                {
                    itemId: 3327,
                    level: 15,
                    name: "Craft snelms"
                },
                {
                    itemId: 21515,
                    level: 15,
                    name: "Craft oak bird houses"
                },
                {
                    itemId: 21090,
                    level: 16,
                    name: "Craft opal necklaces"
                },
                {
                    itemId: 21087,
                    level: 16,
                    name: "Craft topaz rings"
                },
                {
                    itemId: 1613,
                    level: 16,
                    name: "Cut red topazes"
                },
                {
                    itemId: 1720,
                    level: 17,
                    name: "Craft unstrung emblems"
                },
                {
                    itemId: 13389,
                    level: 17,
                    name: "Craft xerician robes"
                },
                {
                    itemId: 2961,
                    level: 18,
                    name: "Craft silver sickles"
                },
                {
                    itemId: 5350,
                    level: 19,
                    name: "Craft empty plant pots"
                },
                {
                    itemId: 6038,
                    level: 19,
                    name: "Craft magic strings"
                },
                {
                    itemId: 5418,
                    level: 21,
                    name: "Craft empty sacks"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Craft silver bolts (unf)"
                },
                {
                    itemId: 21117,
                    level: 22,
                    name: "Craft opal bracelets"
                },
                {
                    itemId: 13387,
                    level: 22,
                    name: "Craft xerician tops"
                },
                {
                    itemId: 11071,
                    level: 23,
                    name: "Craft sapphire bracelets"
                },
                {
                    itemId: 21093,
                    level: 25,
                    name: "Craft jade necklaces"
                },
                {
                    itemId: 1521,
                    level: 25,
                    name: "Craft oak pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 21518,
                    level: 25,
                    name: "Craft willow bird houses"
                },
                {
                    itemId: 4537,
                    level: 26,
                    name: "Craft oil lanterns"
                },
                {
                    itemId: 21652,
                    level: 26,
                    name: "Craft drift nets"
                },
                {
                    itemId: 21099,
                    level: 27,
                    name: "Craft opal amulet (u)"
                },
                {
                    itemId: 21120,
                    level: 29,
                    name: "Craft jade bracelets"
                },
                {
                    itemId: 11076,
                    level: 30,
                    name: "Craft emerald bracelets"
                },
                {
                    itemId: 954,
                    level: 30,
                    name: "Craft ropes"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Repair File:Hammer.png Piscarilius fishing cranes"
                },
                {
                    itemId: 10077,
                    level: 32,
                    name: "Craft spiky vambraces"
                },
                {
                    itemId: 21096,
                    level: 32,
                    name: "Craft topaz necklaces"
                },
                {
                    itemId: 229,
                    level: 33,
                    name: "Craft vials"
                },
                {
                    itemId: 21102,
                    level: 34,
                    name: "Craft jade amulet (u)"
                },
                {
                    itemId: 6215,
                    level: 35,
                    name: "Craft Broodoo shield (combat)s"
                },
                {
                    itemId: 21521,
                    level: 35,
                    name: "Craft teak bird houses"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Craft small meat pouches"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Craft small fur pouches"
                },
                {
                    itemId: 5376,
                    level: 36,
                    name: "Craft baskets"
                },
                {
                    itemId: 10132,
                    level: 37,
                    name: "Craft rabbit-foot necklaces"
                },
                {
                    itemId: 1169,
                    level: 38,
                    name: "Craft coifs"
                },
                {
                    itemId: 13445,
                    level: 38,
                    name: "Mine dense essence blocks (with Mining 38)"
                },
                {
                    itemId: 7938,
                    level: 38,
                    name: "Create dark essence fragments"
                },
                {
                    itemId: 21123,
                    level: 38,
                    name: "Craft topaz bracelets"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Craft heraldic helmets (with crest assigned by Sir Renitee)"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Spin hemp into hemp yarn"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Craft bolts of canvas"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Craft gem satchels"
                },
                {
                    itemId: 1519,
                    level: 40,
                    name: "Craft willow pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 22269,
                    level: 41,
                    name: "Craft hard leather shields"
                },
                {
                    itemId: 1133,
                    level: 41,
                    name: "Craft studded bodies"
                },
                {
                    itemId: 6667,
                    level: 42,
                    name: "Craft empty fishbowls"
                },
                {
                    itemId: 11085,
                    level: 42,
                    name: "Craft ruby bracelets"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Craft gold tiaras"
                },
                {
                    itemId: -1,
                    level: 43,
                    name: "Craft heraldic kiteshields (with crest assigned by Sir Renitee)"
                },
                {
                    itemId: 1097,
                    level: 44,
                    name: "Craft studded chaps"
                },
                {
                    itemId: 22192,
                    level: 45,
                    name: "Craft maple bird houses"
                },
                {
                    itemId: 6328,
                    level: 45,
                    name: "Craft snakeskin boots"
                },
                {
                    itemId: 6333,
                    level: 45,
                    name: "Craft teak pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 21105,
                    level: 45,
                    name: "Craft topaz amulet (u)"
                },
                {
                    itemId: 567,
                    level: 46,
                    name: "Craft unpowered orbs"
                },
                {
                    itemId: 6330,
                    level: 47,
                    name: "Craft snakeskin vambraces"
                },
                {
                    itemId: 6326,
                    level: 48,
                    name: "Craft snakeskin bandanas"
                },
                {
                    itemId: 4542,
                    level: 49,
                    name: "Craft lantern lenses"
                },
                {
                    itemId: 22195,
                    level: 50,
                    name: "Craft mahogany bird houses"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: -1,
                    level: 50,
                    name: "Craft clothes pouches (with Woodcutting 50)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Craft medium fur pouches"
                },
                {
                    itemId: 6324,
                    level: 51,
                    name: "Craft snakeskin chaps"
                },
                {
                    itemId: 10810,
                    level: 52,
                    name: "Craft arctic pine pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 12929,
                    level: 52,
                    name: "Craft serpentine helms"
                },
                {
                    itemId: 6322,
                    level: 53,
                    name: "Craft snakeskin bodies"
                },
                {
                    itemId: 1395,
                    level: 54,
                    name: "Craft water battlestaves"
                },
                {
                    itemId: 1645,
                    level: 55,
                    name: "Craft dragonstone rings"
                },
                {
                    itemId: 11864,
                    level: 55,
                    name: "Craft slayer helmets (after purchasing \"Malevolent masquerade\" for 400 Slayer reward points)"
                },
                {
                    itemId: 1517,
                    level: 55,
                    name: "Craft maple pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 1615,
                    level: 55,
                    name: "Cut dragonstones"
                },
                {
                    itemId: 22272,
                    level: 56,
                    name: "Craft snakeskin shields"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Craft the colossal pouch"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Craft green d'hide vambraces"
                },
                {
                    itemId: 11092,
                    level: 58,
                    name: "Craft diamond bracelets"
                },
                {
                    itemId: 1399,
                    level: 58,
                    name: "Craft earth battlestaves"
                },
                {
                    itemId: 12904,
                    level: 59,
                    name: "Craft toxic staves of the dead"
                },
                {
                    itemId: 12899,
                    level: 59,
                    name: "Craft tridents of the swamp"
                },
                {
                    itemId: 1099,
                    level: 60,
                    name: "Craft green d'hide chaps"
                },
                {
                    itemId: 6332,
                    level: 60,
                    name: "Craft mahogany pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 22198,
                    level: 60,
                    name: "Craft yew bird houses"
                },
                {
                    itemId: 3391,
                    level: 60,
                    name: "Craft splitbark gauntlets"
                },
                {
                    itemId: 3393,
                    level: 60,
                    name: "Craft splitbark boots"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Craft Sunstone golem (with Fallen From Grace completed)"
                },
                {
                    itemId: 3385,
                    level: 61,
                    name: "Craft splitbark helms"
                },
                {
                    itemId: 1393,
                    level: 62,
                    name: "Craft fire battlestaves"
                },
                {
                    itemId: 22275,
                    level: 62,
                    name: "Craft green d'hide shields"
                },
                {
                    itemId: 3389,
                    level: 62,
                    name: "Craft splitbark legs"
                },
                {
                    itemId: 3387,
                    level: 62,
                    name: "Craft splitbark bodies"
                },
                {
                    itemId: 22368,
                    level: 62,
                    name: "Craft bryophyta's staff"
                },
                {
                    itemId: 1135,
                    level: 63,
                    name: "Craft green d'hide bodies"
                },
                {
                    itemId: 10075,
                    level: 64,
                    name: "Repair gloves of silence"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Craft large meat pouches"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Craft large fur pouches"
                },
                {
                    itemId: 1397,
                    level: 66,
                    name: "Craft air battlestaves"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Craft blue d'hide vambraces"
                },
                {
                    itemId: 6564,
                    level: 67,
                    name: "Craft onyx rings"
                },
                {
                    itemId: 6573,
                    level: 67,
                    name: "Cut onyxes"
                },
                {
                    itemId: 2493,
                    level: 68,
                    name: "Craft blue d'hide chaps"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Craft Mixed hide capes"
                },
                {
                    itemId: 22278,
                    level: 69,
                    name: "Craft blue d'hide shields"
                },
                {
                    itemId: -1,
                    level: 69,
                    name: "Craft mixed hide boots"
                },
                {
                    itemId: 1515,
                    level: 70,
                    name: "Craft yew pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 2499,
                    level: 71,
                    name: "Craft blue d'hide bodies"
                },
                {
                    itemId: -1,
                    level: 71,
                    name: "Craft Mixed hide legs"
                },
                {
                    itemId: 1664,
                    level: 72,
                    name: "Craft dragon necklaces"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Craft Mixed hide tops"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Craft noxious halberds (with Smithing 72)"
                },
                {
                    itemId: -1,
                    level: 73,
                    name: "Craft red d'hide vambraces"
                },
                {
                    itemId: -1,
                    level: 73,
                    name: "Spin cotton boll into cotton yarn"
                },
                {
                    itemId: -1,
                    level: 73,
                    name: "Craft bolts of cotton"
                },
                {
                    itemId: 11115,
                    level: 74,
                    name: "Craft dragonstone bracelets"
                },
                {
                    itemId: 22201,
                    level: 75,
                    name: "Craft magic bird houses"
                },
                {
                    itemId: 2495,
                    level: 75,
                    name: "Craft red d'hide chaps"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Craft divine rune pouches"
                },
                {
                    itemId: 11866,
                    level: 75,
                    name: "Craft slayer rings (after purchasing \"Ring Bling\" for 150 Slayer reward points)"
                },
                {
                    itemId: 11866,
                    level: 75,
                    name: "Craft slayer rings (eternal) (after purchasing \"Ring Bling\" for 150 Slayer reward points)"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Craft Hueycoatl hide coif"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Craft Hueycoatl hide vambraces"
                },
                {
                    itemId: 22281,
                    level: 76,
                    name: "Craft red d'hide shields"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Craft camphor pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Craft Hueycoatl hide chaps"
                },
                {
                    itemId: 2501,
                    level: 77,
                    name: "Craft red d'hide bodies"
                },
                {
                    itemId: -1,
                    level: 78,
                    name: "Craft Hueycoatl hide body"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Craft black d'hide vambraces"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Craft ancient rings (with Magic 90)"
                },
                {
                    itemId: 1683,
                    level: 80,
                    name: "Craft dragonstone amulet (u)"
                },
                {
                    itemId: -1,
                    level: 81,
                    name: "Craft gem totes"
                },
                {
                    itemId: -1,
                    level: 81,
                    name: "Craft gem sacks"
                },
                {
                    itemId: 2497,
                    level: 82,
                    name: "Craft black d'hide chaps"
                },
                {
                    itemId: 6565,
                    level: 82,
                    name: "Craft onyx necklaces"
                },
                {
                    itemId: 21338,
                    level: 83,
                    name: "Craft amethyst bolt tips"
                },
                {
                    itemId: 22284,
                    level: 83,
                    name: "Craft black d'hide shields"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "CraftConfliction gauntlets (with Smithing 70)"
                },
                {
                    itemId: 2503,
                    level: 84,
                    name: "Craft black d'hide bodies"
                },
                {
                    itemId: 11130,
                    level: 84,
                    name: "Craft onyx bracelets"
                },
                {
                    itemId: -1,
                    level: 84,
                    name: "Craft necklace of rupture"
                },
                {
                    itemId: 21350,
                    level: 85,
                    name: "Craft amethyst arrowtips"
                },
                {
                    itemId: 1513,
                    level: 85,
                    name: "Craft magic pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Create accursed sceptres"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Craft amulet of rancour"
                },
                {
                    itemId: -1,
                    level: 87,
                    name: "Craft amethyst javelin tips"
                },
                {
                    itemId: 10973,
                    level: 87,
                    name: "Craft light orbs"
                },
                {
                    itemId: 25853,
                    level: 89,
                    name: "Craft amethyst dart tips"
                },
                {
                    itemId: 19499,
                    level: 89,
                    name: "Craft zenyte rings"
                },
                {
                    itemId: 19493,
                    level: 89,
                    name: "Cut zenytes"
                },
                {
                    itemId: 6566,
                    level: 90,
                    name: "Craft onyx amulet (u)"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Craft Armadylean plates"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Craft Fortified Masori armour"
                },
                {
                    itemId: 22204,
                    level: 90,
                    name: "Craft redwood bird houses"
                }
            ]
        },
        {
            label: "Members 3",
            entries: [
                {
                    itemId: -1,
                    level: 90,
                    name: "Craft ironwood pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 19500,
                    level: 92,
                    name: "Craft zenyte necklaces"
                },
                {
                    itemId: 19492,
                    level: 95,
                    name: "Craft zenyte bracelets"
                },
                {
                    itemId: 19669,
                    level: 95,
                    name: "Craft redwood pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: -1,
                    level: 97,
                    name: "Craft rosewood pyre ships (with Barbarian Training completed)"
                },
                {
                    itemId: 19501,
                    level: 98,
                    name: "Craft zenyte amulet (u)"
                },
                {
                    itemId: 9780,
                    level: 99,
                    name: "Buy the Crafting cape and hood from the Master Crafter in the Crafting Guild, and wear them"
                }
            ]
        }
    ]
};
