// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Farming/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const farmingSkillGuide: SkillGuideData = {
    skillId: SkillId.Farming,
    tabs: [
        {
            label: "Members 1",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level slightly increases the expected yield when harvesting crops with a variable crop yiel",
                    description: "d"
                },
                {
                    itemId: 1942,
                    level: 1,
                    name: "Grow potatoes"
                },
                {
                    itemId: 6010,
                    level: 2,
                    name: "Grow marigolds"
                },
                {
                    itemId: 6006,
                    level: 3,
                    name: "Grow barley"
                },
                {
                    itemId: 5994,
                    level: 4,
                    name: "Grow hammerstone hops"
                },
                {
                    itemId: 1957,
                    level: 5,
                    name: "Grow onions"
                },
                {
                    itemId: 1965,
                    level: 7,
                    name: "Grow cabbages"
                },
                {
                    itemId: 5996,
                    level: 8,
                    name: "Grow asgarnian hops"
                },
                {
                    itemId: 199,
                    level: 9,
                    name: "Grow grimy guam leaves"
                },
                {
                    itemId: 1951,
                    level: 10,
                    name: "Grow redberries"
                },
                {
                    itemId: 6014,
                    level: 11,
                    name: "Grow rosemary"
                },
                {
                    itemId: 1982,
                    level: 12,
                    name: "Grow tomatoes"
                },
                {
                    itemId: 5931,
                    level: 13,
                    name: "Grow jute fibres"
                },
                {
                    itemId: -1,
                    level: 13,
                    name: "Required to complete Diary Easy Kandarin Diary"
                },
                {
                    itemId: 201,
                    level: 14,
                    name: "Grow grimy marrentills"
                },
                {
                    itemId: 1521,
                    level: 15,
                    name: "Grow oak trees (produces oak logs when chopped, oak roots when dug up, and oak leaves when prune",
                    description: "d if diseased)"
                },
                {
                    itemId: 5998,
                    level: 16,
                    name: "Grow yanillian hops"
                },
                {
                    itemId: -1,
                    level: 17,
                    name: "Required for Quest Forgettable Tale..."
                },
                {
                    itemId: 1779,
                    level: 18,
                    name: "Grow flax"
                },
                {
                    itemId: 203,
                    level: 19,
                    name: "Grow grimy tarromins"
                },
                {
                    itemId: 5986,
                    level: 20,
                    name: "Grow sweetcorn"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Required for Quest The Garden of Death"
                },
                {
                    itemId: 6000,
                    level: 21,
                    name: "Grow krandorian hops"
                },
                {
                    itemId: 753,
                    level: 22,
                    name: "Grow cadava berries"
                },
                {
                    itemId: 6059,
                    level: 23,
                    name: "Build and place scarecrows"
                },
                {
                    itemId: 21504,
                    level: 23,
                    name: "Grow giant seaweed"
                },
                {
                    itemId: 6043,
                    level: 23,
                    name: "Obtain two oak roots when digging up a fully grown oak tree"
                },
                {
                    itemId: 6012,
                    level: 24,
                    name: "Grow nasturtiums"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Grow woad leaves"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Required for Quest Garden of Tranquillity"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Required to complete Diary Medium Varrock Diary"
                },
                {
                    itemId: 205,
                    level: 26,
                    name: "Grow grimy harralanders"
                },
                {
                    itemId: 225,
                    level: 26,
                    name: "Grow limpwurt roots"
                },
                {
                    itemId: -1,
                    level: 26,
                    name: "Required to complete Diary Medium Kandarin Diary"
                },
                {
                    itemId: -1,
                    level: 26,
                    name: "Completion of the Medium Kandarin Diary grants a 5% higher yield of herbs from the Catherby herb",
                    description: " patch"
                },
                {
                    itemId: -1,
                    level: 26,
                    name: "Completion of the Diary Hard Kandarin Diary grants a 10% higher yield of herbs from the Catherby",
                    description: " herb patch"
                },
                {
                    itemId: 1955,
                    level: 27,
                    name: "Grow Cooking apples (produces cooking apples when fully grown)"
                },
                {
                    itemId: 20905,
                    level: 27,
                    name: "Grow golpars"
                },
                {
                    itemId: -1,
                    level: 27,
                    name: "Required to complete Diary Medium Karamja Diary"
                },
                {
                    itemId: 6002,
                    level: 28,
                    name: "Grow wildblood hops"
                },
                {
                    itemId: -1,
                    level: 28,
                    name: "Grow elkhorn coral"
                },
                {
                    itemId: 3261,
                    level: 29,
                    name: "Grow goutweed"
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "Required for Quest My Arm's Big Adventure"
                },
                {
                    itemId: 1519,
                    level: 30,
                    name: "Grow Willow trees (produces willow logs when chopped, willow roots when dug up, and willow leave",
                    description: "s when pruned if diseased)"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required for Quest Enlightened Journey"
                },
                {
                    itemId: 5504,
                    level: 31,
                    name: "Grow strawberries"
                },
                {
                    itemId: 6043,
                    level: 31,
                    name: "Obtain three oak roots when digging up a fully grown oak tree"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Required to complete Diary Medium Ardougne Diary"
                },
                {
                    itemId: 207,
                    level: 32,
                    name: "Grow grimy ranarr weeds"
                },
                {
                    itemId: 1963,
                    level: 33,
                    name: "Grow banana trees (produces bananas when fully grown)"
                },
                {
                    itemId: 13426,
                    level: 34,
                    name: "Grow golovanova fruit (at the Tithe Farm)"
                },
                {
                    itemId: 6333,
                    level: 35,
                    name: "Grow teak trees (produces teak logs when chopped)"
                },
                {
                    itemId: 2126,
                    level: 36,
                    name: "Grow dwellberries"
                },
                {
                    itemId: 1987,
                    level: 36,
                    name: "Grow grapes"
                },
                {
                    itemId: -1,
                    level: 37,
                    name: "Grow hemp"
                },
                {
                    itemId: 3049,
                    level: 38,
                    name: "Grow grimy toadflax"
                },
                {
                    itemId: 6045,
                    level: 38,
                    name: "Obtain two willow roots when digging up a fully grown willow"
                },
                {
                    itemId: 20908,
                    level: 39,
                    name: "Grow buchu leaves"
                },
                {
                    itemId: 2108,
                    level: 39,
                    name: "Grow Oranges (produces oranges when fully grown)"
                },
                {
                    itemId: 6043,
                    level: 39,
                    name: "Obtain four oak roots when digging up a fully grown oak tree"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Required for Quest Rum Deal"
                },
                {
                    itemId: 5970,
                    level: 42,
                    name: "Grow Curry leafs (produces curry leaves when fully grown)"
                },
                {
                    itemId: 209,
                    level: 44,
                    name: "Grow grimy irit leaves"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Access the beginner tier of the Farming Guild"
                },
                {
                    itemId: 1517,
                    level: 45,
                    name: "Grow maple trees (produces maple logs when chopped, maple roots when dug up, and maple leaves wh",
                    description: "en pruned if diseased)"
                },
                {
                    itemId: 22993,
                    level: 45,
                    name: "Complete easy farming contracts"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Required for Quest Grim Tales"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Required to complete Diary Medium Kourend & Kebos Diary"
                },
                {
                    itemId: 6045,
                    level: 46,
                    name: "Obtain three willow roots when digging up a fully grown willow"
                },
                {
                    itemId: 5982,
                    level: 47,
                    name: "Grow watermelons"
                },
                {
                    itemId: 247,
                    level: 48,
                    name: "Grow jangerberries"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Pick Star flower ()"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Required for Quest Fairytale II - Cure a Queen"
                },
                {
                    itemId: 211,
                    level: 50,
                    name: "Grow grimy avantoes"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Make nature offerings (with Woodcutting 68)"
                },
                {
                    itemId: 2114,
                    level: 51,
                    name: "Grow Pineapples (produces pineapples when fully grown)"
                },
                {
                    itemId: -1,
                    level: 52,
                    name: "Grow pillar coral"
                },
                {
                    itemId: 6004,
                    level: 53,
                    name: "Grow bittercap mushrooms"
                },
                {
                    itemId: 6047,
                    level: 53,
                    name: "Obtain two maple roots when digging up a fully grown maple tree"
                },
                {
                    itemId: -1,
                    level: 53,
                    name: "Required to complete Diary Hard Morytania Diary"
                },
                {
                    itemId: 13427,
                    level: 54,
                    name: "Grow bologano fruit (at the Tithe Farm)"
                },
                {
                    itemId: 6045,
                    level: 54,
                    name: "Obtain four willow roots when digging up a fully grown willow"
                },
                {
                    itemId: 6016,
                    level: 55,
                    name: "Grow cactus spines"
                },
                {
                    itemId: 6332,
                    level: 55,
                    name: "Grow mahogany trees (produces mahogany logs when chopped)"
                },
                {
                    itemId: 20902,
                    level: 55,
                    name: "Grow noxifers"
                },
                {
                    itemId: 213,
                    level: 56,
                    name: "Grow grimy kwuarms"
                },
                {
                    itemId: 5972,
                    level: 57,
                    name: "Grow Papaya fruits (produces papayas when fully grown)"
                },
                {
                    itemId: 22932,
                    level: 58,
                    name: "Grow white lilies"
                },
                {
                    itemId: 239,
                    level: 59,
                    name: "Grow white berries"
                },
                {
                    itemId: 1515,
                    level: 60,
                    name: "Grow yew trees (produces yew logs when chopped, yew roots when dug up, and yew leaves when prune",
                    description: "d if diseased)"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: 231,
                    level: 61,
                    name: "Grow snape grass"
                },
                {
                    itemId: 6047,
                    level: 61,
                    name: "Obtain three maple roots when digging up a fully grown maple tree"
                },
                {
                    itemId: 3051,
                    level: 62,
                    name: "Grow grimy snapdragons"
                },
                {
                    itemId: -1,
                    level: 63,
                    name: "Grow nightshades"
                },
                {
                    itemId: -1,
                    level: 63,
                    name: "Required to complete Diary Hard Lumbridge & Draynor Diary"
                },
                {
                    itemId: 3138,
                    level: 64,
                    name: "Grow potato cacti"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Grow Huascas"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Access the intermediate tier of the Farming Guild"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Grow Hespori icon"
                },
                {
                    itemId: 22993,
                    level: 65,
                    name: "Complete medium farming contracts"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Required for Quest While Guthix Sleeps"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Grow camphor trees (produces camphor logs when chopped)"
                },
                {
                    itemId: 215,
                    level: 67,
                    name: "Grow grimy cadantines"
                },
                {
                    itemId: 5974,
                    level: 68,
                    name: "Grow Coconuts (produces coconuts when fully grown)"
                },
                {
                    itemId: 6049,
                    level: 68,
                    name: "Obtain two yew roots when digging up a fully grown yew tree"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Required to complete Diary Hard Varrock Diary"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Required to complete Diary Hard Western Provinces Diary"
                },
                {
                    itemId: 6047,
                    level: 69,
                    name: "Obtain four maple roots when digging up a fully grown maple tree"
                },
                {
                    itemId: 6018,
                    level: 70,
                    name: "Grow poison ivy berries"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Required for Quest Song of the Elves"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Required to complete Diary Hard Ardougne Diary"
                },
                {
                    itemId: -1,
                    level: 71,
                    name: "Grow Cotton bolls"
                },
                {
                    itemId: 5980,
                    level: 72,
                    name: "Grow Calquat fruits (produces calquat fruits when fully grown)"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Required to complete Diary Elite Karamja Diary"
                },
                {
                    itemId: 2485,
                    level: 73,
                    name: "Grow grimy lantadymes"
                },
                {
                    itemId: 23962,
                    level: 74,
                    name: "Grow Crystal shards (with Quest Song of the Elves completed)"
                },
                {
                    itemId: 13428,
                    level: 74,
                    name: "Grow logavano fruit (at the Tithe Farm)"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Required to complete Diary Hard Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Completion of the Hard Kourend & Kebos Diary grants a 5% higher yield of herbs from the Hosidius",
                    description: " and Farming Guild herb patches"
                },
                {
                    itemId: 1513,
                    level: 75,
                    name: "Grow magic trees (produces magic logs when chopped, magic roots when dug up, and magic leaves wh",
                    description: "en pruned if diseased)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Required to complete Diary Elite Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Grow attas plants"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Grow iasor plants"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Grow kronos plants"
                },
                {
                    itemId: 6049,
                    level: 76,
                    name: "Obtain three yew roots when digging up a fully grown yew tree"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Grow umbral coral"
                },
                {
                    itemId: 217,
                    level: 79,
                    name: "Grow grimy dwarf weeds"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Required to complete Diary Elite Kandarin Diary"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Completion of the Elite Kandarin Diary grants a 15% higher yield of herbs from the Catherby herb",
                    description: " patch"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Chances to obtain Spirit Seeds from the Reward Cart"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Grow ironwood trees (produces ironwood logs when chopped)"
                },
                {
                    itemId: 22929,
                    level: 81,
                    name: "Grow dragonfruit"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Grow spirit trees"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Can have one spirit tree grown"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Build a (with Construction 75)"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Build a (with Construction 95)"
                },
                {
                    itemId: 6051,
                    level: 83,
                    name: "Obtain two magic roots when digging up a fully grown magic tree"
                },
                {
                    itemId: 6049,
                    level: 84,
                    name: "Obtain four yew roots when digging up a fully grown yew tree"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Access the advanced tier of the Farming Guild"
                },
                {
                    itemId: 22935,
                    level: 85,
                    name: "Grow Celastrus barks"
                },
                {
                    itemId: 219,
                    level: 85,
                    name: "Grow grimy torstols"
                },
                {
                    itemId: 22993,
                    level: 85,
                    name: "Complete hard farming contracts"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Required to complete Diary Elite Ardougne Diary"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Required to complete Diary Elite Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 88,
                    name: "Can have two spirit trees grown"
                },
                {
                    itemId: 19669,
                    level: 90,
                    name: "Grow Redwood trees (produces redwood logs when chopped)"
                },
                {
                    itemId: 6051,
                    level: 91,
                    name: "Obtain three magic roots when digging up a fully grown magic tree"
                },
                {
                    itemId: -1,
                    level: 91,
                    name: "Required to complete Diary Elite Falador Diary"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Grow rosewood trees (produces rosewood logs when chopped)"
                },
                {
                    itemId: -1,
                    level: 93,
                    name: "Can have three spirit trees grown"
                },
                {
                    itemId: -1,
                    level: 96,
                    name: "Can have four spirit trees grown"
                },
                {
                    itemId: 9810,
                    level: 99,
                    name: "Buy the Farming cape and hood from the Martin the Master Gardener in the Draynor Village market,",
                    description: " and wear them"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Herb patches will have a 5% greater yield while wearing the farming cape"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Can have unlimited spirit trees grown"
                },
                {
                    itemId: 6051,
                    level: 99,
                    name: "Obtain four magic roots when digging up a fully grown magic tree"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        }
    ]
};
