// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Herblore/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const herbloreSkillGuide: SkillGuideData = {
    skillId: SkillId.Herblore,
    tabs: [
        {
            label: "Members 1",
            entries: [
                {
                    itemId: 199,
                    level: 3,
                    name: "Clean grimy guam leaves"
                },
                {
                    itemId: 1533,
                    level: 3,
                    name: "Clean grimy rogue's purses"
                },
                {
                    itemId: 1525,
                    level: 3,
                    name: "Clean grimy snake weeds"
                },
                {
                    itemId: 91,
                    level: 3,
                    name: "Mix Guam potion (unf)"
                },
                {
                    itemId: 121,
                    level: 3,
                    name: "Mix Attack potion(4)s"
                },
                {
                    itemId: 11429,
                    level: 4,
                    name: "Mix Attack mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 201,
                    level: 5,
                    name: "Clean grimy marrentills"
                },
                {
                    itemId: 93,
                    level: 5,
                    name: "Mix marrentill potions (unf)"
                },
                {
                    itemId: 175,
                    level: 5,
                    name: "Mix Antipoison(4)s"
                },
                {
                    itemId: 11433,
                    level: 6,
                    name: "Mix Antipoison mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 203,
                    level: 11,
                    name: "Clean grimy tarromins"
                },
                {
                    itemId: 95,
                    level: 12,
                    name: "Mix tarromin potions (unf)"
                },
                {
                    itemId: 113,
                    level: 12,
                    name: "Mix Strength potion(4)s"
                },
                {
                    itemId: 11441,
                    level: 14,
                    name: "Mix Strength mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 10142,
                    level: 19,
                    name: "Mix guam tars"
                },
                {
                    itemId: 205,
                    level: 20,
                    name: "Clean grimy harralanders"
                },
                {
                    itemId: 97,
                    level: 22,
                    name: "Mix harralander potions (unf)"
                },
                {
                    itemId: 6470,
                    level: 22,
                    name: "Mix Compost potion(4)s"
                },
                {
                    itemId: 7652,
                    level: 22,
                    name: "Mix Guthix balance(4)s"
                },
                {
                    itemId: 127,
                    level: 22,
                    name: "Mix Restore potion(4)s"
                },
                {
                    itemId: 11449,
                    level: 24,
                    name: "Mix Restore mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 207,
                    level: 25,
                    name: "Clean grimy ranarr weeds"
                },
                {
                    itemId: 1582,
                    level: 25,
                    name: "Mix blamish oils"
                },
                {
                    itemId: 3008,
                    level: 26,
                    name: "Mix Energy potion(4)s"
                },
                {
                    itemId: 11453,
                    level: 29,
                    name: "Mix Energy mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 3049,
                    level: 30,
                    name: "Clean grimy toadflaxs"
                },
                {
                    itemId: 99,
                    level: 30,
                    name: "Mix ranarr potions (unf)"
                },
                {
                    itemId: 133,
                    level: 30,
                    name: "Mix Defence potion(4)s"
                },
                {
                    itemId: 10143,
                    level: 31,
                    name: "Mix marrentill tars"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Harvest herbs from the Herbiboar (with Hunter 80)"
                },
                {
                    itemId: 11457,
                    level: 33,
                    name: "Mix Defence mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 3002,
                    level: 34,
                    name: "Mix toadflax potions (unf)"
                },
                {
                    itemId: 3032,
                    level: 34,
                    name: "Mix Agility potion(4)s"
                },
                {
                    itemId: 9739,
                    level: 36,
                    name: "Mix Combat potion(4)s"
                },
                {
                    itemId: 11461,
                    level: 37,
                    name: "Mix Agility mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 139,
                    level: 38,
                    name: "Mix Prayer potion(4)s"
                },
                {
                    itemId: 10144,
                    level: 39,
                    name: "Mix tarromin tars"
                },
                {
                    itemId: 209,
                    level: 40,
                    name: "Clean grimy irit leaves"
                },
                {
                    itemId: 11445,
                    level: 40,
                    name: "Mix combat mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 11465,
                    level: 42,
                    name: "Mix Prayer mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 10145,
                    level: 44,
                    name: "Mix harralander tars"
                },
                {
                    itemId: 101,
                    level: 45,
                    name: "Mix irit potions (unf)"
                },
                {
                    itemId: 145,
                    level: 45,
                    name: "Mix Super attack(4)s"
                },
                {
                    itemId: 11469,
                    level: 47,
                    name: "Mix Superattack mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 20913,
                    level: 47,
                    name: "Mix Elder (-) potions"
                },
                {
                    itemId: 20925,
                    level: 47,
                    name: "Mix Twisted (-) potions"
                },
                {
                    itemId: 20937,
                    level: 47,
                    name: "Mix Kodai (-) potions"
                },
                {
                    itemId: 211,
                    level: 48,
                    name: "Clean grimy avantoes"
                },
                {
                    itemId: 181,
                    level: 48,
                    name: "Mix Superantipoison(4)s"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Create anti-odour salt"
                },
                {
                    itemId: 103,
                    level: 50,
                    name: "Mix avantoe potions (unf)"
                },
                {
                    itemId: 151,
                    level: 50,
                    name: "Mix Fishing potion(4)s"
                },
                {
                    itemId: 11473,
                    level: 51,
                    name: "Mix Anti-poison supermix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 3016,
                    level: 52,
                    name: "Mix super energies"
                },
                {
                    itemId: 20949,
                    level: 52,
                    name: "Mix Revitalisation (-) potions"
                },
                {
                    itemId: 20961,
                    level: 52,
                    name: "Mix Prayer enhance (-) potions"
                },
                {
                    itemId: 20973,
                    level: 52,
                    name: "Mix Xeric's aid (-) potions"
                },
                {
                    itemId: 9998,
                    level: 53,
                    name: "Mix Hunter potion(4)s"
                },
                {
                    itemId: 11477,
                    level: 53,
                    name: "Mix Fishing mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 213,
                    level: 54,
                    name: "Clean grimy kwuarms"
                },
                {
                    itemId: -1,
                    level: 54,
                    name: "Mix Goading potion(4)s"
                },
                {
                    itemId: 105,
                    level: 55,
                    name: "Mix kwuarm potions (unf)"
                },
                {
                    itemId: 157,
                    level: 55,
                    name: "Mix Super strength(4)s"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Mix irit tars"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Mix Elkhorn potion (unf)"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Mix Haemostatic poultice"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Create haemostatic dressings"
                },
                {
                    itemId: 11481,
                    level: 56,
                    name: "Mix Super energy mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: -1,
                    level: 58,
                    name: "Clean grimy huascas"
                },
                {
                    itemId: 11517,
                    level: 58,
                    name: "Mix Hunting mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: -1,
                    level: 58,
                    name: "Mix Prayer regeneration potion(4)s"
                },
                {
                    itemId: -1,
                    level: 58,
                    name: "Required to purchase a Herb sack"
                },
                {
                    itemId: 3051,
                    level: 59,
                    name: "Clean grimy snapdragons"
                },
                {
                    itemId: 11485,
                    level: 59,
                    name: "Mix Super str. mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 20917,
                    level: 59,
                    name: "Mix Elder potion (4)s"
                },
                {
                    itemId: 20929,
                    level: 59,
                    name: "Mix Twisted potion (4)s"
                },
                {
                    itemId: 20941,
                    level: 59,
                    name: "Mix Kodai potion (4)s"
                },
                {
                    itemId: 187,
                    level: 60,
                    name: "Mix weapon poisons"
                },
                {
                    itemId: 11730,
                    level: 60,
                    name: "Mix Overload (-)s"
                },
                {
                    itemId: 175,
                    level: 60,
                    name: "Mix Antipoison (-)s"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Mix Mammoth-might mix in Mastering Mixology"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Mix Alco-augmentator in Mastering Mixology"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Mix Liplack liquor in Mastering Mixology"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Participate in Mastering Mixology"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Mix Pillar potion (unf)"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Mix Super fishing potion(4)s"
                },
                {
                    itemId: 3004,
                    level: 63,
                    name: "Mix snapdragon potions (unf)"
                },
                {
                    itemId: 3024,
                    level: 63,
                    name: "Mix Super restore(4)s"
                },
                {
                    itemId: -1,
                    level: 63,
                    name: "Mix Mystic mana amalgam in Mastering Mixology"
                },
                {
                    itemId: 215,
                    level: 65,
                    name: "Clean grimy cadantines"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: 20953,
                    level: 65,
                    name: "Mix Revitalisation potion (4)s"
                },
                {
                    itemId: 20961,
                    level: 65,
                    name: "Mix Prayer enhance potions"
                },
                {
                    itemId: 20973,
                    level: 65,
                    name: "Mix Xeric's aid potions"
                },
                {
                    itemId: 107,
                    level: 66,
                    name: "Mix cadantine potions (unf)"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Mix extreme energies"
                },
                {
                    itemId: 163,
                    level: 66,
                    name: "Mix Super defence(4)s"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Mix Marley's moonlight in Mastering Mixology"
                },
                {
                    itemId: 2485,
                    level: 67,
                    name: "Clean grimy lantadymes"
                },
                {
                    itemId: -1,
                    level: 67,
                    name: "Mix Super hunter potion(4)s"
                },
                {
                    itemId: 11493,
                    level: 67,
                    name: "Mix Super restore mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 5942,
                    level: 68,
                    name: "Mix Antidote+(4)"
                },
                {
                    itemId: 2483,
                    level: 69,
                    name: "Mix lantadyme potions (unf)"
                },
                {
                    itemId: 2452,
                    level: 69,
                    name: "Mix Antifire potion(4)s"
                },
                {
                    itemId: -1,
                    level: 69,
                    name: "Mix Azure aura mix in Mastering Mixology"
                },
                {
                    itemId: 217,
                    level: 70,
                    name: "Clean grimy dwarf weeds"
                },
                {
                    itemId: 20913,
                    level: 70,
                    name: "Mix Elder (+) potions"
                },
                {
                    itemId: 20925,
                    level: 70,
                    name: "Mix Twisted (+) potions"
                },
                {
                    itemId: 20937,
                    level: 70,
                    name: "Mix Kodai (+) potions"
                },
                {
                    itemId: 11497,
                    level: 71,
                    name: "Mix Super def. mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 109,
                    level: 72,
                    name: "Mix dwarf weed potions (unf)"
                },
                {
                    itemId: 169,
                    level: 72,
                    name: "Mix Ranging potion(4)s"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Mix Aqualux amalgam in Mastering Mixology"
                },
                {
                    itemId: 187,
                    level: 73,
                    name: "Mix weapon poison+"
                },
                {
                    itemId: 11501,
                    level: 74,
                    name: "Mix Antidote+ mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 219,
                    level: 75,
                    name: "Clean grimy torstols"
                },
                {
                    itemId: 11505,
                    level: 75,
                    name: "Mix Antifire mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 11730,
                    level: 75,
                    name: "Mix Overloads"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Mix Megalite liquid in Mastering Mixology"
                },
                {
                    itemId: 3040,
                    level: 76,
                    name: "Mix Magic potion(4)s"
                },
                {
                    itemId: 12625,
                    level: 77,
                    name: "Mix Stamina potion(4)s"
                },
                {
                    itemId: 111,
                    level: 78,
                    name: "Mix torstol potions (unf)"
                },
                {
                    itemId: 189,
                    level: 78,
                    name: "Mix Zamorak brew(4)s"
                },
                {
                    itemId: 20949,
                    level: 78,
                    name: "Mix Revitalisation (+) potions"
                },
                {
                    itemId: 20961,
                    level: 78,
                    name: "Mix Prayer enhance (+) potions"
                },
                {
                    itemId: 20973,
                    level: 78,
                    name: "Mix Xeric's aid (+) potions"
                },
                {
                    itemId: -1,
                    level: 78,
                    name: "Mix Anti-leech lotion in Mastering Mixology"
                },
                {
                    itemId: 5942,
                    level: 79,
                    name: "Mix Antidote++(4)"
                },
                {
                    itemId: 22443,
                    level: 80,
                    name: "Mix cadantine blood potions (unf)"
                },
                {
                    itemId: 22461,
                    level: 80,
                    name: "Mix Bastion potion(4)s"
                },
                {
                    itemId: 22449,
                    level: 80,
                    name: "Mix Battlemage potion(4)s"
                },
                {
                    itemId: 11509,
                    level: 80,
                    name: "Mix Ranging mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 6685,
                    level: 81,
                    name: "Mix Saradomin brew(4)s"
                },
                {
                    itemId: -1,
                    level: 81,
                    name: "Mix Surge potion(4)s"
                },
                {
                    itemId: -1,
                    level: 81,
                    name: "Mix Mixalot in Mastering Mixology"
                },
                {
                    itemId: 187,
                    level: 82,
                    name: "Mix weapon poison++"
                },
                {
                    itemId: 11513,
                    level: 83,
                    name: "Mix Magic mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 11951,
                    level: 84,
                    name: "Mix Extended antifire(4)s"
                },
                {
                    itemId: 26340,
                    level: 85,
                    name: "Mix Ancient brew(4)s"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Mix Extended stamina potion(4)s"
                },
                {
                    itemId: 11521,
                    level: 85,
                    name: "Mix Zamorak mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 12633,
                    level: 86,
                    name: "Mix Stamina mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 12905,
                    level: 87,
                    name: "Mix Anti-venom(4)s"
                },
                {
                    itemId: -1,
                    level: 88,
                    name: "Mix Menaphite remedy(4)"
                },
                {
                    itemId: -1,
                    level: 89,
                    name: "Mix Umbral potion (unf)"
                },
                {
                    itemId: -1,
                    level: 89,
                    name: "Mix Armadyl brew(4)s"
                },
                {
                    itemId: 12695,
                    level: 90,
                    name: "Mix Super combat potion(4)s"
                },
                {
                    itemId: 11730,
                    level: 90,
                    name: "Mix Overload (+)s"
                },
                {
                    itemId: -1,
                    level: 91,
                    name: "Mix Forgotten brew(4)s"
                },
                {
                    itemId: 11960,
                    level: 91,
                    name: "Mix Extended antifire mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 26350,
                    level: 92,
                    name: "Mix Ancient mix(2)es (with Barbarian Herblore completed)"
                },
                {
                    itemId: 12905,
                    level: 94,
                    name: "Mix Anti-venom+(4)"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Mix Extended anti-venom+(4)"
                },
                {
                    itemId: 9774,
                    level: 99,
                    name: "Buy the herblore cape and hood from Kaqemeex at the druid circle in Taverley, and wear them"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        }
    ]
};
