// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Magic/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const magicSkillGuide: SkillGuideData = {
    skillId: SkillId.Magic,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level increases chance of magic attacks against the player missing, where damage taken is c",
                    description: "alculated from 70% Magic level, 30% Defence level, and Magic defence bonus"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level slightly increases the player's accuracy with Magic attacks"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Cast Lumbridge Home Teleport on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Cast Wind Strike on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 3,
                    name: "Cast Confuse on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 5,
                    name: "Cast Water Strike on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 5,
                    name: "Hit up to 4 base damage with Wind Strike"
                },
                {
                    itemId: -1,
                    level: 7,
                    name: "Cast Lvl-1 Enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 9,
                    name: "Cast Earth Strike on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 9,
                    name: "Hit up to 6 base damage with Wind Strike and Water Strike"
                },
                {
                    itemId: -1,
                    level: 11,
                    name: "Cast Weaken on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 13,
                    name: "Cast Fire Strike on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 13,
                    name: "Hit up to 8 base damage with Wind Strike, Water Strike, and Earth Strike"
                },
                {
                    itemId: 8014,
                    level: 15,
                    name: "Cast Bones to Bananas on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 17,
                    name: "Cast Wind Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 19,
                    name: "Cast Curse on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Cast Bind on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Cast Low Level Alchemy on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 23,
                    name: "Cast Water Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 23,
                    name: "Hit up to 10 base damage with Wind Bolt"
                },
                {
                    itemId: 8007,
                    level: 25,
                    name: "Cast Varrock Teleport on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 27,
                    name: "Cast Lvl-2 Enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "Cast Earth Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "Hit up to 11 base damage with Wind Bolt and Water Bolt"
                },
                {
                    itemId: 22368,
                    level: 30,
                    name: "Wield Bryophyta's staves (with Attack 30)"
                },
                {
                    itemId: 8008,
                    level: 31,
                    name: "Cast Lumbridge Teleport on the standard spellbook"
                },
                {
                    itemId: 8022,
                    level: 33,
                    name: "Cast Telekinetic Grab on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Cast Fire Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Hit up to 12 base damage with Wind Bolt, Water Bolt, and Earth Bolt"
                },
                {
                    itemId: 8009,
                    level: 37,
                    name: "Cast Falador Teleport on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Cast Crumble Undead on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 41,
                    name: "Cast Wind Blast on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Cast Monster Inspect on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 43,
                    name: "Cast Superheat Item on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 47,
                    name: "Cast Water Blast on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 47,
                    name: "Hit up to 14 base damage with Wind Blast"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Cast Lvl-3 Enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Cast Snare on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 51,
                    name: "Possibility of gaining Magic XP from the Evil Bob random event"
                },
                {
                    itemId: -1,
                    level: 53,
                    name: "Cast Earth Blast on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 53,
                    name: "Hit up to 15 base damage with Wind Blast and Water Blast"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Cast High Level Alchemy on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Cast Lvl-4 Enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 59,
                    name: "Cast Fire Blast on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 59,
                    name: "Hit up to 16 base damage with Wind Blast, Water Blast, and Earth Blast"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Cast Tele Block on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        },
        {
            label: "Members 1",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Cast Arceuus Home Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Cast Edgeville Home Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Cast Lunar Home Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 4,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 6,
                    name: "Cast Arceuus Library Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 7,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 7,
                    name: "Required for Quest In Aid of the Myreque"
                },
                {
                    itemId: -1,
                    level: 14,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 15,
                    name: "Required for Quest Watchtower"
                },
                {
                    itemId: -1,
                    level: 16,
                    name: "Cast Basic Reanimation on the Arceuus spellbook"
                },
                {
                    itemId: 19615,
                    level: 17,
                    name: "Cast Draynor Manor Teleport on the Arceuus spellbook"
                },
                {
                    itemId: 13387,
                    level: 20,
                    name: "Wear Xerician top (with Defence 10)"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Required for Quest Elemental Workshop II"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Required to complete Diary Easy Wilderness Diary"
                },
                {
                    itemId: 22949,
                    level: 23,
                    name: "Cast Battlefront Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 24,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Required to complete Diary Medium Varrock Diary"
                },
                {
                    itemId: -1,
                    level: 27,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: 19617,
                    level: 28,
                    name: "Cast Mind Altar Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: 11998,
                    level: 30,
                    name: "Wield battlestaves (with Attack 30)"
                },
                {
                    itemId: 10149,
                    level: 30,
                    name: "Wield swamp lizards (with Attack 30 and Ranged)"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Required to complete Diary Medium Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 33,
                    name: "Required for Quest Darkness of Hallowvale"
                },
                {
                    itemId: -1,
                    level: 33,
                    name: "Required for Quest The Giant Dwarf"
                },
                {
                    itemId: -1,
                    level: 33,
                    name: "Required for Quest Spirits of the Elid"
                },
                {
                    itemId: -1,
                    level: 34,
                    name: "Cast Respawn Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Cast Ghostly Grasp on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 37,
                    name: "Required to complete Diary Medium Falador Diary"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Cast Resurrect Lesser Ghost on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Cast Resurrect Lesser Skeleton on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Cast Resurrect Lesser Zombie on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Required for Quest Enakhra's Lament"
                },
                {
                    itemId: 19619,
                    level: 40,
                    name: "Cast Salve Graveyard Teleport on the Arceuus spellbook"
                },
                {
                    itemId: 8013,
                    level: 40,
                    name: "Cast Teleport to House on the standard spellbook"
                },
                {
                    itemId: 20517,
                    level: 40,
                    name: "Wear Elder chaos top"
                },
                {
                    itemId: 4091,
                    level: 40,
                    name: "Wear Mystic robe top (with Defence 20)"
                },
                {
                    itemId: 7399,
                    level: 40,
                    name: "Wear Enchanted top (with Defence 20)"
                },
                {
                    itemId: 20131,
                    level: 40,
                    name: "Wear Robe top of darkness (with Defence 20)"
                },
                {
                    itemId: 6139,
                    level: 40,
                    name: "Wear Skeletal top (with Defence 40 and Quest The Fremennik Trials completed)"
                },
                {
                    itemId: 3387,
                    level: 40,
                    name: "Wear Splitbark body (with Defence 40)"
                },
                {
                    itemId: 6563,
                    level: 40,
                    name: "Wield mystic staves (with Attack 40)"
                },
                {
                    itemId: -1,
                    level: 41,
                    name: "Cast Adept Reanimation on the Arceuus spellbook"
                },
                {
                    itemId: 8839,
                    level: 42,
                    name: "Wear Void knight top (with Attack 42, Strength, Defence, Ranged, Hitpoints, and Prayer 22)"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Required to complete Diary Elite Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Cast Inferior Demonbane on the Arceuus spellbook"
                },
                {
                    itemId: 8010,
                    level: 45,
                    name: "Cast Camelot Teleport on the standard spellbook"
                },
                {
                    itemId: 6908,
                    level: 45,
                    name: "Wield beginner wands"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Required for Quest King's Ransom"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Required to complete Diary Medium Kandarin Diary"
                },
                {
                    itemId: -1,
                    level: 46,
                    name: "Required for Quest The Eyes of Glouphrie"
                },
                {
                    itemId: -1,
                    level: 47,
                    name: "Cast Shadow Veil on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 48,
                    name: "Cast Kourend Castle Teleport on the standard spellbook (with Quest Client of Kourend completed)"
                },
                {
                    itemId: 19621,
                    level: 48,
                    name: "Cast Fenkenstrain's Castle Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Required to complete Quest Sins of the Father"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Cast Iban Blast on the standard spellbook (with Quest Underground Pass completed)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Cast Magic Dart on the standard spellbook (with Slayer 55)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Cast Dark Lure on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Cast Smoke Rush whilst on Ancient Magicks"
                },
                {
                    itemId: 6916,
                    level: 50,
                    name: "Wear Infinity top (with Defence 25)"
                },
                {
                    itemId: 25389,
                    level: 50,
                    name: "Wear swampbark body (with Defence 50)"
                },
                {
                    itemId: 6910,
                    level: 50,
                    name: "Wield apprentice wands"
                },
                {
                    itemId: 1409,
                    level: 50,
                    name: "Wield Iban's staves (with Attack 50 and Quest Underground Pass completed)"
                },
                {
                    itemId: 4170,
                    level: 50,
                    name: "Wield slayer's staves (with Slayer 55)"
                },
                {
                    itemId: 4675,
                    level: 50,
                    name: "Wield ancient staves (with Attack 50 and Quest Desert Treasure I completed)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Wield bone staves"
                },
                {
                    itemId: 10146,
                    level: 50,
                    name: "Wield orange salamanders (with Attack 50 and Ranged)"
                },
                {
                    itemId: 20714,
                    level: 50,
                    name: "Wield tomes of fire"
                },
                {
                    itemId: 25574,
                    level: 50,
                    name: "Wield tomes of water"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Wield tomes of earth"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required for Quest Desert Treasure I"
                },
                {
                    itemId: 8011,
                    level: 51,
                    name: "Cast Ardougne Teleport on the standard spellbook (with Quest Plague City completed)"
                },
                {
                    itemId: -1,
                    level: 51,
                    name: "Required to complete Diary Medium Ardougne Diary"
                },
                {
                    itemId: -1,
                    level: 52,
                    name: "Cast Shadow Rush whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 54,
                    name: "Cast Civitas illa Fortis Teleport on the standard spellbook (with Quest Twilight's Promise compl",
                    description: "eted)"
                },
                {
                    itemId: 12781,
                    level: 54,
                    name: "Cast Paddewwa Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 54,
                    name: "Required to complete Diary Hard Varrock Diary"
                },
                {
                    itemId: 6912,
                    level: 55,
                    name: "Wield teacher wands"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Cast Charge Water Orb on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Cast Summon Boat on the standard spellbook (with Quest The Pandemonium completed)"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Cast Skeletal Grasp on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Cast Blood Rush whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Required for Quest Legends' Quest"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Required to complete Diary Hard Kandarin Diary"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Cast Resurrect Superior Ghost on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Cast Resurrect Superior Skeleton on the Arceuus spellbook (with Quest A Kingdom Divided complete",
                    description: "d)"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Cast Resurrect Superior Zombie on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Required for Quest The Blood Moon Rises"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: -1,
                    level: 58,
                    name: "Cast Ice Rush whilst on Ancient Magicks"
                },
                {
                    itemId: 8012,
                    level: 58,
                    name: "Cast Watchtower Teleport on the standard spellbook (with Quest Watchtower completed)"
                },
                {
                    itemId: -1,
                    level: 59,
                    name: "Cast Mark of Darkness on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 59,
                    name: "Required for Quest Family Crest"
                },
                {
                    itemId: 6926,
                    level: 60,
                    name: "Cast Bones to Peaches on the standard spellbook (after unlocking the spell at the Minigame Mage ",
                    description: "Training Arena)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Cast Charge Earth Orb on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Cast Claws of Guthix on the standard spellbook (with Mage Arena completed)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Cast Flames of Zamorak on the standard spellbook (with Mage Arena completed)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Cast Saradomin Strike on the standard spellbook (with Mage Arena completed)"
                },
                {
                    itemId: 12782,
                    level: 60,
                    name: "Cast Senntisten Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: 13239,
                    level: 60,
                    name: "Craft Primordial boots, Eternal boots, and Pegasian boots (with Runecraft 60)"
                },
                {
                    itemId: 2412,
                    level: 60,
                    name: "Wear Saradomin cape (with Mage Arena I completed)"
                },
                {
                    itemId: 25404,
                    level: 60,
                    name: "Wear bloodbark body (with Defence 60)"
                },
                {
                    itemId: 6914,
                    level: 60,
                    name: "Wield master wands"
                },
                {
                    itemId: 2417,
                    level: 60,
                    name: "Wield god staves (with Mage Arena I completed)"
                },
                {
                    itemId: 22552,
                    level: 60,
                    name: "Wield Thammaron's sceptres"
                },
                {
                    itemId: 6526,
                    level: 60,
                    name: "Wield Toktz-mej-tals (with Attack 60)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Wield twinflame staves"
                },
                {
                    itemId: 10147,
                    level: 60,
                    name: "Wield red salamanders (with Attack 60 and Ranged)"
                },
                {
                    itemId: 6889,
                    level: 60,
                    name: "Wield mage's books"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Required to complete Diary Hard Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Required to complete Diary Medium Wilderness Diary"
                },
                {
                    itemId: 11747,
                    level: 61,
                    name: "Cast Trollheim Teleport on the standard spellbook (with Quest Eadgar's Ruse completed)"
                },
                {
                    itemId: 19623,
                    level: 61,
                    name: "Cast West Ardougne Teleport on the Arceuus spellbook (with Quest Biohazard completed)"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Cast Wind Wave on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Cast Superior Demonbane on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Cast Smoke Burst whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Wield Warped sceptres"
                },
                {
                    itemId: -1,
                    level: 63,
                    name: "Cast Charge Fire Orb on the standard spellbook"
                },
                {
                    itemId: 19631,
                    level: 64,
                    name: "Cast Ape Atoll Teleport on the standard spellbook (with Quest Recipe for Disaster: Freeing King ",
                    description: "Awowogei completed)"
                },
                {
                    itemId: -1,
                    level: 64,
                    name: "Cast Lesser Corruption on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 64,
                    name: "Cast Shadow Burst whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 64,
                    name: "Required to complete Diary Hard Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Cast Bake Pie on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Cast Geomancy on the Lunar spellbook"
                },
                {
                    itemId: 19625,
                    level: 65,
                    name: "Cast Harmony Island Teleport on the Arceuus spellbook (with Quest The Great Brain Robbery comple",
                    description: "ted)"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Cast Water Wave on the standard spellbook"
                },
                {
                    itemId: 10338,
                    level: 65,
                    name: "Wear 3rd Age robe top (with Defence 30)"
                },
                {
                    itemId: 12422,
                    level: 65,
                    name: "Wield 3rd Age wands"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Wield dragon hunter wands"
                },
                {
                    itemId: 12825,
                    level: 65,
                    name: "Wield arcane spirit shields (with Prayer 70 and Defence 75)"
                },
                {
                    itemId: 12821,
                    level: 65,
                    name: "Wield spectral spirit shields (with Prayer 70 and Defence 75)"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Hit up to 18 base damage with Wind Wave"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Required for Quest Lunar Diplomacy"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Access to the Wizards' Guild"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Cast Vulnerability on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Cast Vile Vigour on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: 12779,
                    level: 66,
                    name: "Cast Kharyrll Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Cast Charge Air Orb on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Cast Cure Plant on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Cast Monster Examine on the Lunar spellbook (with Quest Dream Mentor completed)"
                },
                {
                    itemId: 21633,
                    level: 66,
                    name: "Forge ancient wyvern shields (with Smithing 66)"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Required for Quest Swan Song"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Required to complete Diary Hard Ardougne Diary"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Required to complete Diary Hard Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Required to complete Diary Hard Morytania Diary"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Required to complete Diary Hard Wilderness Diary"
                },
                {
                    itemId: -1,
                    level: 67,
                    name: "Cast Astral Contact on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 67,
                    name: "Cast Teleport to Boat on the standard spellbook (with Quest The Pandemonium completed)"
                },
                {
                    itemId: -1,
                    level: 67,
                    name: "Required for Quest While Guthix Sleeps"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Cast Blood Burst whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Cast Cure Other on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Cast Humidify on the Lunar spellbook (with Quest Dream Mentor completed)"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Cast lvl-5 enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Required to complete Diary Hard Desert Diary"
                },
                {
                    itemId: 24949,
                    level: 69,
                    name: "Cast Moonclan Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Cast Earth Wave on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Cast Degrime on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Cast Ice Burst whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Cast Tele Group Moonclan on the Lunar spellbook"
                },
                {
                    itemId: 24291,
                    level: 70,
                    name: "Wear Dagon'hai robe top (with Defence 40)"
                },
                {
                    itemId: 4712,
                    level: 70,
                    name: "Wear Ahrim's robetop (with Defence 70)"
                },
                {
                    itemId: 22951,
                    level: 70,
                    name: "Wear Boots of Brimstone (with Defence 70 and Ranged)"
                },
                {
                    itemId: 12002,
                    level: 70,
                    name: "Wear occult necklaces"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Wield accursed sceptres"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Wield ancient sceptres (with Attack 50, Strength 60), and Quest Secrets of the North completed)"
                },
                {
                    itemId: 4710,
                    level: 70,
                    name: "Wield Ahrim's staff (with Attack 70)"
                },
                {
                    itemId: 10148,
                    level: 70,
                    name: "Wield black salamanders (with Attack 70 and Ranged)"
                },
                {
                    itemId: 21633,
                    level: 70,
                    name: "Wield ancient wyvern shields (with Defence 75 and partial completion of Quest Dragon Slayer I)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Hit up to 19 base damage with Wind Wave and Water Wave"
                },
                {
                    itemId: 19627,
                    level: 71,
                    name: "Cast Cemetery Teleport on the Arceuus spellbook"
                },
                {
                    itemId: -1,
                    level: 71,
                    name: "Cast Cure Me on the Lunar spellbook"
                },
                {
                    itemId: 11159,
                    level: 71,
                    name: "Cast Hunter Kit (with Lunar spells unlocked and Quest Dream Mentor completed)"
                },
                {
                    itemId: 24951,
                    level: 71,
                    name: "Cast Ourania Teleport on the Lunar spellbook (after speaking to Baba Yaga)"
                },
                {
                    itemId: 24422,
                    level: 72,
                    name: "Wield the Nightmare staff (with Hitpoints 50)"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Cast Expert Reanimation on the Arceuus spellbook"
                },
                {
                    itemId: 12780,
                    level: 72,
                    name: "Cast Lassar Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: 24953,
                    level: 72,
                    name: "Cast Waterbirth Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Required to complete Diary Hard Fremennik Diary"
                }
            ]
        },
        {
            label: "Members 3",
            entries: [
                {
                    itemId: -1,
                    level: 73,
                    name: "Cast Enfeeble on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 73,
                    name: "Cast Ward of Arceuus on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 73,
                    name: "Cast Tele Group Waterbirth on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Cast Cure Group on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Cast Smoke Blitz whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Cast Teleother Lumbridge on the standard spellbook"
                },
                {
                    itemId: 24955,
                    level: 75,
                    name: "Cast Barbarian Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Cast Fire Wave on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Cast Stat Spy on the Lunar spellbook (with Quest Dream Mentor completed)"
                },
                {
                    itemId: 21791,
                    level: 75,
                    name: "Wear imbued god capes (with Mage Arena II completed)"
                },
                {
                    itemId: 21021,
                    level: 75,
                    name: "Wear Ancestral robe top (with Defence 65)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Wear Blue moon chestplate (with Defence 50)"
                },
                {
                    itemId: 13235,
                    level: 75,
                    name: "Wear eternal boots (with Defence 75)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Wield blue moon spears (with Attack 70)"
                },
                {
                    itemId: 11905,
                    level: 75,
                    name: "Wield tridents of the seas"
                },
                {
                    itemId: 4170,
                    level: 75,
                    name: "Wield slayer's staves (e) (with Slayer 55)"
                },
                {
                    itemId: 11791,
                    level: 75,
                    name: "Wield staves of the dead (with Attack 75)"
                },
                {
                    itemId: 24144,
                    level: 75,
                    name: "Wield staves of balance (with Attack 75)"
                },
                {
                    itemId: 22296,
                    level: 75,
                    name: "Wield staves of light (with Attack 75)"
                },
                {
                    itemId: 12904,
                    level: 75,
                    name: "Wield toxic staves of the dead (with Attack 75)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Hit up to 20 base damage with Wind Wave, Water Wave, and Earth Wave"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Required for Quest Dragon Slayer II"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Required for Quest Desert Treasure II - The Fallen Empire"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Cast Resurrect Greater Ghost on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Cast Resurrect Greater Skeleton on the Arceuus spellbook (with Quest A Kingdom Divided completed",
                    description: ")"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Cast Resurrect Greater Zombie on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Cast Shadow Blitz whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Cast Spin Flax on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Cast Tele Group Barbarian on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Wield purging staves (with Attack 50 and Quest While Guthix Sleeps completed)"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Cast Superglass Make on the Lunar spellbook"
                },
                {
                    itemId: 26243,
                    level: 78,
                    name: "Wear Virtus robe top (with Defence 75)"
                },
                {
                    itemId: 12899,
                    level: 78,
                    name: "Wield trident of the Swamp"
                },
                {
                    itemId: -1,
                    level: 78,
                    name: "Cast Resurrect Crops on the Arceuus spellbook"
                },
                {
                    itemId: 12777,
                    level: 78,
                    name: "Cast Dareeyak Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: 24957,
                    level: 78,
                    name: "Cast Khazard Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 78,
                    name: "Cast Tan Leather on the Lunar spellbook (with Diary Hard Fremennik Diary completed)"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Cast Entangle on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Cast Undead Grasp on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Cast Tele Group Khazard on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 79,
                    name: "Cast Dream on the Lunar spellbook (with Quest Dream Mentor completed)"
                },
                {
                    itemId: 21006,
                    level: 80,
                    name: "Wield kodai wands"
                },
                {
                    itemId: 25985,
                    level: 80,
                    name: "Wield Elidinis' ward (with Defence 80 and Prayer)"
                },
                {
                    itemId: 25985,
                    level: 80,
                    name: "Wield Elidinis' ward (f) (with Defence 80 and Prayer)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wield tecu salamanders (with Attack 80 and Ranged 80)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wield soulflame horns"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wear Avernic treads and its maxed variants (with Defence 80, Strength 80, and Ranged 80)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Cast Charge on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Cast Stun on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Cast Death Charge on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Cast Blood Blitz whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Cast String Jewellery on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 81,
                    name: "Cast Stat Restore Pot Share on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 81,
                    name: "Cast Wind Surge on the standard spellbook"
                },
                {
                    itemId: 24425,
                    level: 82,
                    name: "Wield the Eldritch Nightmare staff (with Hitpoints 50)"
                },
                {
                    itemId: 24423,
                    level: 82,
                    name: "Wield the Harmonised Nightmare staff (with Hitpoints 50)"
                },
                {
                    itemId: 24424,
                    level: 82,
                    name: "Wield the Volatile Nightmare staff (with Hitpoints 50)"
                },
                {
                    itemId: 22323,
                    level: 82,
                    name: "Wield Sanguinesti staves"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Cast Teleother Falador on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Cast Dark Demonbane on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Cast Ice Blitz whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Cast Magic Imbue on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Wield the Eye of Ayak"
                },
                {
                    itemId: 19629,
                    level: 83,
                    name: "Cast Barrows Teleport on the Arceuus spellbook (with Quest Priest in Peril completed)"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Cast Fertile Soil on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Required to complete Diary Elite Morytania Diary"
                },
                {
                    itemId: -1,
                    level: 84,
                    name: "Cast Demonic Offering on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 84,
                    name: "Cast Carrallanger Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 84,
                    name: "Cast Boost Potion Share on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Cast Water Surge on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Cast Greater Corruption on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: 24959,
                    level: 85,
                    name: "Cast Fishing Guild Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Cast Teleport to Target (after consuming a Target teleport scroll)"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Wield Tumeken's shadow"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Hit up to 22 base damage with Wind Surge"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Cast Plank Make on the Lunar spellbook (with Quest Dream Mentor completed)"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Cast Smoke Barrage whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Cast Tele Group Fishing Guild on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Required to complete Diary Elite Varrock Diary"
                },
                {
                    itemId: 24961,
                    level: 87,
                    name: "Cast Catherby Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 87,
                    name: "Cast Enchant Crossbow Bolt on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 87,
                    name: "Cast Lvl-6 Enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 87,
                    name: "Required to complete Diary Elite Kandarin Diary"
                },
                {
                    itemId: -1,
                    level: 88,
                    name: "Cast Shadow Barrage whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 88,
                    name: "Cast Tele Group Catherby on the Lunar spellbook"
                },
                {
                    itemId: 24963,
                    level: 89,
                    name: "Cast Ice Plateau Teleport on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 89,
                    name: "Cast Recharge Dragonstone on the Lunar spellbook (with Diary Hard Fremennik Diary completed)"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Cast Earth Surge on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Cast Teleother Camelot on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Cast Master Reanimation on the Arceuus spellbook"
                }
            ]
        },
        {
            label: "Members 4",
            entries: [
                {
                    itemId: 19631,
                    level: 90,
                    name: "Cast Ape Atoll Teleport on the Arceuus spellbook (with Quest Monkey Madness I and Daero's traini",
                    description: "ng completed)"
                },
                {
                    itemId: 12775,
                    level: 90,
                    name: "Cast Annakarl Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Cast Tele Group Ice Plateau on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Hit up to 23 base damage with Wind Surge and Water Surge"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Craft ancient rings (with Crafting 80)"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Required to complete Diary Elite Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 91,
                    name: "Cast Energy Transfer on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Cast Sinister Offering on the Arceuus spellbook (with Quest A Kingdom Divided completed)"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Cast Blood Barrage whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Cast Heal Other on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 93,
                    name: "Cast Lvl-7 Enchant on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 93,
                    name: "Cast Vengeance Other on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Cast Ice Barrage whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Cast Vengeance on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Required to complete Diary Elite Ardougne Diary"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Required to complete Diary Elite Desert Diary"
                },
                {
                    itemId: -1,
                    level: 95,
                    name: "Cast Fire Surge on the standard spellbook"
                },
                {
                    itemId: -1,
                    level: 95,
                    name: "Cast Heal Group on the Lunar spellbook"
                },
                {
                    itemId: -1,
                    level: 95,
                    name: "Hit up to 24 base damage with Wind Surge, Water Surge, and Earth Surge"
                },
                {
                    itemId: 12778,
                    level: 96,
                    name: "Cast Ghorrock Teleport whilst on Ancient Magicks"
                },
                {
                    itemId: -1,
                    level: 96,
                    name: "Cast Spellbook Swap on the Lunar spellbook (with Quest Dream Mentor completed)"
                },
                {
                    itemId: -1,
                    level: 96,
                    name: "Required to complete Diary Elite Wilderness Diary"
                },
                {
                    itemId: 9762,
                    level: 99,
                    name: "Buy the magic cape and hood from Wizard Sinina in the Wizards' Guild, and wear them"
                }
            ]
        }
    ]
};
