// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Ranged/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const rangedSkillGuide: SkillGuideData = {
    skillId: SkillId.Ranged,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level in Ranged slightly increases the accuracy and maximum damage of a player's ranged att",
                    description: "acks"
                },
                {
                    itemId: 9705,
                    level: 1,
                    name: "Wield training bows"
                },
                {
                    itemId: 50,
                    level: 1,
                    name: "Wield shortbows"
                },
                {
                    itemId: 48,
                    level: 1,
                    name: "Wield longbows"
                },
                {
                    itemId: 837,
                    level: 1,
                    name: "Wield crossbows"
                },
                {
                    itemId: 767,
                    level: 1,
                    name: "Wield Phoenix crossbows"
                },
                {
                    itemId: 54,
                    level: 5,
                    name: "Wield oak shortbows"
                },
                {
                    itemId: 56,
                    level: 5,
                    name: "Wield oak longbows"
                },
                {
                    itemId: 1169,
                    level: 20,
                    name: "Wear coifs"
                },
                {
                    itemId: 1133,
                    level: 20,
                    name: "Wear studded bodies (with Defence 20)"
                },
                {
                    itemId: 1097,
                    level: 20,
                    name: "Wear studded chaps"
                },
                {
                    itemId: 60,
                    level: 20,
                    name: "Wield willow shortbows"
                },
                {
                    itemId: 58,
                    level: 20,
                    name: "Wield willow longbows"
                },
                {
                    itemId: 10280,
                    level: 20,
                    name: "Wield willow comp bows"
                },
                {
                    itemId: 64,
                    level: 30,
                    name: "Wield maple shortbows"
                },
                {
                    itemId: 62,
                    level: 30,
                    name: "Wield maple longbows"
                },
                {
                    itemId: 1135,
                    level: 40,
                    name: "Wear Green d'hide body (with Defence 40 and Quest Dragon Slayer I completed for the green d'hide",
                    description: " body)"
                },
                {
                    itemId: 23264,
                    level: 40,
                    name: "Wear Gilded d'hide body (with Defence 40 and Quest Dragon Slayer I completed for the gilded d'hi",
                    description: "de body)"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        },
        {
            label: "Members 1",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Use Bronze cannon icons (with Sailing 28)"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Use Iron cannon icons (with Sailing 35)"
                },
                {
                    itemId: 9174,
                    level: 1,
                    name: "Wield bronze crossbows"
                },
                {
                    itemId: 806,
                    level: 1,
                    name: "Wield bronze darts"
                },
                {
                    itemId: 864,
                    level: 1,
                    name: "Wield bronze knives"
                },
                {
                    itemId: 800,
                    level: 1,
                    name: "Wield bronze thrownaxes"
                },
                {
                    itemId: 807,
                    level: 1,
                    name: "Wield iron darts"
                },
                {
                    itemId: 863,
                    level: 1,
                    name: "Wield iron knives"
                },
                {
                    itemId: 801,
                    level: 1,
                    name: "Wield iron thrownaxes"
                },
                {
                    itemId: -1,
                    level: 5,
                    name: "Use Steel cannon icons (with Sailing 47)"
                },
                {
                    itemId: 808,
                    level: 5,
                    name: "Wield steel darts"
                },
                {
                    itemId: 865,
                    level: 5,
                    name: "Wield steel knives"
                },
                {
                    itemId: 802,
                    level: 5,
                    name: "Wield steel thrownaxes"
                },
                {
                    itemId: 3093,
                    level: 10,
                    name: "Wield black darts"
                },
                {
                    itemId: 869,
                    level: 10,
                    name: "Wield black knives"
                },
                {
                    itemId: 9176,
                    level: 16,
                    name: "Wield blurite crossbows (with Quest The Knight's Sword completed)"
                },
                {
                    itemId: 9418,
                    level: 19,
                    name: "Access wall (north wall of Falador) shortcut (requires grappling, Strength 37, and Agility 11)"
                },
                {
                    itemId: -1,
                    level: 19,
                    name: "Required to complete Diary Medium Falador Diary"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Use Mithril cannon icons (with Sailing 57)"
                },
                {
                    itemId: 809,
                    level: 20,
                    name: "Wield mithril darts"
                },
                {
                    itemId: 866,
                    level: 20,
                    name: "Wield mithril knives"
                },
                {
                    itemId: 803,
                    level: 20,
                    name: "Wield mithril thrownaxes"
                },
                {
                    itemId: 22269,
                    level: 20,
                    name: "Wield hard leather shields (with Defence 10)"
                },
                {
                    itemId: 9418,
                    level: 21,
                    name: "Access wall (south-west wall of Yanille) shortcut (requires grappling, Strength 38, and Agility ",
                    description: "39)"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Required to complete Diary Medium Ardougne Diary"
                },
                {
                    itemId: 10954,
                    level: 25,
                    name: "Wear Frog-leather body (with Defence 25)"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Required for Quest Underground Pass"
                },
                {
                    itemId: 9177,
                    level: 26,
                    name: "Wield iron crossbows"
                },
                {
                    itemId: 8880,
                    level: 28,
                    name: "Wield Dorgeshuun crossbows"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Use Adamant cannon icons (with Sailing 69)"
                },
                {
                    itemId: 10498,
                    level: 30,
                    name: "Wear Ava's attractors (with Quest Animal Magnetism completed)"
                },
                {
                    itemId: 6322,
                    level: 30,
                    name: "Wear Snakeskin body (with Defence 30)"
                },
                {
                    itemId: 2883,
                    level: 30,
                    name: "Wield ogre bows (with partial completion of Quest Big Chompy Bird Hunting)"
                },
                {
                    itemId: 4827,
                    level: 30,
                    name: "Wield comp ogre bows (with partial completion of Quest Zogre Flesh Eaters)"
                },
                {
                    itemId: 810,
                    level: 30,
                    name: "Wield adamant darts"
                },
                {
                    itemId: 867,
                    level: 30,
                    name: "Wield adamant knives"
                },
                {
                    itemId: 804,
                    level: 30,
                    name: "Wield adamant thrownaxes"
                },
                {
                    itemId: 10149,
                    level: 30,
                    name: "Wield swamp lizards (with Attack 30 and Magic 30)"
                },
                {
                    itemId: 22272,
                    level: 30,
                    name: "Wield snakeskin shields (with Defence 30)"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required for Quest Animal Magnetism"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required for Quest Big Chompy Bird Hunting"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required for Quest Zogre Flesh Eaters"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required to complete Diary Easy Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required to complete Diary Medium Western Provinces Diary"
                },
                {
                    itemId: 9179,
                    level: 31,
                    name: "Wield steel crossbows"
                },
                {
                    itemId: 9418,
                    level: 35,
                    name: "Access rock (east Catherby) shortcut (requires grappling, Strength 35, and Agility 32)"
                },
                {
                    itemId: 9461,
                    level: 36,
                    name: "Wield mithril crossbows"
                },
                {
                    itemId: 9418,
                    level: 37,
                    name: "Access broken raft (south of Lumbridge) shortcut (requires grappling, Strength 19, and Agility 8",
                    description: ")"
                },
                {
                    itemId: -1,
                    level: 37,
                    name: "Required for Quest Spirits of the Elid"
                },
                {
                    itemId: 9418,
                    level: 39,
                    name: "Access rock (Taverley Dungeon) shortcut (requires grappling, Strength 22, and Agility 36)"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Access to the Ranging Guild"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Use Rune cannon icons (with Sailing 80)"
                },
                {
                    itemId: 6133,
                    level: 40,
                    name: "Wear spined armour (with Defence 40)"
                },
                {
                    itemId: 2581,
                    level: 40,
                    name: "Wear Robin hood hats"
                },
                {
                    itemId: 12596,
                    level: 40,
                    name: "Wear rangers' tunics"
                },
                {
                    itemId: 23249,
                    level: 40,
                    name: "Wear rangers' tights"
                },
                {
                    itemId: 19994,
                    level: 40,
                    name: "Wear ranger gloves"
                },
                {
                    itemId: 2577,
                    level: 40,
                    name: "Wear ranger boots"
                },
                {
                    itemId: 68,
                    level: 40,
                    name: "Wield yew shortbows"
                },
                {
                    itemId: 66,
                    level: 40,
                    name: "Wield yew longbows"
                },
                {
                    itemId: 10282,
                    level: 40,
                    name: "Wield yew comp bows"
                },
                {
                    itemId: 811,
                    level: 40,
                    name: "Wield rune darts"
                },
                {
                    itemId: 868,
                    level: 40,
                    name: "Wield rune knives"
                },
                {
                    itemId: 805,
                    level: 40,
                    name: "Wield rune thrownaxes"
                },
                {
                    itemId: 22275,
                    level: 40,
                    name: "Wield green d'hide shields (with Defence 40)"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Required for Quest Cabin Fever"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Required for Quest Temple of Ikov"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Required to complete Diary Medium Kandarin Diary"
                },
                {
                    itemId: 9418,
                    level: 42,
                    name: "Access rock (south of volcano area on Karamja) shortcut (requires grappling, Strength 21, and Ag",
                    description: "ility 53)"
                },
                {
                    itemId: 8839,
                    level: 42,
                    name: "Wear Void knight top (with Attack 42, Strength, Magic, Defence, Hitpoints, and Prayer 22)"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Required to complete Diary Elite Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Required to complete Diary Hard Karamja Diary"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Wield camphor blowpipes"
                },
                {
                    itemId: 9976,
                    level: 45,
                    name: "Wield chinchompas"
                },
                {
                    itemId: 9183,
                    level: 46,
                    name: "Wield adamant crossbows"
                },
                {
                    itemId: -1,
                    level: 47,
                    name: "Required for Quest The Path of Glouphrie"
                },
                {
                    itemId: 10499,
                    level: 50,
                    name: "Wear Ava's accumulators (with Quest Animal Magnetism completed)"
                },
                {
                    itemId: 2499,
                    level: 50,
                    name: "Wear blue d'hide body (with Defence 40 for the body)"
                },
                {
                    itemId: 72,
                    level: 50,
                    name: "Wield magic shortbows"
                },
                {
                    itemId: 70,
                    level: 50,
                    name: "Wield magic longbows"
                },
                {
                    itemId: 10284,
                    level: 50,
                    name: "Wield magic comp bows"
                },
                {
                    itemId: 6724,
                    level: 50,
                    name: "Wield seerculls"
                },
                {
                    itemId: 10156,
                    level: 50,
                    name: "Wield hunters' crossbows"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Wield bone shortbows"
                },
                {
                    itemId: 4150,
                    level: 50,
                    name: "Wield broad arrows (with Slayer 55)"
                },
                {
                    itemId: 25849,
                    level: 50,
                    name: "Wield amethyst darts"
                },
                {
                    itemId: 10146,
                    level: 50,
                    name: "Wield orange salamanders (with Attack 50 and Magic 50)"
                },
                {
                    itemId: 22278,
                    level: 50,
                    name: "Wield blue d'hide shields (with Defence 40)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required to complete Diary Medium Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Wield ironwood blowpipes"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: 9977,
                    level: 55,
                    name: "Wield red chinchompas"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Wield hunter's spears (with Strength 30)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Use Dragon cannon icons (with Sailing 92)"
                },
                {
                    itemId: 2501,
                    level: 60,
                    name: "Wear Red d'hide body (with Defence 40 for the body)"
                },
                {
                    itemId: 10555,
                    level: 60,
                    name: "Wear penance skirts (with Defence 40, 375 Honour points in each role, and killed the Penance Que",
                    description: "en in Minigame Barbarian Assault)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Wear Mixed hide top (with Defence 50)"
                },
                {
                    itemId: 11235,
                    level: 60,
                    name: "Wield dark bows"
                },
                {
                    itemId: 22547,
                    level: 60,
                    name: "Wield Craw's bows"
                },
                {
                    itemId: 11230,
                    level: 60,
                    name: "Wield dragon darts"
                },
                {
                    itemId: 22804,
                    level: 60,
                    name: "Wield dragon knives"
                },
                {
                    itemId: 6522,
                    level: 60,
                    name: "Wield toktz-xil-uls"
                },
                {
                    itemId: 10147,
                    level: 60,
                    name: "Wield red salamanders (with Attack 60 and Magic 60)"
                },
                {
                    itemId: 22281,
                    level: 60,
                    name: "Wield red d'hide shields (with Defence 40)"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Wield aquanite hoppers"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Required for Quest Mourning's End Part I"
                },
                {
                    itemId: 9185,
                    level: 61,
                    name: "Wield rune crossbow"
                },
                {
                    itemId: 11875,
                    level: 61,
                    name: "Wield broad bolts (with Slayer 55)"
                },
                {
                    itemId: 20849,
                    level: 61,
                    name: "Wield dragon thrownaxes"
                },
                {
                    itemId: 9418,
                    level: 62,
                    name: "Attempt pillar grapples in Hallowed Sepulchre"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Required for Quest The Curse of Arrav"
                },
                {
                    itemId: 21902,
                    level: 64,
                    name: "Wield dragon crossbows"
                },
                {
                    itemId: 10330,
                    level: 65,
                    name: "Wear 3rd Age range top (with Defence 45)"
                },
                {
                    itemId: 12424,
                    level: 65,
                    name: "Wield 3rd Age bows"
                },
                {
                    itemId: 11959,
                    level: 65,
                    name: "Wield black chinchompas"
                },
                {
                    itemId: 19478,
                    level: 65,
                    name: "Wield light ballistae"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Wield rosewood blowpipes"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Wield hunters' sunlight crossbows (with Hunter 50)"
                },
                {
                    itemId: 21914,
                    level: 70,
                    name: "Wear Ava's assembler (with Quest Dragon Slayer II completed)"
                },
                {
                    itemId: 2503,
                    level: 70,
                    name: "Wear black d'hide body (with Defence 40 for the body)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Wear Saradomin d'hide body (with Defence 40 for the body, coif, boots and shield)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Wear Hueycoatl hide body (with Defence 40 for the body and coif)"
                },
                {
                    itemId: 4732,
                    level: 70,
                    name: "Wear Karil's coif (with Defence 70)"
                },
                {
                    itemId: 11828,
                    level: 70,
                    name: "Wear Armadyl chestplate (with Defence 70)"
                },
                {
                    itemId: 22951,
                    level: 70,
                    name: "Wear Boots of Brimstone (with Magic 70 and Defence 70)"
                },
                {
                    itemId: 23901,
                    level: 70,
                    name: "Wield crystal bows (with Agility 50 and Quest Roving Elves completed)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Wield webweaver bows"
                },
                {
                    itemId: 4734,
                    level: 70,
                    name: "Wield Karil's crossbow"
                },
                {
                    itemId: 11785,
                    level: 70,
                    name: "Wield Armadyl crossbows"
                },
                {
                    itemId: 21012,
                    level: 70,
                    name: "Wield dragon hunter crossbows"
                },
                {
                    itemId: 10148,
                    level: 70,
                    name: "Wield black salamanders (with Attack 70 and Magic 70)"
                },
                {
                    itemId: 22284,
                    level: 70,
                    name: "Wield black d'hide shields (with Defence 40)"
                },
                {
                    itemId: 22002,
                    level: 70,
                    name: "Wield dragonfire wards (with Defence 75 and partial completion of Quest Dragon Slayer I)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Access Armadyl's Eyrie in the God Wars Dungeon"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Required to complete Diary Elite Fremennik Diary"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Required to complete Diary Elite Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Required to complete Diary Hard Western Provinces Diary"
                },
                {
                    itemId: 13237,
                    level: 75,
                    name: "Wear pegasian boots (with Defence 75)"
                },
                {
                    itemId: 19481,
                    level: 75,
                    name: "Wield heavy ballistae"
                },
                {
                    itemId: 12924,
                    level: 75,
                    name: "Wield toxic blowpipes"
                },
                {
                    itemId: 21000,
                    level: 75,
                    name: "Wield twisted bucklers (with Defence 75)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Wear Eclipse moon chestplate (with Defence 50)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Wield eclipse atlatls (with Attack 50 and Strength 50)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Wear Dizana's quiver"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Wield scorching bows (with Quest While Guthix Sleeps completed)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wear Masori body (with Defence 30)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wear fortified Masori armour (with Defence 80)"
                },
                {
                    itemId: 26235,
                    level: 80,
                    name: "Wear zaryte vambraces (with Defence 45)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wear Avernic treads and its maxed variants (with Defence 80, Strength 80, and Magic 80)"
                },
                {
                    itemId: 25862,
                    level: 80,
                    name: "Wield bows of Faerdhinen (with Agility 70)"
                },
                {
                    itemId: 26374,
                    level: 80,
                    name: "Wield zaryte crossbows"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wield venator bows"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Wield tecu salamanders (with Attack 80 and Magic 80)"
                },
                {
                    itemId: 20997,
                    level: 85,
                    name: "Wield twisted bows"
                },
                {
                    itemId: 9756,
                    level: 99,
                    name: "Buy the Ranging cape and hood from Armour salesman in the Ranging Guild, and wear them"
                }
            ]
        }
    ]
};
