// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Runecraft/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const runecraftSkillGuide: SkillGuideData = {
    skillId: SkillId.Runecraft,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: 556,
                    level: 1,
                    name: "Craft air runes and create air tiaras at the Air Altar"
                },
                {
                    itemId: 5529,
                    level: 1,
                    name: "Create mind tiaras at the Mind Altar"
                },
                {
                    itemId: 5531,
                    level: 1,
                    name: "Create water tiaras at the Water Altar"
                },
                {
                    itemId: 5535,
                    level: 1,
                    name: "Create earth tiaras at the Earth Altar"
                },
                {
                    itemId: 5537,
                    level: 1,
                    name: "Create fire tiaras at the Fire Altar"
                },
                {
                    itemId: 5533,
                    level: 1,
                    name: "Create body tiaras at the Body Altar"
                },
                {
                    itemId: 558,
                    level: 2,
                    name: "Craft mind runes at the Mind Altar"
                },
                {
                    itemId: 555,
                    level: 5,
                    name: "Craft water runes at the Water Altar"
                },
                {
                    itemId: 557,
                    level: 9,
                    name: "Craft earth runes at the Earth Altar"
                },
                {
                    itemId: 556,
                    level: 11,
                    name: "Craft 2 air runes per essence"
                },
                {
                    itemId: 554,
                    level: 14,
                    name: "Craft fire runes at the Fire Altar"
                },
                {
                    itemId: 558,
                    level: 14,
                    name: "Craft 2 mind runes per essence"
                },
                {
                    itemId: 555,
                    level: 19,
                    name: "Craft 2 water runes per essence"
                },
                {
                    itemId: 559,
                    level: 20,
                    name: "Craft body runes at the Body Altar"
                },
                {
                    itemId: 556,
                    level: 22,
                    name: "Craft 3 air runes per essence"
                },
                {
                    itemId: 557,
                    level: 26,
                    name: "Craft 2 earth runes per essence"
                },
                {
                    itemId: 558,
                    level: 28,
                    name: "Craft 3 mind runes per essence"
                },
                {
                    itemId: 556,
                    level: 33,
                    name: "Craft 4 air runes per essence"
                },
                {
                    itemId: 554,
                    level: 35,
                    name: "Craft 2 fire runes per essence"
                },
                {
                    itemId: 555,
                    level: 38,
                    name: "Craft 3 water runes per essence"
                },
                {
                    itemId: 558,
                    level: 42,
                    name: "Craft 4 mind runes per essence"
                },
                {
                    itemId: 556,
                    level: 44,
                    name: "Craft 5 air runes per essence"
                },
                {
                    itemId: 559,
                    level: 46,
                    name: "Craft 2 body runes per essence"
                },
                {
                    itemId: 557,
                    level: 52,
                    name: "Craft 3 earth runes per essence"
                },
                {
                    itemId: 556,
                    level: 55,
                    name: "Craft 6 air runes per essence"
                },
                {
                    itemId: 558,
                    level: 56,
                    name: "Craft 5 mind runes per essence"
                },
                {
                    itemId: 555,
                    level: 57,
                    name: "Craft 4 water runes per essence"
                },
                {
                    itemId: 556,
                    level: 66,
                    name: "Craft 7 air runes per essence"
                },
                {
                    itemId: 558,
                    level: 70,
                    name: "Craft 6 mind runes per essence"
                },
                {
                    itemId: 554,
                    level: 70,
                    name: "Craft 3 fire runes per essence"
                },
                {
                    itemId: 555,
                    level: 76,
                    name: "Craft 5 water runes per essence"
                },
                {
                    itemId: 556,
                    level: 77,
                    name: "Craft 8 air runes per essence"
                },
                {
                    itemId: 557,
                    level: 78,
                    name: "Craft 4 earth runes per essence"
                },
                {
                    itemId: 558,
                    level: 84,
                    name: "Craft 7 mind runes per essence"
                },
                {
                    itemId: 556,
                    level: 88,
                    name: "Craft 9 air runes per essence"
                },
                {
                    itemId: 559,
                    level: 92,
                    name: "Craft 3 body runes per essence"
                },
                {
                    itemId: 555,
                    level: 95,
                    name: "Craft 6 water runes per essence"
                },
                {
                    itemId: 558,
                    level: 98,
                    name: "Craft 8 mind runes per essence"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                },
                {
                    itemId: 556,
                    level: 99,
                    name: "Craft 10 air runes per essence"
                }
            ]
        },
        {
            label: "Members",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Craft runes at the Ourania Altar"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Create elemental tiaras at elemental altars"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Create catalytic tiaras at catalytic altars"
                },
                {
                    itemId: 5543,
                    level: 1,
                    name: "Create chaos tiaras at the Chaos Altar"
                },
                {
                    itemId: 5541,
                    level: 1,
                    name: "Create nature tiaras at the Nature Altar"
                },
                {
                    itemId: 13446,
                    level: 1,
                    name: "Create dark essence blocks"
                },
                {
                    itemId: 5509,
                    level: 1,
                    name: "Store essence in small pouches"
                },
                {
                    itemId: 4695,
                    level: 6,
                    name: "Craft mist runes at the Air or Water Altar"
                },
                {
                    itemId: 4696,
                    level: 10,
                    name: "Craft dust runes at the Air or Earth Altar"
                },
                {
                    itemId: 4698,
                    level: 13,
                    name: "Craft mud runes at the Earth or Water Altar"
                },
                {
                    itemId: -1,
                    level: 14,
                    name: "Build a (with Construction 41)"
                },
                {
                    itemId: 4697,
                    level: 15,
                    name: "Craft smoke runes at the Air or Fire Altar"
                },
                {
                    itemId: 4694,
                    level: 19,
                    name: "Craft steam runes at the Fire or Water Altar"
                },
                {
                    itemId: 4699,
                    level: 23,
                    name: "Craft lava runes at the Fire or Earth Altar"
                },
                {
                    itemId: 5510,
                    level: 25,
                    name: "Store essence in medium pouches"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Craft and store 8 essence in the colossal pouch (with Crafting 56)"
                },
                {
                    itemId: -1,
                    level: 33,
                    name: "Craft sunfire runes at a Shrine of Ralos"
                },
                {
                    itemId: 562,
                    level: 35,
                    name: "Craft chaos runes at the Chaos Altar"
                },
                {
                    itemId: 3391,
                    level: 42,
                    name: "Infuse splitbark gauntlets into swampbark gauntlets at the Nature Altar (after reading a runescr",
                    description: "oll of swampbark)"
                },
                {
                    itemId: 3393,
                    level: 42,
                    name: "Infuse splitbark boots into swampbark boots at the Nature Altar (after reading a runescroll of s",
                    description: "wampbark)"
                },
                {
                    itemId: 561,
                    level: 44,
                    name: "Craft nature runes at the Nature Altar"
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Build a (with Construction 41)"
                },
                {
                    itemId: 3385,
                    level: 46,
                    name: "Infuse splitbark helms into swampbark helms at the Nature Altar (after reading a runescroll of s",
                    description: "wampbark)"
                },
                {
                    itemId: 3387,
                    level: 48,
                    name: "Infuse splitbark bodies into swampbark bodies at the Nature Altar (after reading a runescroll of",
                    description: " swampbark)"
                },
                {
                    itemId: 3389,
                    level: 48,
                    name: "Infuse splitbark legs into swampbark legs at the Nature Altar (after reading a runescroll of swa",
                    description: "mpbark)"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Craft 2 sunfire runes per essence"
                },
                {
                    itemId: 5512,
                    level: 50,
                    name: "Store essence in large pouches"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Store 16 essence in the colossal pouch"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Reinvigorate desiccated pages into burnt pages at the Book of Eternal Flame"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Reinvigorate desiccated pages into soaked pages at the Book of Storms"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Reinvigorate desiccated pages into soiled pages at the Book of Earthen Might"
                },
                {
                    itemId: 564,
                    level: 59,
                    name: "Craft 2 cosmic runes per essence"
                },
                {
                    itemId: 11840,
                    level: 60,
                    name: "Infuse dragon boots into primordial boots (with Magic 60)"
                },
                {
                    itemId: 6920,
                    level: 60,
                    name: "Infuse infinity boots into eternal boots (with Magic 60)"
                },
                {
                    itemId: 2577,
                    level: 60,
                    name: "Infuse ranger boots into pegasian boots (with Magic 60)"
                },
                {
                    itemId: 562,
                    level: 74,
                    name: "Craft 2 chaos runes per essence"
                },
                {
                    itemId: 5514,
                    level: 75,
                    name: "Store essence in giant pouches"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Store 27 essence in the colossal pouch"
                },
                {
                    itemId: 3391,
                    level: 77,
                    name: "Infuse splitbark gauntlets into bloodbark gauntlets at the Blood Altar or Kourend's Blood Altar ",
                    description: "(after reading a runescroll of bloodbark)"
                },
                {
                    itemId: 3393,
                    level: 77,
                    name: "Infuse splitbark boots into bloodbark boots at the Blood Altar or Kourend's Blood Altar (after r",
                    description: "eading a runescroll of bloodbark)"
                },
                {
                    itemId: 3385,
                    level: 79,
                    name: "Infuse splitbark helms into bloodbark helms at the Blood Altar or Kourend's Blood Altar (after r",
                    description: "eading a runescroll of bloodbark)"
                },
                {
                    itemId: 3387,
                    level: 81,
                    name: "Infuse splitbark bodies into bloodbark bodies at the Blood Altar or Kourend's Blood Altar (after",
                    description: " reading a runescroll of bloodbark)"
                },
                {
                    itemId: 3389,
                    level: 81,
                    name: "Infuse splitbark legs into bloodbark legs at the Blood Altar or Kourend's Blood Altar (after rea",
                    description: "ding a runescroll of bloodbark)"
                },
                {
                    itemId: 9075,
                    level: 82,
                    name: "Craft 2 astral runes per essence"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Store 40 essence in the colossal pouch"
                },
                {
                    itemId: 566,
                    level: 90,
                    name: "Craft soul runes at the Soul Altar"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Craft aether runes at the Cosmic Altar"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Build a (with Construction 41)"
                },
                {
                    itemId: 561,
                    level: 91,
                    name: "Craft 2 nature runes per essence"
                },
                {
                    itemId: 563,
                    level: 95,
                    name: "Craft 2 law runes per essence"
                },
                {
                    itemId: -1,
                    level: 98,
                    name: "Craft 3 sunfire runes per essence"
                }
            ]
        }
    ]
};
