// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Slayer/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const slayerSkillGuide: SkillGuideData = {
    skillId: SkillId.Slayer,
    tabs: [
        {
            label: "Members",
            entries: [
                {
                    itemId: 4155,
                    level: 1,
                    name: "Use enchanted gems"
                },
                {
                    itemId: 4551,
                    level: 1,
                    name: "Wear spiny helmets (with Defence 5)"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Receive Slayer assignments from Turael in Burthorpe"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Receive Wilderness Slayer assignments from Krystilia in Edgeville"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Receive Slayer assignments from Mazchna in Canifis (with Combat 20)"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Receive Slayer assignments from Vannaka in Edgeville Dungeon (with Combat 40)"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Receive Slayer assignments from Konar quo Maten in Mount Karuulm (with Combat 75)"
                },
                {
                    itemId: -1,
                    level: 7,
                    name: "Slay Cave bug icons"
                },
                {
                    itemId: 4164,
                    level: 10,
                    name: "Wear facemasks"
                },
                {
                    itemId: -1,
                    level: 10,
                    name: "Slay Cave crawler icons"
                },
                {
                    itemId: 4166,
                    level: 15,
                    name: "Wear earmuffs"
                },
                {
                    itemId: -1,
                    level: 17,
                    name: "Slay Cave slime icons"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Slay Rockslug icons"
                },
                {
                    itemId: -1,
                    level: 22,
                    name: "Slay desert lizards"
                },
                {
                    itemId: 4156,
                    level: 25,
                    name: "Wield mirror shields (with Defence 20)"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Slay Cockatrice icons"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Slay Pyrefiend icons"
                },
                {
                    itemId: 7053,
                    level: 33,
                    name: "Wield Lit bug lanterns"
                },
                {
                    itemId: -1,
                    level: 33,
                    name: "Slay Harpie Bug Swarm icons"
                },
                {
                    itemId: 11864,
                    level: 35,
                    name: "Wear Slayer helmets (with Crafting 55 and unlocking the ability to assemble with 400 Slayer rewa",
                    description: "rd points)"
                },
                {
                    itemId: 8923,
                    level: 35,
                    name: "Wear witchwood icons"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Slay Wall beast icons"
                },
                {
                    itemId: 7159,
                    level: 37,
                    name: "Wear insulated boots"
                },
                {
                    itemId: -1,
                    level: 37,
                    name: "Slay Killerwatt icons"
                },
                {
                    itemId: 10952,
                    level: 39,
                    name: "Use Slayer bells"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Slay Molanisk icons"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Slay Basilisk icons"
                },
                {
                    itemId: 6708,
                    level: 42,
                    name: "Wear Slayer gloves"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Slay Fever spider icons"
                },
                {
                    itemId: 23037,
                    level: 44,
                    name: "Wear boots of stone"
                },
                {
                    itemId: 22951,
                    level: 44,
                    name: "Wear Boots of Brimstone"
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Slay Sulphur Lizard icons and grimy lizards"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Slay Infernal Mage icons"
                },
                {
                    itemId: -1,
                    level: 48,
                    name: "Slay Lesser nagua icon"
                },
                {
                    itemId: -1,
                    level: 48,
                    name: "Slay Lesser nagua icon"
                },
                {
                    itemId: -1,
                    level: 48,
                    name: "Slay Lesser nagua icon"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Slay Bloodveld icon"
                },
                {
                    itemId: -1,
                    level: 52,
                    name: "Slay jellies"
                },
                {
                    itemId: -1,
                    level: 54,
                    name: "Slay s"
                },
                {
                    itemId: 4158,
                    level: 55,
                    name: "Wield leaf-bladed spears, leaf-bladed swords, and leaf-bladed battleaxes (with Attack 50)"
                },
                {
                    itemId: 4150,
                    level: 55,
                    name: "Wield broad arrows and broad bolts (with Ranged 50)"
                },
                {
                    itemId: 4170,
                    level: 55,
                    name: "Wield Slayer's staves (with Magic 50)"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Cast Magic Dart (with Magic 50)"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Slay Turoth icons"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Slay Mutated zygomite icons"
                },
                {
                    itemId: -1,
                    level: 58,
                    name: "Slay Cave horror icons (with a witchwood icon equipped)"
                },
                {
                    itemId: 4168,
                    level: 60,
                    name: "Wear nose pegs"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Slay Aberrant spectre icons"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Slay Basilisk Knight icons"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Slay Wyrm icons"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Slay lava strykewyrms (with Sailing 60)"
                },
                {
                    itemId: -1,
                    level: 63,
                    name: "Slay Spiritual ranger icons"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Wield Amethyst broad bolts 5"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Slay Dust devil icons"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Slay Fossil Island wyverns icons"
                },
                {
                    itemId: -1,
                    level: 67,
                    name: "Slay s"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Slay Spiritual warrior icons"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Slay Kurask icons"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Slay Skeletal Wyvern icons"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Slay Venator slayer icons"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Slay Gargoyle icons and the Grotesque Guardians boss"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Slay s"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Slay Brutal black dragon icons"
                },
                {
                    itemId: -1,
                    level: 78,
                    name: "Slay Aquanite icon"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Slay Nechryael icon"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Slay Ancient Wyvern icons"
                },
                {
                    itemId: -1,
                    level: 83,
                    name: "Slay Spiritual mage icons"
                },
                {
                    itemId: -1,
                    level: 84,
                    name: "Slay Drake icons"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Slay Abyssal demon icons and the Abyssal Sire boss"
                },
                {
                    itemId: -1,
                    level: 87,
                    name: "Slay Cave kraken icons and the Kraken boss"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Slay Dark beast icons"
                },
                {
                    itemId: -1,
                    level: 91,
                    name: "Slay Cerberus icon"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Slay Araxyte icon and the Araxyte icon boss"
                },
                {
                    itemId: -1,
                    level: 93,
                    name: "Slay Smoke devil icons and the thermonuclear smoke devil boss"
                },
                {
                    itemId: -1,
                    level: 95,
                    name: "Slay Hydra icons and the Alchemical Hydra boss"
                },
                {
                    itemId: -1,
                    level: 95,
                    name: "Required to complete Grandmaster Combat Achievements"
                },
                {
                    itemId: 9786,
                    level: 99,
                    name: "Buy the Slayer cape and hood from Duradel or Kuradal in Shilo Village, and wear them"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        }
    ]
};
