// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Smithing/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const smithingSkillGuide: SkillGuideData = {
    skillId: SkillId.Smithing,
    tabs: [
        {
            label: "Free-to-play 1",
            entries: [
                {
                    itemId: 2349,
                    level: 1,
                    name: "Smelt bronze bars"
                },
                {
                    itemId: 1351,
                    level: 1,
                    name: "Smith bronze axes"
                },
                {
                    itemId: 1205,
                    level: 1,
                    name: "Smith bronze daggers"
                },
                {
                    itemId: 1422,
                    level: 2,
                    name: "Smith bronze maces"
                },
                {
                    itemId: 1139,
                    level: 3,
                    name: "Smith bronze med helms"
                },
                {
                    itemId: 1277,
                    level: 4,
                    name: "Smith bronze swords"
                },
                {
                    itemId: 1321,
                    level: 5,
                    name: "Smith bronze scimitars"
                },
                {
                    itemId: 1291,
                    level: 6,
                    name: "Smith bronze longswords"
                },
                {
                    itemId: 1155,
                    level: 7,
                    name: "Smith bronze full helms"
                },
                {
                    itemId: 1173,
                    level: 8,
                    name: "Smith bronze sq shields"
                },
                {
                    itemId: 1337,
                    level: 9,
                    name: "Smith bronze warhammers"
                },
                {
                    itemId: 1375,
                    level: 10,
                    name: "Smith bronze battleaxes"
                },
                {
                    itemId: 1103,
                    level: 11,
                    name: "Smith bronze chainbodies"
                },
                {
                    itemId: 1189,
                    level: 12,
                    name: "Smith bronze kiteshields"
                },
                {
                    itemId: 1307,
                    level: 14,
                    name: "Smith bronze 2h swords"
                },
                {
                    itemId: 2351,
                    level: 15,
                    name: "Smelt iron bars (50% success rate unless wearing a ring of forging)"
                },
                {
                    itemId: 1203,
                    level: 15,
                    name: "Smith iron daggers"
                },
                {
                    itemId: 1075,
                    level: 16,
                    name: "Smith bronze platelegs"
                },
                {
                    itemId: 1087,
                    level: 16,
                    name: "Smith bronze plateskirts"
                },
                {
                    itemId: 1349,
                    level: 16,
                    name: "Smith iron axes"
                },
                {
                    itemId: 1420,
                    level: 17,
                    name: "Smith iron maces"
                },
                {
                    itemId: 1117,
                    level: 18,
                    name: "Smith bronze platebodies"
                },
                {
                    itemId: 1137,
                    level: 18,
                    name: "Smith iron med helms"
                },
                {
                    itemId: 1279,
                    level: 19,
                    name: "Smith iron swords"
                },
                {
                    itemId: 2355,
                    level: 20,
                    name: "Smelt silver bars"
                },
                {
                    itemId: 1323,
                    level: 20,
                    name: "Smith iron scimitars"
                },
                {
                    itemId: 1293,
                    level: 21,
                    name: "Smith iron longswords"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "New information is available from the 22574"
                },
                {
                    itemId: 1153,
                    level: 22,
                    name: "Smith iron full helms"
                },
                {
                    itemId: 1175,
                    level: 23,
                    name: "Smith iron sq shields"
                },
                {
                    itemId: 1335,
                    level: 24,
                    name: "Smith iron warhammers"
                },
                {
                    itemId: 1363,
                    level: 25,
                    name: "Smith iron battleaxes"
                },
                {
                    itemId: 1101,
                    level: 26,
                    name: "Smith iron chainbodies"
                },
                {
                    itemId: 1191,
                    level: 27,
                    name: "Smith iron kiteshields"
                },
                {
                    itemId: 1309,
                    level: 29,
                    name: "Smith iron 2h swords"
                },
                {
                    itemId: 2353,
                    level: 30,
                    name: "Smelt steel bars"
                },
                {
                    itemId: 1207,
                    level: 30,
                    name: "Smith steel daggers"
                },
                {
                    itemId: 1067,
                    level: 31,
                    name: "Smith iron platelegs"
                },
                {
                    itemId: 1081,
                    level: 31,
                    name: "Smith iron plateskirts"
                },
                {
                    itemId: 1353,
                    level: 31,
                    name: "Smith steel axes"
                },
                {
                    itemId: 1424,
                    level: 32,
                    name: "Smith steel maces"
                },
                {
                    itemId: 1115,
                    level: 33,
                    name: "Smith iron platebodies"
                },
                {
                    itemId: 1141,
                    level: 33,
                    name: "Smith steel med helms"
                },
                {
                    itemId: 1539,
                    level: 34,
                    name: "Smith steel nails"
                },
                {
                    itemId: 1281,
                    level: 34,
                    name: "Smith steel swords"
                },
                {
                    itemId: 1325,
                    level: 35,
                    name: "Smith steel scimitars"
                },
                {
                    itemId: 1295,
                    level: 36,
                    name: "Smith steel longswords"
                },
                {
                    itemId: 1157,
                    level: 37,
                    name: "Smith steel full helms"
                },
                {
                    itemId: 1177,
                    level: 38,
                    name: "Smith steel sq shields"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "New information is available from the 22574"
                },
                {
                    itemId: 1339,
                    level: 39,
                    name: "Smith steel warhammers"
                },
                {
                    itemId: 2357,
                    level: 40,
                    name: "Smelt gold bars (wearing goldsmith gauntlets will grant higher experience)"
                },
                {
                    itemId: 1365,
                    level: 40,
                    name: "Smith steel battleaxes"
                },
                {
                    itemId: 1105,
                    level: 41,
                    name: "Smith steel chainbodies"
                },
                {
                    itemId: 1193,
                    level: 42,
                    name: "Smith steel kiteshields"
                },
                {
                    itemId: 1311,
                    level: 44,
                    name: "Smith steel 2h swords"
                },
                {
                    itemId: 1069,
                    level: 46,
                    name: "Smith steel platelegs"
                },
                {
                    itemId: 1083,
                    level: 46,
                    name: "Smith steel plateskirts"
                },
                {
                    itemId: 1119,
                    level: 48,
                    name: "Smith steel platebodies"
                },
                {
                    itemId: 2359,
                    level: 50,
                    name: "Smelt mithril bars"
                },
                {
                    itemId: 1209,
                    level: 50,
                    name: "Smith mithril daggers"
                },
                {
                    itemId: 1355,
                    level: 51,
                    name: "Smith mithril axes"
                },
                {
                    itemId: 1428,
                    level: 52,
                    name: "Smith mithril maces"
                },
                {
                    itemId: 1143,
                    level: 53,
                    name: "Smith mithril med helms"
                },
                {
                    itemId: 1285,
                    level: 54,
                    name: "Smith mithril swords"
                },
                {
                    itemId: 1329,
                    level: 55,
                    name: "Smith mithril scimitars"
                },
                {
                    itemId: 1299,
                    level: 56,
                    name: "Smith mithril longswords"
                },
                {
                    itemId: 1159,
                    level: 57,
                    name: "Smith mithril full helms"
                },
                {
                    itemId: 1181,
                    level: 58,
                    name: "Smith mithril sq shields"
                },
                {
                    itemId: 1343,
                    level: 59,
                    name: "Smith mithril warhammers"
                },
                {
                    itemId: 1369,
                    level: 60,
                    name: "Smith mithril battleaxes"
                },
                {
                    itemId: 1109,
                    level: 61,
                    name: "Smith mithril chainbodies"
                },
                {
                    itemId: 1197,
                    level: 62,
                    name: "Smith mithril kiteshields"
                },
                {
                    itemId: 1315,
                    level: 64,
                    name: "Smith mithril 2h swords"
                },
                {
                    itemId: 1071,
                    level: 66,
                    name: "Smith mithril platelegs"
                },
                {
                    itemId: 1085,
                    level: 66,
                    name: "Smith mithril plateskirts"
                },
                {
                    itemId: 1121,
                    level: 68,
                    name: "Smith mithril platebodies"
                },
                {
                    itemId: 2361,
                    level: 70,
                    name: "Smelt adamantite bars"
                },
                {
                    itemId: 1211,
                    level: 70,
                    name: "Smith adamant daggers"
                },
                {
                    itemId: 1357,
                    level: 71,
                    name: "Smith adamant axes"
                },
                {
                    itemId: 1430,
                    level: 72,
                    name: "Smith adamant maces"
                },
                {
                    itemId: 1145,
                    level: 73,
                    name: "Smith adamant med helms"
                },
                {
                    itemId: 1287,
                    level: 74,
                    name: "Smith adamant swords"
                },
                {
                    itemId: 1331,
                    level: 75,
                    name: "Smith adamant scimitars"
                },
                {
                    itemId: 1301,
                    level: 76,
                    name: "Smith adamant longswords"
                },
                {
                    itemId: 1161,
                    level: 77,
                    name: "Smith adamant full helms"
                },
                {
                    itemId: 1183,
                    level: 78,
                    name: "Smith adamant sq shields"
                },
                {
                    itemId: 1345,
                    level: 79,
                    name: "Smith adamant warhammers"
                },
                {
                    itemId: 1371,
                    level: 80,
                    name: "Smith adamant battleaxes"
                },
                {
                    itemId: 1111,
                    level: 81,
                    name: "Smith adamant chainbodies"
                }
            ]
        },
        {
            label: "Free-to-play 2",
            entries: [
                {
                    itemId: 1199,
                    level: 82,
                    name: "Smith adamant kiteshields"
                },
                {
                    itemId: 1317,
                    level: 84,
                    name: "Smith adamant 2h swords"
                },
                {
                    itemId: 2363,
                    level: 85,
                    name: "Smelt runite bars"
                },
                {
                    itemId: 1213,
                    level: 85,
                    name: "Smith rune daggers"
                },
                {
                    itemId: 1073,
                    level: 86,
                    name: "Smith adamant platelegs"
                },
                {
                    itemId: 1091,
                    level: 86,
                    name: "Smith adamant plateskirts"
                },
                {
                    itemId: 1359,
                    level: 86,
                    name: "Smith rune axes"
                },
                {
                    itemId: 1432,
                    level: 87,
                    name: "Smith rune maces"
                },
                {
                    itemId: 1123,
                    level: 88,
                    name: "Smith adamant platebodies"
                },
                {
                    itemId: 1147,
                    level: 88,
                    name: "Smith rune med helms"
                },
                {
                    itemId: 1289,
                    level: 89,
                    name: "Smith rune swords"
                },
                {
                    itemId: 1333,
                    level: 90,
                    name: "Smith rune scimitars"
                },
                {
                    itemId: 1303,
                    level: 91,
                    name: "Smith rune longswords"
                },
                {
                    itemId: 1163,
                    level: 92,
                    name: "Smith rune full helms"
                },
                {
                    itemId: 1185,
                    level: 93,
                    name: "Smith rune sq shields"
                },
                {
                    itemId: 1347,
                    level: 94,
                    name: "Smith rune warhammers"
                },
                {
                    itemId: 1373,
                    level: 95,
                    name: "Smith rune battleaxes"
                },
                {
                    itemId: 1113,
                    level: 96,
                    name: "Smith rune chainbodies"
                },
                {
                    itemId: 1201,
                    level: 97,
                    name: "Smith rune kiteshields"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                },
                {
                    itemId: 1319,
                    level: 99,
                    name: "Smith rune 2h swords"
                },
                {
                    itemId: 1127,
                    level: 99,
                    name: "Smith rune platebodies"
                },
                {
                    itemId: 1079,
                    level: 99,
                    name: "Smith rune platelegs"
                },
                {
                    itemId: 1093,
                    level: 99,
                    name: "Smith rune plateskirts"
                }
            ]
        },
        {
            label: "Members 1",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Convert bronze felling axes"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Convert iron felling axes"
                },
                {
                    itemId: 877,
                    level: 3,
                    name: "Smith bronze bolts (unf)"
                },
                {
                    itemId: 4819,
                    level: 4,
                    name: "Smith bronze nails"
                },
                {
                    itemId: 1794,
                    level: 4,
                    name: "Smith bronze wires"
                },
                {
                    itemId: 39,
                    level: 5,
                    name: "Smith bronze arrowtips"
                },
                {
                    itemId: -1,
                    level: 5,
                    name: "Smith Bronze cannonballs"
                },
                {
                    itemId: 11367,
                    level: 5,
                    name: "Smith bronze hastae (with Barbarian Training completed)"
                },
                {
                    itemId: 1237,
                    level: 5,
                    name: "Smith bronze spears (with Barbarian Training completed)"
                },
                {
                    itemId: 9420,
                    level: 6,
                    name: "Smith bronze limbs"
                },
                {
                    itemId: -1,
                    level: 6,
                    name: "Smith bronze javelin tips"
                },
                {
                    itemId: -1,
                    level: 6,
                    name: "Convert steel felling axes"
                },
                {
                    itemId: 864,
                    level: 7,
                    name: "Smith bronze knives"
                },
                {
                    itemId: -1,
                    level: 10,
                    name: "Smith bronze keel parts"
                },
                {
                    itemId: -1,
                    level: 10,
                    name: "Smith large bronze keel parts"
                },
                {
                    itemId: -1,
                    level: 11,
                    name: "Convert black felling axes"
                },
                {
                    itemId: 2349,
                    level: 15,
                    name: "Smelt bronze bars in the crucible of the Giants' Foundry"
                },
                {
                    itemId: 2351,
                    level: 15,
                    name: "Smelt iron bars in the crucible of the Giants' Foundry"
                },
                {
                    itemId: 7225,
                    level: 17,
                    name: "Smith iron spits"
                },
                {
                    itemId: 9140,
                    level: 18,
                    name: "Smith iron bolts (unf)"
                },
                {
                    itemId: 4820,
                    level: 19,
                    name: "Smith iron nails"
                },
                {
                    itemId: 40,
                    level: 20,
                    name: "Smith iron arrowtips"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Smith Iron cannonballs"
                },
                {
                    itemId: 11369,
                    level: 20,
                    name: "Smith iron hastae (with Barbarian Training completed)"
                },
                {
                    itemId: 1239,
                    level: 20,
                    name: "Smith iron spears (with Barbarian Training completed)"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Smith iron javelin tips"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Convert mithril felling axes"
                },
                {
                    itemId: 863,
                    level: 22,
                    name: "Smith iron knives"
                },
                {
                    itemId: -1,
                    level: 22,
                    name: "Smith iron keel parts"
                },
                {
                    itemId: -1,
                    level: 22,
                    name: "Smith large iron keel parts"
                },
                {
                    itemId: 9423,
                    level: 23,
                    name: "Smith iron limbs"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Smelt Lead bars"
                },
                {
                    itemId: 4540,
                    level: 26,
                    name: "Smith oil lantern frames"
                },
                {
                    itemId: 2353,
                    level: 30,
                    name: "Smelt steel bars in the crucible of the Giants' Foundry"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Convert adamant felling axes"
                },
                {
                    itemId: 9141,
                    level: 33,
                    name: "Smith steel bolts (unf)"
                },
                {
                    itemId: 41,
                    level: 35,
                    name: "Smith steel arrowtips"
                },
                {
                    itemId: 11371,
                    level: 35,
                    name: "Smith steel hastae (with Barbarian Training completed)"
                },
                {
                    itemId: 1241,
                    level: 35,
                    name: "Smith steel spears (with Barbarian Training completed)"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Smith secateurs attachments (with Woodcutting 35)"
                },
                {
                    itemId: -1,
                    level: 36,
                    name: "Smith steel javelin tips"
                },
                {
                    itemId: 9425,
                    level: 36,
                    name: "Smith steel limbs"
                },
                {
                    itemId: 2370,
                    level: 36,
                    name: "Smith steel studs"
                },
                {
                    itemId: 865,
                    level: 37,
                    name: "Smith steel knives"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Smith steel keel parts"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Smith large steel keel parts"
                },
                {
                    itemId: -1,
                    level: 41,
                    name: "Convert rune felling axes"
                },
                {
                    itemId: 13354,
                    level: 45,
                    name: "Smelt lovakite bars"
                },
                {
                    itemId: 13357,
                    level: 45,
                    name: "Smith tier 1 Shayzien gloves"
                },
                {
                    itemId: 13358,
                    level: 47,
                    name: "Smith tier 1 Shayzien boots"
                },
                {
                    itemId: 4544,
                    level: 49,
                    name: "Smith bullseye lanterns (unf)"
                },
                {
                    itemId: 13359,
                    level: 49,
                    name: "Smith tier 1 Shayzien helms"
                },
                {
                    itemId: 2359,
                    level: 50,
                    name: "Smelt mithril bars in the crucible of the Giants' Foundry"
                },
                {
                    itemId: 13360,
                    level: 51,
                    name: "Smith tier 1 Shayzien greaves"
                },
                {
                    itemId: 9142,
                    level: 53,
                    name: "Smith mithril bolts (unf)"
                },
                {
                    itemId: 13361,
                    level: 53,
                    name: "Smith tier 1 Shayzien platebodies"
                },
                {
                    itemId: 4822,
                    level: 54,
                    name: "Smith mithril nails"
                },
                {
                    itemId: 42,
                    level: 55,
                    name: "Smith mithril arrowtips"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Smith Mithril cannonballs"
                },
                {
                    itemId: 11373,
                    level: 55,
                    name: "Smith mithril hastae (with Barbarian Training completed)"
                },
                {
                    itemId: 1243,
                    level: 55,
                    name: "Smith mithril spears (with Barbarian Training completed)"
                },
                {
                    itemId: 13357,
                    level: 55,
                    name: "Smith tier 2 Shayzien gloves"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Smith mithril javelin tips"
                },
                {
                    itemId: 9427,
                    level: 56,
                    name: "Smith mithril limbs"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Smith mithril keel parts"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Smith large mithril keel parts"
                },
                {
                    itemId: 866,
                    level: 57,
                    name: "Smith mithril knives"
                },
                {
                    itemId: 13358,
                    level: 57,
                    name: "Smith tier 2 Shayzien boots"
                },
                {
                    itemId: 9416,
                    level: 59,
                    name: "Smith mith grapple tips"
                },
                {
                    itemId: 13359,
                    level: 59,
                    name: "Smith tier 2 Shayzien helms"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Entrance fee of no longer charged at the Blast Furnace"
                },
                {
                    itemId: 13360,
                    level: 61,
                    name: "Smith tier 2 Shayzien greaves"
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Convert dragon felling axes"
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Convert 3rd Age felling axes"
                },
                {
                    itemId: 13361,
                    level: 63,
                    name: "Smith tier 2 Shayzien platebodies"
                },
                {
                    itemId: 13357,
                    level: 65,
                    name: "Smith tier 3 Shayzien gloves"
                },
                {
                    itemId: 21633,
                    level: 66,
                    name: "Smith ancient wyvern shields (with Magic 66)"
                },
                {
                    itemId: 13358,
                    level: 67,
                    name: "Smith tier 3 Shayzien boots"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Build (with Construction 28)"
                },
                {
                    itemId: 13359,
                    level: 69,
                    name: "Smith tier 3 Shayzien helms"
                },
                {
                    itemId: 2361,
                    level: 70,
                    name: "Smelt adamantite bars in the crucible of the Giants' Foundry"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Repair broken zombie axes and zombie helmets"
                },
                {
                    itemId: 13360,
                    level: 71,
                    name: "Smith tier 3 Shayzien greaves"
                },
                {
                    itemId: -1,
                    level: 72,
                    name: "Smith noxious halberd (with Crafting 72)"
                },
                {
                    itemId: 9143,
                    level: 73,
                    name: "Smith adamant bolts(unf)"
                },
                {
                    itemId: 13361,
                    level: 73,
                    name: "Smith tier 3 Shayzien platebodies"
                },
                {
                    itemId: 4823,
                    level: 74,
                    name: "Smith adamantite nails"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Smith adamant keel parts"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Smith large adamant keel parts"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Smelt cupronickel bars"
                }
            ]
        },
        {
            label: "Members 2",
            entries: [
                {
                    itemId: 43,
                    level: 75,
                    name: "Smith adamant arrowtips"
                },
                {
                    itemId: 11375,
                    level: 75,
                    name: "Smith adamant hastae (with Barbarian Training completed)"
                },
                {
                    itemId: 1245,
                    level: 75,
                    name: "Smith adamant spears (with Barbarian Training completed)"
                },
                {
                    itemId: 13357,
                    level: 75,
                    name: "Smith tier 4 Shayzien gloves"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Make sturdy harnesses (with Woodcutting 75)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Smith Adamant cannonballs"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Smith adamant javelin tips"
                },
                {
                    itemId: 9429,
                    level: 76,
                    name: "Smith adamantite limbs"
                },
                {
                    itemId: 867,
                    level: 77,
                    name: "Smith adamant knives"
                },
                {
                    itemId: 13358,
                    level: 77,
                    name: "Smith tier 4 Shayzien boots"
                },
                {
                    itemId: 13359,
                    level: 79,
                    name: "Smith tier 4 Shayzien helms"
                },
                {
                    itemId: 11798,
                    level: 80,
                    name: "Smith godsword blades"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Upgrade Avernic treads"
                },
                {
                    itemId: 13360,
                    level: 81,
                    name: "Smith tier 4 Shayzien greaves"
                },
                {
                    itemId: 13361,
                    level: 83,
                    name: "Smith tier 4 Shayzien platebodies"
                },
                {
                    itemId: 2363,
                    level: 85,
                    name: "Smelt runite bars in the crucible of the Giants' Foundry"
                },
                {
                    itemId: 12827,
                    level: 85,
                    name: "Attach Arcane sigils to blessed spirit shields (with Prayer 90)"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Create ursine chainmaces"
                },
                {
                    itemId: 13243,
                    level: 85,
                    name: "Smith infernal pickaxe (with Mining 61)"
                },
                {
                    itemId: 13357,
                    level: 85,
                    name: "Smith tier 5 Shayzien gloves"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Smith rune keel parts"
                },
                {
                    itemId: -1,
                    level: 86,
                    name: "Smith large rune keel parts"
                },
                {
                    itemId: 13358,
                    level: 87,
                    name: "Smith tier 5 Shayzien boots"
                },
                {
                    itemId: 9144,
                    level: 88,
                    name: "Smith runite bolts (unf)"
                },
                {
                    itemId: -1,
                    level: 88,
                    name: "Build (with Construction 28)"
                },
                {
                    itemId: 4824,
                    level: 89,
                    name: "Smith rune nails"
                },
                {
                    itemId: 13359,
                    level: 89,
                    name: "Smith tier 5 Shayzien helms"
                },
                {
                    itemId: 12827,
                    level: 90,
                    name: "Attach an arcane sigil to Elidinis' ward (with Prayer 90)"
                },
                {
                    itemId: 11283,
                    level: 90,
                    name: "Smith dragonfire shields"
                },
                {
                    itemId: 22002,
                    level: 90,
                    name: "Smith dragonfire wards"
                },
                {
                    itemId: 26378,
                    level: 90,
                    name: "Restore damaged Torva platebody"
                },
                {
                    itemId: 44,
                    level: 90,
                    name: "Smith rune arrowtips"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Smith Rune cannonballs"
                },
                {
                    itemId: 11377,
                    level: 90,
                    name: "Smith rune hastae (with Barbarian Training completed)"
                },
                {
                    itemId: 1247,
                    level: 90,
                    name: "Smith rune spears (with Barbarian Training completed)"
                },
                {
                    itemId: -1,
                    level: 91,
                    name: "Smith rune javelin tips"
                },
                {
                    itemId: 9431,
                    level: 91,
                    name: "Smith runite limbs"
                },
                {
                    itemId: 13360,
                    level: 91,
                    name: "Smith tier 5 Shayzien greaves"
                },
                {
                    itemId: 868,
                    level: 92,
                    name: "Smith rune knives"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Smith Dragon nails"
                },
                {
                    itemId: -1,
                    level: 93,
                    name: "Smith tier 5 Shayzien bodies"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Smith dragon keel parts"
                },
                {
                    itemId: -1,
                    level: 94,
                    name: "Smith large dragon keel parts"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Build (with Construction 28)"
                },
                {
                    itemId: 9795,
                    level: 99,
                    name: "Buy the smithing cape and hood from Thurgo north of Mudskipper Point, and wear them"
                }
            ]
        }
    ]
};
