// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Strength/Level_up_table page. Blank requires fields are intended for hand editing.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const strengthSkillGuide: SkillGuideData = {
    skillId: SkillId.Strength,
    tabs: [
        {
            label: "Overview",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level in Strength contributes to a player's combat level",
                    requires: "",
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Each level in Strength has the potential to increase a player's maximum hit, dependent on other ",
                    requires: "",
                    description: "combat bonuses"
                },

            ]
        },
        {
            label: "Weapons",
            entries: [
                {
                    itemId: ,
                    level: 1,
                    name: "Bronze warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 1,
                    name: "Iron warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 5,
                    name: "Steel warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 5,
                    name: "Blask halberd",
                    requires: "Level 10 Attack",
                },
                {
                    itemId: ,
                    level: 5,
                    name: "White halberd",
                    requires: "Level 10 Attack",
                },
                {
                    itemId: ,
                    level: 10,
                    name: "Black warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 10,
                    name: "White warhammer",
                    requires: "Level 10 Prayer",
                },
                {
                    itemId: ,
                    level: 10,
                    name: "Mithril halberd",
                    requires: "Level 20 Attack",
                },
                {
                    itemId: ,
                    level: 15,
                    name: "Adamant halberd",
                    requires: "Level 30 Attack",
                },
                {
                    itemId: ,
                    level: 20,
                    name: "Mithril warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 20,
                    name: "Rune halberd",
                    requires: "Level 40 Attack",
                },
                {
                    itemId: ,
                    level: 30,
                    name: "Adamant warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 30,
                    name: "Hunter's spear",
                    requires: "Level 55 Ranged",
                },
                {
                    itemId: ,
                    level: 30,
                    name: "Dragon halberd",
                    requires: "Level 60 Attack",
                },
                {
                    itemId: ,
                    level: 40,
                    name: "Rune warhammer",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 40,
                    name: "Barrelchest Anchor",
                    requires: "Level 60 Attack, The Great Brain Robbery",
                },
                {
                    itemId: ,
                    level: 69,
                    name: "Adding more later, this is boring.",
                    requires: "Me to give a damn.",
                },
            ]
        },
        {
            label: "Armour",
            entries: [
                {
                    itemId: ,
                    level: 42,
                    name: "Void Knight equipment",
                    requires: "Level 22 Prayer, level 42 Ranged, level 42 Magic, level 42 Defence, level 42 Attack, level 42 Hitpoints",
                },
                {
                    itemId: ,
                    level: 50,
                    name: "Granite armour",
                    requires: "Level 50 Defence",
                },
                {
                    itemId: ,
                    level: 50,
                    name: "Zombie helmet",
                    requires: "Level 50 Defence",
                },
                {
                    itemId: ,
                    level: 70,
                    name: "Inquisitor's armour",
                    requires: "Level 30 Defence",
                },
                {
                    itemId: ,
                    level: 75,
                    name: "Primordial boots",
                    requires: "Level 75 Defence",
                },
                {
                    itemId: ,
                    level: 75,
                    name: "Bloodrager set",
                    requires: "Level 50 Defence",
                },
                {
                    itemId: ,
                    level: 80,
                    name: "Avernic treads",
                    requires: "Level 80 Defence, level 80 Ranged, level 80 Magic",
                },
                {
                    itemId: ,
                    level: 99,
                    name: "Skillcape",
                    requires: "See the custodian of the shot put room in the Warriors' Guild",
                },
            ]
        },
        {
            label: "Shortcuts",
            entries: [
                {
                    itemId: ,
                    level: 19,
                    name: "Grapple across the River Lum to Al Kharid",
                    requires: "Level 37 Ranged, level 8 agility",
                },
                {
                    itemId: ,
                    level: 21,
                    name: "Karamja crossing south of volcano",
                    requires: "Level 42 Ranged, level 53 Agility",
                },
                {
                    itemId: ,
                    level: 22,
                    name: "Escape from the Water Obelisk island",
                    requires: "Level 39 Ranged, level 36 Agility",
                },
                {
                    itemId: ,
                    level: 28,
                    name: "Scale the Observatory cliff",
                    requires: "Level 24 Ranged, level 23 Agility, Observatory Quest",
                },
                {
                    itemId: ,
                    level: 35,
                    name: "Scale the Catherby cliff",
                    requires: "Level 35 Ranged, level 32 Agility",
                },
                {
                    itemId: ,
                    level: 37,
                    name: "Scale Falador wall",
                    requires: "Level 19 Ranged, level 11 Agility",
                },
                {
                    itemId: ,
                    level: 38,
                    name: "Scale Yanille wall",
                    requires: "Level 21 Ranged, level 39 Agility",
                },
                {
                    itemId: ,
                    level: 70,
                    name: "Cross cave south of Dorgesh-Kaan",
                    requires: "Level 70 Ranged, level 70 Agility, Death to the Dorgeshuun",
                },
            ]
        },
        {
            label: "Areas",
            entries: [
                {
                    itemId: ,
                    level: 60,
                    name: "Access the God Wars Dungeon via the Strength route",
                    requires: "",
                },
                {
                    itemId: ,
                    level: 70,
                    name: "Enter the Bandos area of the God Wars Dungeon",
                    requires: "",
                },
            ]
        },
        {
            label: "Barbarian",
            entries: [
                {
                    itemId: ,
                    level: 15,
                    name: "Leaping trout",
                    requires: "Level 48 Fishing, level 15 Agility",
                },
                {
                    itemId: ,
                    level: 30,
                    name: "Leaping salmon",
                    requires: "Level 58 Fishing, level 30 Agility",
                },
                {
                    itemId: ,
                    level: 35,
                    name: "Tuna (barehanded)",
                    requires: "Level 55 Fishing",
                },
                {
                    itemId: ,
                    level: 35,
                    name: "Harpoonfish (barehanded)",
                    requires: "Level 55 Fishing",
                },
                {
                    itemId: ,
                    level: 45,
                    name: "Leaping sturgeon",
                    requires: "Level 70 Fishing, level 45 Agilty",
                },
                {
                    itemId: ,
                    level: 50,
                    name: "Swordfish (barehanded)",
                    requires: "Level 70 Fishing",
                },
                {
                    itemId: ,
                    level: 76,
                    name: "Shark (barehanded)",
                    requires: "Level 96 Fishing",
                },
            ]
        },
    ]
};
