// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Thieving/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const thievingSkillGuide: SkillGuideData = {
    skillId: SkillId.Thieving,
    tabs: [
        {
            label: "Members",
            entries: [
                {
                    itemId: -1,
                    level: 1,
                    name: "Pickpocket men/women/citizens"
                },
                {
                    itemId: 10847,
                    level: 1,
                    name: "Steal winter sq'irk from the Minigame Sorceress's Garden minigame"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Unlock the 10 coin chest door"
                },
                {
                    itemId: 1965,
                    level: 2,
                    name: "Steal from Cabbages"
                },
                {
                    itemId: 2309,
                    level: 5,
                    name: "Steal from Breads"
                },
                {
                    itemId: 1755,
                    level: 5,
                    name: "Steal from Chisels"
                },
                {
                    itemId: 712,
                    level: 5,
                    name: "Steal from Cup of teas"
                },
                {
                    itemId: -1,
                    level: 10,
                    name: "Pickpocket Thief Farmers"
                },
                {
                    itemId: 617,
                    level: 13,
                    name: "Loot the 10 coin chests"
                },
                {
                    itemId: -1,
                    level: 15,
                    name: "Pickpocket H.A.M. members"
                },
                {
                    itemId: -1,
                    level: 16,
                    name: "Unlock the nature rune chest door"
                },
                {
                    itemId: 950,
                    level: 20,
                    name: "Steal from Silks"
                },
                {
                    itemId: 36,
                    level: 20,
                    name: "Steal candles on Entrana church"
                },
                {
                    itemId: -1,
                    level: 20,
                    name: "Pick locks on Ogre Coffins"
                },
                {
                    itemId: 7919,
                    level: 22,
                    name: "Steal from Bottle of wines"
                },
                {
                    itemId: -1,
                    level: 23,
                    name: "Unlock the axe hut door"
                },
                {
                    itemId: -1,
                    level: 25,
                    name: "Pickpocket warriors/Al Kharid warriors"
                },
                {
                    itemId: 671,
                    level: 25,
                    name: "Steal from Animal skull"
                },
                {
                    itemId: 1955,
                    level: 25,
                    name: "Steal from Cooking apples"
                },
                {
                    itemId: 10844,
                    level: 25,
                    name: "Steal spring sq'irk from the Minigame Sorceress's Garden minigame"
                },
                {
                    itemId: -1,
                    level: 27,
                    name: "Steal from Barley seed 5s"
                },
                {
                    itemId: 561,
                    level: 28,
                    name: "Loot the nature rune chests"
                },
                {
                    itemId: 25244,
                    level: 28,
                    name: "Loot the chest in the Isle of Souls Dungeon"
                },
                {
                    itemId: 25244,
                    level: 28,
                    name: "Loot the Dark key"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Pickpocket Thief Villagers"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Unlock the ardougne sewer gate"
                },
                {
                    itemId: -1,
                    level: 32,
                    name: "Pickpocket Thief Rogues"
                },
                {
                    itemId: -1,
                    level: 33,
                    name: "Loot the Bronze cannonball"
                },
                {
                    itemId: 6814,
                    level: 35,
                    name: "Steal from Furs"
                },
                {
                    itemId: -1,
                    level: 38,
                    name: "Pickpocket Thief Master farmers"
                },
                {
                    itemId: -1,
                    level: 39,
                    name: "Unlock the pirate hall door"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Pickpocket Thief Guards"
                },
                {
                    itemId: 617,
                    level: 43,
                    name: "Loot the 50 coin chests"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Pickpocket Thief Fremenniks"
                },
                {
                    itemId: 10846,
                    level: 45,
                    name: "Steal autumn sq'irk from the Minigame Sorceress's Garden minigame"
                },
                {
                    itemId: -1,
                    level: 46,
                    name: "Unlock the chaos druid tower door"
                },
                {
                    itemId: 41,
                    level: 47,
                    name: "Loot the arrowtips chests"
                },
                {
                    itemId: 9174,
                    level: 49,
                    name: "Steal from Bronze crossbows"
                },
                {
                    itemId: -1,
                    level: 49,
                    name: "Required for stealing artefacts in Port Piscarilius"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Access to the Rogues' Den minigame (with Agility 50)"
                },
                {
                    itemId: 5554,
                    level: 50,
                    name: "Able to obtain Rogue mask, granting double pickpocketing loot"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Crack wall safes inside the Rogues' Den"
                },
                {
                    itemId: 442,
                    level: 50,
                    name: "Steal from Silver ores"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Pickpocket Thief Wealthy citizens"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required for stealing valuables in Civitas illa Fortis"
                },
                {
                    itemId: -1,
                    level: 53,
                    name: "Pickpocket Thief Desert bandits"
                },
                {
                    itemId: 2,
                    level: 54,
                    name: "Loot the Cannonball"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Pickpocket Knights"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Unlock the grubby chest gate"
                },
                {
                    itemId: 565,
                    level: 59,
                    name: "Loot the blood rune chests"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Pickpocket pirates"
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Unlock the Ardougne Castle door"
                },
                {
                    itemId: 13383,
                    level: 64,
                    name: "Loot Xerician fabrics"
                },
                {
                    itemId: -1,
                    level: 65,
                    name: "Pickpocket watchmen"
                },
                {
                    itemId: 1323,
                    level: 65,
                    name: "Steal from Iron scimitars"
                },
                {
                    itemId: 2007,
                    level: 65,
                    name: "Steal from Spices"
                },
                {
                    itemId: 10845,
                    level: 65,
                    name: "Steal summer sq'irk from the Minigame Sorceress's Garden minigame"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Pickpocket Thief Paladins"
                },
                {
                    itemId: 383,
                    level: 72,
                    name: "Loot the king lathas' chests"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Pickpocket gnomes"
                },
                {
                    itemId: 1607,
                    level: 75,
                    name: "Steal from Sapphires"
                },
                {
                    itemId: -1,
                    level: 76,
                    name: "Loot the Adamant cannonball"
                },
                {
                    itemId: 1623,
                    level: 78,
                    name: "Loot the dorgesh-kaan rich chests"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Pickpocket Thief Heroes"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Shortcut in the Rogues' Den maze"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Pickpocket Vyre icons"
                },
                {
                    itemId: 449,
                    level: 82,
                    name: "Steal from Adamantite ores"
                },
                {
                    itemId: -1,
                    level: 82,
                    name: "Unlock the yanille dungeon door"
                },
                {
                    itemId: 1615,
                    level: 84,
                    name: "Loot the rogues' castle chests"
                },
                {
                    itemId: -1,
                    level: 85,
                    name: "Pickpocket elves"
                },
                {
                    itemId: 2,
                    level: 87,
                    name: "Steal from Cannonballs"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Pickpocket Thief TzHaar-Hurs"
                },
                {
                    itemId: 9777,
                    level: 99,
                    name: "Buy the thieving cape and hood from Martin Thwait in the Rogues' Den, and wear them"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        }
    ]
};
