// Generated by scripts/sync-wiki-skill-guides.ts from the OSRS Wiki's public
// Woodcutting/Level_up_table page. Refresh deliberately; do not hand-edit.
import { SkillId } from "../../../../../client/rs/skill/skills";
import type { SkillGuideData } from "../types";

export const woodcuttingSkillGuide: SkillGuideData = {
    skillId: SkillId.Woodcutting,
    tabs: [
        {
            label: "Free-to-play",
            entries: [
                {
                    itemId: 1511,
                    level: 1,
                    name: "Chop logs"
                },
                {
                    itemId: 1351,
                    level: 1,
                    name: "Chop with bronze axes"
                },
                {
                    itemId: 1349,
                    level: 1,
                    name: "Chop with iron axes"
                },
                {
                    itemId: 1353,
                    level: 6,
                    name: "Chop with steel axes"
                },
                {
                    itemId: 1361,
                    level: 11,
                    name: "Chop with black axes"
                },
                {
                    itemId: -1,
                    level: 12,
                    name: "Carve log canoes"
                },
                {
                    itemId: 1521,
                    level: 15,
                    name: "Chop oak logs"
                },
                {
                    itemId: -1,
                    level: 19,
                    name: "New information is available from the 22570"
                },
                {
                    itemId: 1355,
                    level: 21,
                    name: "Chop with mithril axes"
                },
                {
                    itemId: -1,
                    level: 27,
                    name: "Carve dugout canoes"
                },
                {
                    itemId: -1,
                    level: 29,
                    name: "New information is available from the 22570"
                },
                {
                    itemId: 1519,
                    level: 30,
                    name: "Chop willow logs"
                },
                {
                    itemId: 1357,
                    level: 31,
                    name: "Chop with adamant axes"
                },
                {
                    itemId: 1359,
                    level: 41,
                    name: "Chop with rune axes"
                },
                {
                    itemId: 23279,
                    level: 41,
                    name: "Chop with gilded axes"
                },
                {
                    itemId: -1,
                    level: 42,
                    name: "Carve stable dugout canoes"
                },
                {
                    itemId: 1517,
                    level: 45,
                    name: "Chop maple logs"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Carve waka canoes"
                },
                {
                    itemId: 1515,
                    level: 60,
                    name: "Chop yew logs"
                },
                {
                    itemId: -1,
                    level: 99,
                    name: "Skill mastery"
                }
            ]
        },
        {
            label: "Members",
            entries: [
                {
                    itemId: 2862,
                    level: 1,
                    name: "Chop achey tree logs"
                },
                {
                    itemId: 9094,
                    level: 1,
                    name: "Receive a maximum of 1 Kindling from trees at Ice demon"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Chop with bronze felling axes"
                },
                {
                    itemId: -1,
                    level: 1,
                    name: "Chop with iron felling axes"
                },
                {
                    itemId: 1823,
                    level: 1,
                    name: "Cut a Kharidian cactus to fill a waterskin"
                },
                {
                    itemId: -1,
                    level: 6,
                    name: "Chop with steel felling axes"
                },
                {
                    itemId: 6281,
                    level: 10,
                    name: "Chop Thatch spar light (with quest Jungle Potion completed)"
                },
                {
                    itemId: -1,
                    level: 10,
                    name: "Required for Quest My Arm's Big Adventure"
                },
                {
                    itemId: -1,
                    level: 11,
                    name: "Chop with black felling axes"
                },
                {
                    itemId: -1,
                    level: 15,
                    name: "Required to complete Diary Easy Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 15,
                    name: "Required to complete Diary Easy Fremennik Diary"
                },
                {
                    itemId: 6283,
                    level: 20,
                    name: "Chop Thatch spar med (with quest Jungle Potion completed)"
                },
                {
                    itemId: -1,
                    level: 21,
                    name: "Chop with mithril felling axes"
                },
                {
                    itemId: 9094,
                    level: 24,
                    name: "Receive a maximum of 2 Kindling from trees at Ice demon"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required to complete Diary Lumbridge & Draynor Medium Diary"
                },
                {
                    itemId: -1,
                    level: 30,
                    name: "Required to complete Diary Falador Medium Diary"
                },
                {
                    itemId: -1,
                    level: 31,
                    name: "Chop with adamant felling axes"
                },
                {
                    itemId: 6285,
                    level: 35,
                    name: "Chop Thatch spar dense (with quest Jungle Potion completed)"
                },
                {
                    itemId: 6333,
                    level: 35,
                    name: "Chop teak logs"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Make forester's rations (with Cooking 35)"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Make secateurs attachments (with Smithing 35)"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Required for Quest Animal Magnetism"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Required to complete Diary Medium Desert Diary"
                },
                {
                    itemId: -1,
                    level: 35,
                    name: "Required to complete Diary Medium Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 36,
                    name: "Required for Quest Lost City"
                },
                {
                    itemId: 9094,
                    level: 36,
                    name: "Receive a maximum of 3 Kindling from trees at Ice demon"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Chop jatoba logs"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Required for Quest The Fremennik Trials"
                },
                {
                    itemId: -1,
                    level: 40,
                    name: "Required for Quest Troubled Tortugans"
                },
                {
                    itemId: -1,
                    level: 41,
                    name: "Chop with rune felling axes"
                },
                {
                    itemId: 13355,
                    level: 42,
                    name: "Chop juniper logs"
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Wear lumberjack clothing"
                },
                {
                    itemId: -1,
                    level: 44,
                    name: "Wear the forestry outfit"
                },
                {
                    itemId: 3239,
                    level: 45,
                    name: "Chop bark"
                },
                {
                    itemId: -1,
                    level: 45,
                    name: "Required to complete Diary Medium Morytania Diary"
                },
                {
                    itemId: 9094,
                    level: 48,
                    name: "Receive a maximum of 4 Kindling from trees at Ice demon"
                },
                {
                    itemId: 6332,
                    level: 50,
                    name: "Chop mahogany logs"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Make clothes pouches (with Crafting 50)"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required for Quest Legends' Quest"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required for Quest Olaf's Quest"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required to complete Diary Medium Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required to complete Diary Medium Karamja Diary"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required to complete Diary Hard Western Provinces Diary"
                },
                {
                    itemId: -1,
                    level: 50,
                    name: "Required to complete Diary Hard Morytania Diary"
                },
                {
                    itemId: 10810,
                    level: 54,
                    name: "Chop arctic pine logs"
                },
                {
                    itemId: -1,
                    level: 55,
                    name: "Required for Quest Lunar Diplomacy"
                },
                {
                    itemId: 10812,
                    level: 56,
                    name: "Split arctic pine logs"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Craft Neitiznot shield"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Required for Quest The Fremennik Isles"
                },
                {
                    itemId: -1,
                    level: 56,
                    name: "Required to complete Diary Hard Fremennik Diary"
                },
                {
                    itemId: -1,
                    level: 57,
                    name: "Required to complete Diary Hard Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Access the Woodcutting Guild"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Required to complete Diary Hard Kandarin Diary"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Required to complete Diary Hard Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 60,
                    name: "Required to complete Diary Hard Varrock Diary"
                },
                {
                    itemId: 9094,
                    level: 60,
                    name: "Receive a maximum of 5 Kindling from trees at Ice demon"
                },
                {
                    itemId: 6739,
                    level: 61,
                    name: "Chop with dragon axes, 3rd Age axes, and infernal axes"
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Chop with dragon felling axes"
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Chop with 3rd Age felling axes"
                },
                {
                    itemId: -1,
                    level: 61,
                    name: "Required to complete Diary Medium Wilderness Diary"
                },
                {
                    itemId: 24691,
                    level: 62,
                    name: "Chop blisterwood logs (with partial completion of Quest Sins of the Father)"
                },
                {
                    itemId: -1,
                    level: 62,
                    name: "Required for Quest Sins of the Father"
                },
                {
                    itemId: 6004,
                    level: 65,
                    name: "Chop mushrooms, mort myre fungus, and sulliuscep caps from Sulliuscep"
                },
                {
                    itemId: -1,
                    level: 66,
                    name: "Chop camphor logs"
                },
                {
                    itemId: -1,
                    level: 68,
                    name: "Make nature offerings (with Farming 50)"
                },
                {
                    itemId: -1,
                    level: 70,
                    name: "Required for Quest Song of the Elves"
                },
                {
                    itemId: 23673,
                    level: 71,
                    name: "Use crystal axes (with Quest Song of the Elves completed)"
                },
                {
                    itemId: -1,
                    level: 71,
                    name: "Use crystal felling axes (with Quest Song of the Elves completed)"
                },
                {
                    itemId: -1,
                    level: 71,
                    name: "Required for Quest Grim Tales"
                },
                {
                    itemId: 9094,
                    level: 72,
                    name: "Receive a maximum of 6 Kindling from trees at Ice demon"
                },
                {
                    itemId: -1,
                    level: 74,
                    name: "Required for Quest The Blood Moon Rises"
                },
                {
                    itemId: 1513,
                    level: 75,
                    name: "Chop magic logs"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Make sturdy harnesses (with Smithing 75)"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Required to complete Diary Elite Falador Diary"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Required to complete Diary Elite Lumbridge & Draynor Diary"
                },
                {
                    itemId: -1,
                    level: 75,
                    name: "Required to complete Diary Elite Wilderness Diary"
                },
                {
                    itemId: -1,
                    level: 77,
                    name: "Chop Bucket of bloodwood saps (with Quest The Blood Moon Rises completed)"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Chop Demon tears"
                },
                {
                    itemId: -1,
                    level: 80,
                    name: "Chop ironwood logs"
                },
                {
                    itemId: 9094,
                    level: 84,
                    name: "Receive a maximum of 7 Kindling from trees at Ice demon"
                },
                {
                    itemId: 19669,
                    level: 90,
                    name: "Chop redwood logs"
                },
                {
                    itemId: -1,
                    level: 90,
                    name: "Required to complete Diary Elite Kourend & Kebos Diary"
                },
                {
                    itemId: -1,
                    level: 92,
                    name: "Chop rosewood logs"
                },
                {
                    itemId: 9094,
                    level: 96,
                    name: "Receive a maximum of 8 Kindling from trees at Ice demon"
                },
                {
                    itemId: 9807,
                    level: 99,
                    name: "Buy the Woodcutting cape and hood from Wilfred south of the furnace in Lumbridge, and wear them"
                }
            ]
        }
    ]
};
