import type { PlayerState } from "@server/game/player";
import type { CombatAttack } from "@server/game/combat/model/CombatAttack";
import { SpecialAttackTiming, type WeaponCombatProfile } from "@server/game/combat/plugins/WeaponCombatProfile";
import {
    type WeaponSpecialAttackScript,
    setWeaponSpecialAttackTraitOverrides,
} from "@server/game/combat/special-attacks/WeaponSpecialAttackScript";

export const GRANITE_MAUL_ITEM_IDS = Object.freeze([4153, 12848, 24225]);
export const ORNATE_GRANITE_MAUL_ITEM_ID = 24225;
export const GRANITE_MAUL_STANDARD_ENERGY_COST = 60;
export const GRANITE_MAUL_ORNATE_ENERGY_COST = 50;

const GRANITE_MAUL_SPECIAL = Object.freeze({
    hitCount: 1,
    accuracyMultiplier: 1,
    damageMultiplier: 1,
    attackAnimation: 1667,
    castGraphic: Object.freeze({ id: 340 }),
    attackSoundId: 2715,
});

function createGraniteMaulProfile(
    id: string,
    itemIds: readonly number[],
    energyCostPercent: number,
): WeaponCombatProfile {
    return Object.freeze({
        id,
        itemIds: Object.freeze([...itemIds]),
        specialAttackEnergyCost: energyCostPercent,
        specialAttackTiming: SpecialAttackTiming.Instant,
        handleSpecialAttack: () =>
            Object.freeze({
                ...GRANITE_MAUL_SPECIAL,
                energyCostPercent,
            }),
    });
}

export const GRANITE_MAUL_SPECIAL_ATTACK_PROFILE = createGraniteMaulProfile(
    "core:granite_maul",
    [4153, 12848],
    GRANITE_MAUL_STANDARD_ENERGY_COST,
);

export const ORNATE_GRANITE_MAUL_SPECIAL_ATTACK_PROFILE = createGraniteMaulProfile(
    "core:granite_maul_ornate",
    [ORNATE_GRANITE_MAUL_ITEM_ID],
    GRANITE_MAUL_ORNATE_ENERGY_COST,
);

export const GRANITE_MAUL_SPECIAL_ATTACK_PROFILES = Object.freeze([
    GRANITE_MAUL_SPECIAL_ATTACK_PROFILE,
    ORNATE_GRANITE_MAUL_SPECIAL_ATTACK_PROFILE,
]);

export function isGraniteMaul(weaponId: number): boolean {
    return GRANITE_MAUL_ITEM_IDS.includes(Math.trunc(weaponId));
}

export function getGraniteMaulSpecialAttackEnergyCost(weaponId: number): number | undefined {
    if (!isGraniteMaul(weaponId)) return undefined;
    return Math.trunc(weaponId) === ORNATE_GRANITE_MAUL_ITEM_ID
        ? GRANITE_MAUL_ORNATE_ENERGY_COST
        : GRANITE_MAUL_STANDARD_ENERGY_COST;
}

export interface GraniteMaulActivationResult {
    readonly handled: boolean;
    readonly queued: boolean;
    readonly insufficientEnergy: boolean;
}

/**
 * Converts one physical special-bar click into one queued Quick Smash. The
 * varp and IF_BUTTON generated by that click are paired by PlayerCombatState,
 * so packet batching cannot merge two rapid clicks or count one click twice.
 */
export function queueGraniteMaulSpecialAttackInput(
    player: PlayerState,
    weaponId: number,
    currentTick: number,
    source: "varp" | "button",
): GraniteMaulActivationResult {
    const energyCost = getGraniteMaulSpecialAttackEnergyCost(weaponId);
    if (energyCost === undefined) {
        return { handled: false, queued: false, insufficientEnergy: false };
    }
    if (!player.combat.claimInstantSpecialActivationInput(source, currentTick)) {
        return { handled: true, queued: false, insufficientEnergy: false };
    }

    player.combat.pruneExpiredInstantSpecialAttacks(currentTick, 3);
    const queuedCount = player.combat.countQueuedInstantSpecialAttacks(weaponId);
    const reservedEnergy = queuedCount * energyCost;
    if (player.specEnergy.getUnits() - reservedEnergy < energyCost) {
        return { handled: true, queued: false, insufficientEnergy: true };
    }

    player.combat.queueInstantSpecialAttack(
        weaponId,
        player.getCombatTarget(),
        currentTick,
    );
    player.specEnergy.setActivated(true);
    return { handled: true, queued: true, insufficientEnergy: false };
}

export class GraniteMaulSpecialAttackScript implements WeaponSpecialAttackScript {
    readonly energyCost: number;
    readonly bypassAttackDelay = true;

    constructor(readonly itemId: number) {
        this.energyCost = getGraniteMaulSpecialAttackEnergyCost(itemId) ?? 0;
    }

    modifyAttackTraits(attack: CombatAttack): void {
        setWeaponSpecialAttackTraitOverrides(attack, {
            hitCount: GRANITE_MAUL_SPECIAL.hitCount,
            accuracyMultiplier: GRANITE_MAUL_SPECIAL.accuracyMultiplier,
            damageMultiplier: GRANITE_MAUL_SPECIAL.damageMultiplier,
        });
    }

    onHitApplied(
        attacker: any,
        target: any,
        damageCalculated: number,
        currentMapClock: number,
    ): void {
        void attacker;
        void target;
        void damageCalculated;
        void currentMapClock;
    }
}

export const GRANITE_MAUL_SPECIAL_ATTACK_SCRIPTS = Object.freeze(
    GRANITE_MAUL_ITEM_IDS.map((itemId) =>
        Object.freeze(new GraniteMaulSpecialAttackScript(itemId)),
    ),
);
