export const HAMMER_ITEM_ID = 2347;
/** The wieldable hammer has two cache variants; both count as a normal hammer. */
export const IMCANDO_HAMMER_ITEM_IDS = [25644, 25645] as const;
export const FURNACE_ANIMATION = 899;

export type SmithingProductSlot =
    | "dagger"
    | "sword"
    | "scimitar"
    | "longsword"
    | "2h"
    | "axe"
    | "mace"
    | "warhammer"
    | "battleaxe"
    | "claws"
    | "chainbody"
    | "platelegs"
    | "plateskirt"
    | "platebody"
    | "nails"
    | "medhelm"
    | "fullhelm"
    | "squareshield"
    | "kiteshield"
    | "other_2"
    | "darttips"
    | "arrowheads"
    | "knives"
    | "other_1"
    | "other_3"
    | "bolts"
    | "limbs";

export interface SmithingRecipe {
    id: string;
    name: string;
    level: number;
    xp: number;
    barItemId: number;
    barCount: number;
    outputItemId: number;
    outputQuantity: number;
    slot: SmithingProductSlot;
    requireHammer?: boolean;
    animation?: number;
    delayTicks?: number;
}

export interface SmeltingRequirement {
    itemId: number;
    quantity: number;
}

export interface SmeltingRecipe {
    id: string;
    name: string;
    level: number;
    xp: number;
    inputs: SmeltingRequirement[];
    /** Required tools are checked but never consumed. */
    requiredToolItemIds?: readonly number[];
    /** Omit for ordinary furnaces; restricted recipes validate their source. */
    allowedLocIds?: readonly number[];
    outputItemId: number;
    outputQuantity: number;
    animation?: number;
    delayTicks?: number;
    successType?: "guaranteed" | "iron";
    ingredientsLabel?: string;
}

export const SMITHING_RECIPES: SmithingRecipe[] = [
    {
        id: "blurite_bolts",
        name: "Blurite bolts (unf)",
        level: 8,
        xp: 17.5,
        barItemId: 9467,
        barCount: 1,
        outputItemId: 9376,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4,
    },
    {
        id: "blurite_limbs",
        name: "Blurite limbs",
        level: 13,
        xp: 17.5,
        barItemId: 9467,
        barCount: 1,
        outputItemId: 9422,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4,
    },
    {
        id: "bronze_dagger",
        name: "Bronze dagger",
        level: 1,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 1205,
        outputQuantity: 1,
        slot: "dagger",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_dagger",
        name: "Iron dagger",
        level: 15,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 1203,
        outputQuantity: 1,
        slot: "dagger",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_dagger",
        name: "Steel dagger",
        level: 30,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 1207,
        outputQuantity: 1,
        slot: "dagger",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_dagger",
        name: "Mithril dagger",
        level: 50,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 1209,
        outputQuantity: 1,
        slot: "dagger",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_dagger",
        name: "Adamant dagger",
        level: 70,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 1211,
        outputQuantity: 1,
        slot: "dagger",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_dagger",
        name: "Rune dagger",
        level: 85,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 1213,
        outputQuantity: 1,
        slot: "dagger",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_axe",
        name: "Bronze axe",
        level: 1,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 1351,
        outputQuantity: 1,
        slot: "axe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_axe",
        name: "Iron axe",
        level: 16,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 1349,
        outputQuantity: 1,
        slot: "axe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_axe",
        name: "Steel axe",
        level: 31,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 1353,
        outputQuantity: 1,
        slot: "axe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_axe",
        name: "Mithril axe",
        level: 51,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 1355,
        outputQuantity: 1,
        slot: "axe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_axe",
        name: "Adamant axe",
        level: 71,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 1357,
        outputQuantity: 1,
        slot: "axe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_axe",
        name: "Rune axe",
        level: 86,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 1359,
        outputQuantity: 1,
        slot: "axe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_mace",
        name: "Bronze mace",
        level: 2,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 1422,
        outputQuantity: 1,
        slot: "mace",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_mace",
        name: "Iron mace",
        level: 17,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 1420,
        outputQuantity: 1,
        slot: "mace",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_mace",
        name: "Steel mace",
        level: 32,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 1424,
        outputQuantity: 1,
        slot: "mace",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_mace",
        name: "Mithril mace",
        level: 52,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 1428,
        outputQuantity: 1,
        slot: "mace",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_mace",
        name: "Adamant mace",
        level: 72,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 1430,
        outputQuantity: 1,
        slot: "mace",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_mace",
        name: "Rune mace",
        level: 87,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 1432,
        outputQuantity: 1,
        slot: "mace",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_medhelm",
        name: "Bronze med helm",
        level: 3,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 1139,
        outputQuantity: 1,
        slot: "medhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_medhelm",
        name: "Iron med helm",
        level: 18,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 1137,
        outputQuantity: 1,
        slot: "medhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_medhelm",
        name: "Steel med helm",
        level: 33,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 1141,
        outputQuantity: 1,
        slot: "medhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_medhelm",
        name: "Mithril med helm",
        level: 53,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 1143,
        outputQuantity: 1,
        slot: "medhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_medhelm",
        name: "Adamant med helm",
        level: 73,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 1145,
        outputQuantity: 1,
        slot: "medhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_medhelm",
        name: "Rune med helm",
        level: 88,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 1147,
        outputQuantity: 1,
        slot: "medhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_darttips",
        name: "Bronze dart tip",
        level: 4,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 819,
        outputQuantity: 10,
        slot: "darttips",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_darttips",
        name: "Iron dart tip",
        level: 19,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 820,
        outputQuantity: 10,
        slot: "darttips",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_darttips",
        name: "Steel dart tip",
        level: 34,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 821,
        outputQuantity: 10,
        slot: "darttips",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_darttips",
        name: "Mithril dart tip",
        level: 54,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 822,
        outputQuantity: 10,
        slot: "darttips",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_darttips",
        name: "Adamant dart tip",
        level: 74,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 823,
        outputQuantity: 10,
        slot: "darttips",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_darttips",
        name: "Rune dart tip",
        level: 89,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 824,
        outputQuantity: 10,
        slot: "darttips",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_sword",
        name: "Bronze sword",
        level: 4,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 1277,
        outputQuantity: 1,
        slot: "sword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_sword",
        name: "Iron sword",
        level: 19,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 1279,
        outputQuantity: 1,
        slot: "sword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_sword",
        name: "Steel sword",
        level: 34,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 1281,
        outputQuantity: 1,
        slot: "sword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_sword",
        name: "Mithril sword",
        level: 54,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 1285,
        outputQuantity: 1,
        slot: "sword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_sword",
        name: "Adamant sword",
        level: 74,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 1287,
        outputQuantity: 1,
        slot: "sword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_sword",
        name: "Rune sword",
        level: 89,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 1289,
        outputQuantity: 1,
        slot: "sword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_scimitar",
        name: "Bronze scimitar",
        level: 5,
        xp: 25,
        barItemId: 2349,
        barCount: 2,
        outputItemId: 1321,
        outputQuantity: 1,
        slot: "scimitar",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_scimitar",
        name: "Iron scimitar",
        level: 20,
        xp: 50,
        barItemId: 2351,
        barCount: 2,
        outputItemId: 1323,
        outputQuantity: 1,
        slot: "scimitar",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_scimitar",
        name: "Steel scimitar",
        level: 35,
        xp: 75,
        barItemId: 2353,
        barCount: 2,
        outputItemId: 1325,
        outputQuantity: 1,
        slot: "scimitar",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_scimitar",
        name: "Mithril scimitar",
        level: 55,
        xp: 100,
        barItemId: 2359,
        barCount: 2,
        outputItemId: 1329,
        outputQuantity: 1,
        slot: "scimitar",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_scimitar",
        name: "Adamant scimitar",
        level: 75,
        xp: 125,
        barItemId: 2361,
        barCount: 2,
        outputItemId: 1331,
        outputQuantity: 1,
        slot: "scimitar",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_scimitar",
        name: "Rune scimitar",
        level: 90,
        xp: 150,
        barItemId: 2363,
        barCount: 2,
        outputItemId: 1333,
        outputQuantity: 1,
        slot: "scimitar",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_longsword",
        name: "Bronze longsword",
        level: 6,
        xp: 25,
        barItemId: 2349,
        barCount: 2,
        outputItemId: 1291,
        outputQuantity: 1,
        slot: "longsword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_longsword",
        name: "Iron longsword",
        level: 21,
        xp: 50,
        barItemId: 2351,
        barCount: 2,
        outputItemId: 1293,
        outputQuantity: 1,
        slot: "longsword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_longsword",
        name: "Steel longsword",
        level: 36,
        xp: 75,
        barItemId: 2353,
        barCount: 2,
        outputItemId: 1295,
        outputQuantity: 1,
        slot: "longsword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_longsword",
        name: "Mithril longsword",
        level: 56,
        xp: 100,
        barItemId: 2359,
        barCount: 2,
        outputItemId: 1299,
        outputQuantity: 1,
        slot: "longsword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_longsword",
        name: "Adamant longsword",
        level: 76,
        xp: 125,
        barItemId: 2361,
        barCount: 2,
        outputItemId: 1301,
        outputQuantity: 1,
        slot: "longsword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_longsword",
        name: "Rune longsword",
        level: 91,
        xp: 150,
        barItemId: 2363,
        barCount: 2,
        outputItemId: 1303,
        outputQuantity: 1,
        slot: "longsword",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_fullhelm",
        name: "Bronze full helm",
        level: 7,
        xp: 25,
        barItemId: 2349,
        barCount: 2,
        outputItemId: 1155,
        outputQuantity: 1,
        slot: "fullhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_fullhelm",
        name: "Iron full helm",
        level: 22,
        xp: 50,
        barItemId: 2351,
        barCount: 2,
        outputItemId: 1153,
        outputQuantity: 1,
        slot: "fullhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_fullhelm",
        name: "Steel full helm",
        level: 37,
        xp: 75,
        barItemId: 2353,
        barCount: 2,
        outputItemId: 1157,
        outputQuantity: 1,
        slot: "fullhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_fullhelm",
        name: "Mithril full helm",
        level: 57,
        xp: 100,
        barItemId: 2359,
        barCount: 2,
        outputItemId: 1159,
        outputQuantity: 1,
        slot: "fullhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_fullhelm",
        name: "Adamant full helm",
        level: 77,
        xp: 125,
        barItemId: 2361,
        barCount: 2,
        outputItemId: 1161,
        outputQuantity: 1,
        slot: "fullhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_fullhelm",
        name: "Rune full helm",
        level: 92,
        xp: 150,
        barItemId: 2363,
        barCount: 2,
        outputItemId: 1163,
        outputQuantity: 1,
        slot: "fullhelm",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_squareshield",
        name: "Bronze sq shield",
        level: 8,
        xp: 25,
        barItemId: 2349,
        barCount: 2,
        outputItemId: 1173,
        outputQuantity: 1,
        slot: "squareshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_squareshield",
        name: "Iron sq shield",
        level: 23,
        xp: 50,
        barItemId: 2351,
        barCount: 2,
        outputItemId: 1175,
        outputQuantity: 1,
        slot: "squareshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_squareshield",
        name: "Steel sq shield",
        level: 38,
        xp: 75,
        barItemId: 2353,
        barCount: 2,
        outputItemId: 1177,
        outputQuantity: 1,
        slot: "squareshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_squareshield",
        name: "Mithril sq shield",
        level: 58,
        xp: 100,
        barItemId: 2359,
        barCount: 2,
        outputItemId: 1181,
        outputQuantity: 1,
        slot: "squareshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_squareshield",
        name: "Adamant sq shield",
        level: 78,
        xp: 125,
        barItemId: 2361,
        barCount: 2,
        outputItemId: 1183,
        outputQuantity: 1,
        slot: "squareshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_squareshield",
        name: "Rune sq shield",
        level: 93,
        xp: 150,
        barItemId: 2363,
        barCount: 2,
        outputItemId: 1185,
        outputQuantity: 1,
        slot: "squareshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_warhammer",
        name: "Bronze warhammer",
        level: 9,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1337,
        outputQuantity: 1,
        slot: "warhammer",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_warhammer",
        name: "Iron warhammer",
        level: 24,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1335,
        outputQuantity: 1,
        slot: "warhammer",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_warhammer",
        name: "Steel warhammer",
        level: 39,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1339,
        outputQuantity: 1,
        slot: "warhammer",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_warhammer",
        name: "Mithril warhammer",
        level: 59,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1343,
        outputQuantity: 1,
        slot: "warhammer",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_warhammer",
        name: "Adamant warhammer",
        level: 79,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1345,
        outputQuantity: 1,
        slot: "warhammer",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_warhammer",
        name: "Rune warhammer",
        level: 94,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1347,
        outputQuantity: 1,
        slot: "warhammer",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_battleaxe",
        name: "Bronze battleaxe",
        level: 10,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1375,
        outputQuantity: 1,
        slot: "battleaxe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_battleaxe",
        name: "Iron battleaxe",
        level: 25,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1363,
        outputQuantity: 1,
        slot: "battleaxe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_battleaxe",
        name: "Steel battleaxe",
        level: 40,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1365,
        outputQuantity: 1,
        slot: "battleaxe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_battleaxe",
        name: "Mithril battleaxe",
        level: 60,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1369,
        outputQuantity: 1,
        slot: "battleaxe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_battleaxe",
        name: "Adamant battleaxe",
        level: 80,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1371,
        outputQuantity: 1,
        slot: "battleaxe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_battleaxe",
        name: "Rune battleaxe",
        level: 95,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1373,
        outputQuantity: 1,
        slot: "battleaxe",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_chainbody",
        name: "Bronze chainbody",
        level: 11,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1103,
        outputQuantity: 1,
        slot: "chainbody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_chainbody",
        name: "Iron chainbody",
        level: 26,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1101,
        outputQuantity: 1,
        slot: "chainbody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_chainbody",
        name: "Steel chainbody",
        level: 41,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1105,
        outputQuantity: 1,
        slot: "chainbody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_chainbody",
        name: "Mithril chainbody",
        level: 61,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1109,
        outputQuantity: 1,
        slot: "chainbody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_chainbody",
        name: "Adamant chainbody",
        level: 81,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1111,
        outputQuantity: 1,
        slot: "chainbody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_chainbody",
        name: "Rune chainbody",
        level: 96,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1113,
        outputQuantity: 1,
        slot: "chainbody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_kiteshield",
        name: "Bronze kiteshield",
        level: 12,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1189,
        outputQuantity: 1,
        slot: "kiteshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_kiteshield",
        name: "Iron kiteshield",
        level: 27,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1191,
        outputQuantity: 1,
        slot: "kiteshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_kiteshield",
        name: "Steel kiteshield",
        level: 42,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1193,
        outputQuantity: 1,
        slot: "kiteshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_kiteshield",
        name: "Mithril kiteshield",
        level: 62,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1197,
        outputQuantity: 1,
        slot: "kiteshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_kiteshield",
        name: "Adamant kiteshield",
        level: 82,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1199,
        outputQuantity: 1,
        slot: "kiteshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_kiteshield",
        name: "Rune kiteshield",
        level: 97,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1201,
        outputQuantity: 1,
        slot: "kiteshield",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_claws",
        name: "Bronze claws",
        level: 13,
        xp: 25,
        barItemId: 2349,
        barCount: 2,
        outputItemId: 3095,
        outputQuantity: 1,
        slot: "claws",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_claws",
        name: "Iron claws",
        level: 28,
        xp: 50,
        barItemId: 2351,
        barCount: 2,
        outputItemId: 3096,
        outputQuantity: 1,
        slot: "claws",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_claws",
        name: "Steel claws",
        level: 43,
        xp: 75,
        barItemId: 2353,
        barCount: 2,
        outputItemId: 3097,
        outputQuantity: 1,
        slot: "claws",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_claws",
        name: "Mithril claws",
        level: 63,
        xp: 100,
        barItemId: 2359,
        barCount: 2,
        outputItemId: 3099,
        outputQuantity: 1,
        slot: "claws",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_claws",
        name: "Adamant claws",
        level: 83,
        xp: 125,
        barItemId: 2361,
        barCount: 2,
        outputItemId: 3100,
        outputQuantity: 1,
        slot: "claws",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_claws",
        name: "Rune claws",
        level: 98,
        xp: 150,
        barItemId: 2363,
        barCount: 2,
        outputItemId: 3101,
        outputQuantity: 1,
        slot: "claws",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_2h",
        name: "Bronze 2h sword",
        level: 14,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1307,
        outputQuantity: 1,
        slot: "2h",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_2h",
        name: "Iron 2h sword",
        level: 29,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1309,
        outputQuantity: 1,
        slot: "2h",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_2h",
        name: "Steel 2h sword",
        level: 44,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1311,
        outputQuantity: 1,
        slot: "2h",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_2h",
        name: "Mithril 2h sword",
        level: 64,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1315,
        outputQuantity: 1,
        slot: "2h",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_2h",
        name: "Adamant 2h sword",
        level: 84,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1317,
        outputQuantity: 1,
        slot: "2h",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_2h",
        name: "Rune 2h sword",
        level: 99,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1319,
        outputQuantity: 1,
        slot: "2h",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_platelegs",
        name: "Bronze platelegs",
        level: 16,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1075,
        outputQuantity: 1,
        slot: "platelegs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_platelegs",
        name: "Iron platelegs",
        level: 31,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1067,
        outputQuantity: 1,
        slot: "platelegs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_platelegs",
        name: "Steel platelegs",
        level: 46,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1069,
        outputQuantity: 1,
        slot: "platelegs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_platelegs",
        name: "Mithril platelegs",
        level: 66,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1071,
        outputQuantity: 1,
        slot: "platelegs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_platelegs",
        name: "Adamant platelegs",
        level: 86,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1073,
        outputQuantity: 1,
        slot: "platelegs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_platelegs",
        name: "Rune platelegs",
        level: 99,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1079,
        outputQuantity: 1,
        slot: "platelegs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_plateskirt",
        name: "Bronze plateskirt",
        level: 16,
        xp: 37.5,
        barItemId: 2349,
        barCount: 3,
        outputItemId: 1087,
        outputQuantity: 1,
        slot: "plateskirt",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_plateskirt",
        name: "Iron plateskirt",
        level: 31,
        xp: 75,
        barItemId: 2351,
        barCount: 3,
        outputItemId: 1081,
        outputQuantity: 1,
        slot: "plateskirt",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_plateskirt",
        name: "Steel plateskirt",
        level: 46,
        xp: 112.5,
        barItemId: 2353,
        barCount: 3,
        outputItemId: 1083,
        outputQuantity: 1,
        slot: "plateskirt",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_plateskirt",
        name: "Mithril plateskirt",
        level: 66,
        xp: 150,
        barItemId: 2359,
        barCount: 3,
        outputItemId: 1085,
        outputQuantity: 1,
        slot: "plateskirt",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_plateskirt",
        name: "Adamant plateskirt",
        level: 86,
        xp: 187.5,
        barItemId: 2361,
        barCount: 3,
        outputItemId: 1091,
        outputQuantity: 1,
        slot: "plateskirt",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_plateskirt",
        name: "Rune plateskirt",
        level: 99,
        xp: 225,
        barItemId: 2363,
        barCount: 3,
        outputItemId: 1093,
        outputQuantity: 1,
        slot: "plateskirt",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_platebody",
        name: "Bronze platebody",
        level: 18,
        xp: 62.5,
        barItemId: 2349,
        barCount: 5,
        outputItemId: 1117,
        outputQuantity: 1,
        slot: "platebody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_platebody",
        name: "Iron platebody",
        level: 33,
        xp: 125,
        barItemId: 2351,
        barCount: 5,
        outputItemId: 1115,
        outputQuantity: 1,
        slot: "platebody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_platebody",
        name: "Steel platebody",
        level: 48,
        xp: 187.5,
        barItemId: 2353,
        barCount: 5,
        outputItemId: 1119,
        outputQuantity: 1,
        slot: "platebody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_platebody",
        name: "Mithril platebody",
        level: 68,
        xp: 250,
        barItemId: 2359,
        barCount: 5,
        outputItemId: 1121,
        outputQuantity: 1,
        slot: "platebody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_platebody",
        name: "Adamant platebody",
        level: 88,
        xp: 312.5,
        barItemId: 2361,
        barCount: 5,
        outputItemId: 1123,
        outputQuantity: 1,
        slot: "platebody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_platebody",
        name: "Rune platebody",
        level: 99,
        xp: 375,
        barItemId: 2363,
        barCount: 5,
        outputItemId: 1127,
        outputQuantity: 1,
        slot: "platebody",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_nails",
        name: "Bronze nails",
        level: 4,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 4819,
        outputQuantity: 15,
        slot: "nails",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_nails",
        name: "Iron nails",
        level: 19,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 4820,
        outputQuantity: 15,
        slot: "nails",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_nails",
        name: "Steel nails",
        level: 34,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 1539,
        outputQuantity: 15,
        slot: "nails",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_nails",
        name: "Mithril nails",
        level: 54,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 4822,
        outputQuantity: 15,
        slot: "nails",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_nails",
        name: "Adamant nails",
        level: 74,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 4823,
        outputQuantity: 15,
        slot: "nails",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_nails",
        name: "Rune nails",
        level: 89,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 4824,
        outputQuantity: 15,
        slot: "nails",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_arrowheads",
        name: "Bronze arrowtips",
        level: 5,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 39,
        outputQuantity: 15,
        slot: "arrowheads",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_arrowheads",
        name: "Iron arrowtips",
        level: 20,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 40,
        outputQuantity: 15,
        slot: "arrowheads",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_arrowheads",
        name: "Steel arrowtips",
        level: 35,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 41,
        outputQuantity: 15,
        slot: "arrowheads",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_arrowheads",
        name: "Mithril arrowtips",
        level: 55,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 42,
        outputQuantity: 15,
        slot: "arrowheads",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_arrowheads",
        name: "Adamant arrowtips",
        level: 75,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 43,
        outputQuantity: 15,
        slot: "arrowheads",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_arrowheads",
        name: "Rune arrowtips",
        level: 90,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 44,
        outputQuantity: 15,
        slot: "arrowheads",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_knives",
        name: "Bronze knife",
        level: 7,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 864,
        outputQuantity: 5,
        slot: "knives",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_knives",
        name: "Iron knife",
        level: 22,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 863,
        outputQuantity: 5,
        slot: "knives",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_knives",
        name: "Steel knife",
        level: 37,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 865,
        outputQuantity: 5,
        slot: "knives",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_knives",
        name: "Mithril knife",
        level: 57,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 866,
        outputQuantity: 5,
        slot: "knives",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_knives",
        name: "Adamant knife",
        level: 77,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 867,
        outputQuantity: 5,
        slot: "knives",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_knives",
        name: "Rune knife",
        level: 92,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 868,
        outputQuantity: 5,
        slot: "knives",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_bolts",
        name: "Bronze bolts (unf)",
        level: 3,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 9375,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_bolts",
        name: "Iron bolts (unf)",
        level: 18,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 9377,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_bolts",
        name: "Steel bolts (unf)",
        level: 33,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 9378,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_bolts",
        name: "Mithril bolts (unf)",
        level: 53,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 9379,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_bolts",
        name: "Adamant bolts (unf)",
        level: 73,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 9380,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_bolts",
        name: "Rune bolts (unf)",
        level: 88,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 9381,
        outputQuantity: 10,
        slot: "bolts",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_limbs",
        name: "Bronze limbs",
        level: 6,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 9420,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_limbs",
        name: "Iron limbs",
        level: 23,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 9423,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_limbs",
        name: "Steel limbs",
        level: 36,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 9425,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_limbs",
        name: "Mithril limbs",
        level: 56,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 9427,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_limbs",
        name: "Adamant limbs",
        level: 76,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 9429,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_limbs",
        name: "Rune limbs",
        level: 91,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 9431,
        outputQuantity: 1,
        slot: "limbs",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_other_3",
        name: "Bronze javelin heads",
        level: 3,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 19570,
        outputQuantity: 5,
        slot: "other_3",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_other_3",
        name: "Iron javelin heads",
        level: 17,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 19572,
        outputQuantity: 5,
        slot: "other_3",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_other_3",
        name: "Steel javelin heads",
        level: 32,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 19574,
        outputQuantity: 5,
        slot: "other_3",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_other_3",
        name: "Mithril javelin heads",
        level: 52,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 19576,
        outputQuantity: 5,
        slot: "other_3",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "adamant_other_3",
        name: "Adamant javelin heads",
        level: 72,
        xp: 62.5,
        barItemId: 2361,
        barCount: 1,
        outputItemId: 19578,
        outputQuantity: 5,
        slot: "other_3",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "rune_other_3",
        name: "Rune javelin heads",
        level: 87,
        xp: 75,
        barItemId: 2363,
        barCount: 1,
        outputItemId: 19580,
        outputQuantity: 5,
        slot: "other_3",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "bronze_other_1",
        name: "Bronze wire",
        level: 4,
        xp: 12.5,
        barItemId: 2349,
        barCount: 1,
        outputItemId: 1794,
        outputQuantity: 1,
        slot: "other_1",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_other_1",
        name: "Iron spit",
        level: 17,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 7225,
        outputQuantity: 1,
        slot: "other_1",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_other_1",
        name: "Steel studs",
        level: 36,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 2370,
        outputQuantity: 1,
        slot: "other_1",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "mithril_other_1",
        name: "Mithril grapple tip",
        level: 59,
        xp: 50,
        barItemId: 2359,
        barCount: 1,
        outputItemId: 9416,
        outputQuantity: 1,
        slot: "other_1",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "iron_other_2",
        name: "Oil lantern frame",
        level: 26,
        xp: 25,
        barItemId: 2351,
        barCount: 1,
        outputItemId: 4540,
        outputQuantity: 1,
        slot: "other_2",
        animation: 898,
        delayTicks: 4
    },
    {
        id: "steel_other_2",
        name: "Bullseye lantern (unf)",
        level: 49,
        xp: 37.5,
        barItemId: 2353,
        barCount: 1,
        outputItemId: 4544,
        outputQuantity: 1,
        slot: "other_2",
        animation: 898,
        delayTicks: 4
    }
];

export const SMELTING_RECIPES: SmeltingRecipe[] = [
    {
        id: "smelt_bronze_bar",
        name: "Bronze bar",
        level: 1,
        xp: 6.2,
        inputs: [
            { itemId: 436, quantity: 1 },
            { itemId: 438, quantity: 1 },
        ],
        outputItemId: 2349,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Copper + Tin ore",
    },
    {
        id: "smelt_blurite_bar",
        name: "Blurite bar",
        level: 13,
        xp: 8,
        inputs: [{ itemId: 668, quantity: 1 }],
        outputItemId: 9467,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Blurite ore",
    },
    {
        id: "smelt_iron_bar",
        name: "Iron bar",
        level: 15,
        xp: 12.5,
        inputs: [{ itemId: 440, quantity: 1 }],
        outputItemId: 2351,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "iron",
        ingredientsLabel: "Iron ore",
    },
    {
        id: "smelt_silver_bar",
        name: "Silver bar",
        level: 20,
        xp: 13.7,
        inputs: [{ itemId: 442, quantity: 1 }],
        outputItemId: 2355,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Silver ore",
    },
    {
        id: "smelt_steel_bar",
        name: "Steel bar",
        level: 30,
        xp: 17.5,
        inputs: [
            { itemId: 440, quantity: 1 },
            { itemId: 453, quantity: 2 },
        ],
        outputItemId: 2353,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Iron ore + 2 Coal",
    },
    {
        id: "smelt_gold_bar",
        name: "Gold bar",
        level: 40,
        xp: 22.5,
        inputs: [{ itemId: 444, quantity: 1 }],
        outputItemId: 2357,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Gold ore",
    },
    {
        id: "make_steel_cannonballs_double",
        name: "Steel cannonball",
        level: 35,
        xp: 51.2,
        inputs: [{ itemId: 2353, quantity: 2 }],
        requiredToolItemIds: [27012, 27013],
        outputItemId: 2,
        outputQuantity: 8,
        animation: FURNACE_ANIMATION,
        delayTicks: 8,
        successType: "guaranteed",
        ingredientsLabel: "2 Steel bars + Double ammo mould",
    },
    {
        id: "make_steel_cannonballs",
        name: "Steel cannonball",
        level: 35,
        xp: 25.6,
        inputs: [{ itemId: 2353, quantity: 1 }],
        requiredToolItemIds: [4],
        outputItemId: 2,
        outputQuantity: 4,
        animation: FURNACE_ANIMATION,
        delayTicks: 8,
        successType: "guaranteed",
        ingredientsLabel: "Steel bar + Ammo mould",
    },
    {
        id: "smelt_lovakite_bar",
        name: "Lovakite bar",
        level: 45,
        xp: 20,
        inputs: [
            { itemId: 13356, quantity: 1 },
            { itemId: 453, quantity: 2 },
        ],
        allowedLocIds: [28562],
        outputItemId: 13354,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Lovakite ore + 2 Coal",
    },
    {
        id: "smelt_mithril_bar",
        name: "Mithril bar",
        level: 50,
        xp: 30,
        inputs: [
            { itemId: 447, quantity: 1 },
            { itemId: 453, quantity: 4 },
        ],
        outputItemId: 2359,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Mithril ore + 4 Coal",
    },
    {
        id: "smelt_adamantite_bar",
        name: "Adamantite bar",
        level: 70,
        xp: 38,
        inputs: [
            { itemId: 449, quantity: 1 },
            { itemId: 453, quantity: 6 },
        ],
        outputItemId: 2361,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Adamantite ore + 6 Coal",
    },
    {
        id: "smelt_runite_bar",
        name: "Runite bar",
        level: 85,
        xp: 50,
        inputs: [
            { itemId: 451, quantity: 1 },
            { itemId: 453, quantity: 8 },
        ],
        outputItemId: 2363,
        outputQuantity: 1,
        animation: FURNACE_ANIMATION,
        delayTicks: 4,
        successType: "guaranteed",
        ingredientsLabel: "Runite ore + 8 Coal",
    },
];

export function getSmithingRecipeById(id: string): SmithingRecipe | undefined {
    return SMITHING_RECIPES.find((recipe) => recipe.id === id);
}

export function getSmithingRecipeByBarAndSlot(
    barItemId: number,
    slot: SmithingProductSlot,
): SmithingRecipe | undefined {
    return SMITHING_RECIPES.find((recipe) => recipe.barItemId === barItemId && recipe.slot === slot);
}

export function getSmeltingRecipeById(id: string): SmeltingRecipe | undefined {
    return SMELTING_RECIPES.find((recipe) => recipe.id === id);
}

export function calculateIronSmeltChance(level: number): number {
    // Regular-furnace iron is always a 50% roll. Ring of Forging is handled
    // by the caller as an explicit override.
    void level;
    return 0.5;
}

export function computeSmeltingBatchCount(
    entries: Array<{ itemId: number; quantity: number }>,
    recipe: SmeltingRecipe,
): number {
    if (!Array.isArray(recipe.inputs) || recipe.inputs.length === 0) {
        return 0;
    }
    let minBatch = Number.MAX_SAFE_INTEGER;
    for (const req of recipe.inputs) {
        const required = Math.max(1, req.quantity);
        const available = countItem(entries, req.itemId);
        const possible = Math.floor(available / required);
        minBatch = Math.min(minBatch, possible);
        if (minBatch <= 0) return 0;
    }
    if (minBatch === Number.MAX_SAFE_INTEGER) return 0;
    return Math.max(0, minBatch);
}

function countItem(entries: Array<{ itemId: number; quantity: number }>, itemId: number): number {
    if (!Array.isArray(entries)) return 0;
    let total = 0;
    for (const entry of entries) {
        if (!entry) continue;
        if (entry.itemId !== itemId) continue;
        total += Math.max(0, entry.quantity);
    }
    return total;
}

export function hasRequiredSmeltingTools(
    entries: Array<{ itemId: number; quantity: number }>,
    recipe: SmeltingRecipe,
): boolean {
    const required = recipe.requiredToolItemIds;
    if (!required || required.length === 0) return true;
    return required.some((itemId) => countItem(entries, itemId) > 0);
}
